### ISSUE TITLE
ServerException	FileError: Error adding a file

### ISSUE THREAD

**Issue by sapura** [sismics/docs#108]
hi i encountered ServerException	FileError: Error adding a file

please advise how to solve

thanks a lot

**Comment by jendib** [comment]
Could you attach the `server.log`?
It should be in `/var/docs/log` depending how you configured your installation.

**Comment by sapura** [comment]
hi I'm using jetty 9
I could not find /var/docs/log in my system
Can you advise me where the /var/docs/log located?

**Comment by jendib** [comment]
Try adding [this file](https://github.com/sismics/docs/blob/master/docs.xml) in the same directory as your `docs.war` (they need to have the same name). In this file you can configure the storage directory (where you'll find the log, database and file storage).

**Comment by sapura** [comment]
is this the correct xml configuration because my not able to start ?  i still getting the same error 


 
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/</Set>
  <Set name="war"><SystemProperty name="jetty.data" default="."/>/docs.war</Set>
  <Call class="java.lang.System" name="setProperty">
    <Arg>docs.home</Arg>
    <Arg>/data</Arg>
  </Call>

</Configure>


and do i need to create the data folder?

**Comment by jendib** [comment]
Yes you need to create a /data folder, or change it to wherever you want.

**Comment by sapura** [comment]
your doc.xml syntax seems not correct, I'm not able to start the server, can you please send me the working one thanks

**Comment by jendib** [comment]
I'm using it myself on Jetty 9, it's working. You just need to customize it for your needs.
