### ISSUE TITLE
Latest release does not work out-of-the-box

### ISSUE THREAD

**Issue by mmaenz** [sismics/docs#122]
Hi,

wanted to test it but fails to run. Don't know the exact reason. Tried Tomcat 8&9 and Glassfish.
Just deployed the war file. Nothing else. Creates the database as seen in the log-files.

The download package is large, there are old log-files in sismicsdocs/log directory.

Running on java 1.8.0_112 on osx 10.12 with mentioned Tomcat and Glassfish.

May you put up a working version?

Thanks!

**Comment by jendib** [comment]
What do you have in your log file?

**Comment by mmaenz** [comment]
Thanks for the work, I really appreciate it!

Will give it a try the next days.

**Comment by jendib** [comment]
The release is fixed and available here: https://github.com/sismics/docs/releases/tag/v1.4
