### ISSUE TITLE
Building with Docker fails

### ISSUE THREAD

**Issue by almereyda** [sismics/docs#124]
As the Dockerfile uses [build artifacts](http://blog.terranillius.com/post/docker_builder_pattern/) it seems appropriate to also [build those within a Docker environment](http://stackoverflow.com/questions/27767264/how-to-dockerize-maven-project-and-how-many-ways-to-accomplish-it):

```
$ docker run -it --rm \
       -v "$(pwd)":/opt/maven \
       -w /opt/maven \
       maven:3-jdk-7 \  
> mvn clean -DskipTests install
```
Unfortunately this fails:

```
find: pred.c:1932: launch: Assertion `starting_desc >= 0' failed.
/usr/local/bin/mvn-entrypoint.sh: line 23:     9 Aborted                 (core dumped) find /usr/share/maven/ref/ -type f -exec bash -eu -c 'copy_reference_file /usr/share/maven/ref/ "$1" "$2"' _ {} "$log" \;
```

Also from `docs-web` for generating the desired WAR artefacts for the application Dockerfile:

```
$ docker run -it --rm \
       -v "$(pwd)":/opt/maven \
       -w /opt/maven \
       maven:3-jdk-7 \
mvn -Pprod -DskipTests clean install
find: pred.c:1932: launch: Assertion `starting_desc >= 0' failed.
/usr/local/bin/mvn-entrypoint.sh: line 23:     9 Aborted                 (core dumped) find /usr/share/maven/ref/ -type f -exec bash -eu -c 'copy_reference_file /usr/share/maven/ref/ "$1" "$2"' _ {} "$log" \;
```

**Comment by jendib** [comment]
I will need your Maven output to understand what the problem is.
As you can see on Travis https://travis-ci.org/sismics/docs the project builds from a container without any issue.

**Comment by almereyda** [comment]
Oh pardon, I hadn't witnessed the existing Dockerfile.

    docker run --rm -p 8080:8080 sismics/docs:latest

Runs fine, but https://github.com/sismics/docs/commit/6b0106e3850a09343f4900b11bbc5ce9b7dafc82 wasn't present back then, either. Thank you.

**Comment by jendib** [comment]
Yes I pushed a public image recently, so you don't need to compile anything :)
