### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jkathir** [sismics/docs#132]
1. Google like search engine like https://ambar.cloud/
2. Next, Previous, Go to Option like Folio Views
3. Number of hits found before hitting the actual search like Folio Views
4. Import options from Zim, Treepad or other wikis.
5. Handling huge number of documents by providing quick search via Solr or Apache Lucene
6. Support for tamil language
7. Having tags for each document (Reference: https://collatenotes.com/)
8 .Built in web clipper (save webpages locally) - (Reference: https://collatenotes.com/)
9. Support for full text search in huge text nodes - example atleast 10,000 nodes with 100 kb of text each. Most note-taking software couldn't handle such huge content due to missing indexing
Quickest search results via indexing through Apache Lucene like docFetcher (http://www.techrepublic.com/blog/linux-and-open-source/portable-desktop-search-make-the-most-of-docfetcher/)

**Comment by jendib** [comment]
For 1, 5, 8, it's already done with the search field. It searches inside the documents using Lucene as a fulltext search engine.
For 7 it's done too, you can add tags on documents.
For 3, the search is done as you type, so there is no real need for this.

2 and 4 are good ideas, we could add a quick navigation and some importing features.
For 6, the app doesn't support multilanguage yet but it's on my roadmap. Also I don't know this language :)

**Comment by jkathir** [comment]
#3, the user can add more words if the number of records found are huge. else always the user has to guess the records.
#6 - there are lots of free editors supports tamil language. Also lots of tamil fonts already available.

For tamil fonts, please go through the following steps

Download http://www.azhagi.com/ software which is the tamil editor like
microsoft word
Type the text in different font like choosing in microsoft word
You can see the font as well as the text
Make sure the text is being supported

Fonts for your kind reference:

http://www.azhagi.com/freefonts.html#top1
http://tamil.indiatyping.com/index.php/download-tamil-font
http://www.freetamilfont.com/

**Comment by jendib** [comment]
The problem is not about the font, it's just that I am the sole developer of this project and I don't know your language. If you want to do it, I would accept your pull request.
