### ISSUE TITLE
Need complete steps for setup the docs in Windows Machine

### ISSUE THREAD

**Issue by jkathir** [sismics/docs#133]
I'm not sure how to setup the docs in windows machine. A detailed steps with screenshots would be helpful for everyone. Please consider this.

**Comment by jkathir** [comment]
could you please update the steps to install the tomcat on windows 32 bit/64 bit supported version as well as other OS...a little bit of information would save a lot of time..else this can only be used by a developer and not everyone..else there should be a zip file with pre-deployed tomcat version for windows, linux and mac...please consider this..

**Comment by jendib** [comment]
The war file in the release section or the Docker image are the main sources to install the application.
However, any pull request to more detailed installation steps is welcome.

**Comment by shrideh** [comment]
1. https://tomcat.apache.org/download-80.cgi
2. 64-bit Windows zip or 32bit
3. install it and full install and start it 
4. docs-web-1.9.war dl and move it to C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps
5. http://localhost:8080/docs-web-1.9/
6. admin admin
