### ISSUE TITLE
Need help on installation...

### ISSUE THREAD

**Issue by jkathir** [sismics/docs#134]
I have downloaded tomcat and now i don't know which folder i need to copy to the webapps folder.

If i need to have maven setup, docker or something technical it would be very hard and only developers can evaluate it...

Capture the detailed steps with screenshots else atleast have a folder to copy and paste it in webapps folder so that the steps would be minimal..

Now i am not sure whether i need everything...Please kindly help me in detail.

**Comment by jkathir** [comment]
any suggestion?

**Comment by jendib** [comment]
Downlaod the latest war file here https://github.com/sismics/docs/releases and put it in the webapps folder.
Using the Docker image is still the easier way to run the app (see https://github.com/sismics/docs#install-with-docker).

**Comment by jkathir** [comment]
great..i will test and update you..

**Comment by jkathir** [comment]
How to install docker in windows and run the docker image? could you please kindly assist me
