### ISSUE TITLE
Error on PDF upload..No error message in tomcat logs..Unable to find out the problem

### ISSUE THREAD

**Issue by jkathir** [sismics/docs#135]
![error_sismics](https://user-images.githubusercontent.com/30680308/29929854-4ee28c0e-8e8a-11e7-899f-02645b3e393f.jpg)

Please kindly advice how to fix it? uploaded 2 pdf file one is error and other is pro-long pending.

Environment:
Windows 10 - 64 Bit
jdk1.8.0_101
apache-tomcat-9.0.0.M26-windows-x64

**Comment by jendib** [comment]
You have an error in the logs, see "1 new error" on top of your screenshot.
