### ISSUE TITLE
Deploying docs-web-1.5.war with tomcat 8 results in 404

### ISSUE THREAD

**Issue by deanrw** [sismics/docs#183]
I've uploaded and deployed the new v1.5 .war file on my tomcat 8 server. Tomcat's manager and logs suggest it's been deployed correctly but loading the web address (linked from tomcat's manger app) results in a 404.

I've tried v1.4 and I can reach the login screen fine. I note the absence of a 'index.html' file in the deployed v1.5 webapps directory (which I assume is the cause of the 404), whereas the v1.4 contains one.

Unless there's something else I'm missing?

Many thanks

**Comment by jendib** [comment]
I'm actually only using Jetty, but it should work on all servlet containers, I'll take a look.

**Comment by jendib** [comment]
I actually botched the war release. Currently uploading the right one now. I tested it on a blank Tomcat and it now works perfectly.

**Comment by deanrw** [comment]
Awesome, it now works flawlessly.

Many thanks for your quick response!
