### ISSUE TITLE
OCR images-only PDF

### ISSUE THREAD

**Issue by jendib** [sismics/docs#186]

**Comment by schemen** [comment]
Yes Please! I consider this very important as I use it for scanning paper documents

**Comment by jendib** [comment]
OCR is already working for images files if you really need it quickly ;)
This issue is just for the special case of PDF with only images in it

**Comment by schemen** [comment]
Indeed =) Well I think it's quite important to support it as few people probably scan to images instead of PDFs. 

Cool project though, looking forward to it maturing!

**Comment by jendib** [comment]
I finished the feature in the master branch, please test and tell me if it's all good for you (The Docker image sismics/docs:latest is up to date if you are using this).
I'm unit testing with this PDF: https://github.com/sismics/docs/blob/master/docs-core/src/test/resources/file/scanned.pdf

**Comment by schemen** [comment]
I tested it with a few documents, it seems to be working! Thank you!
