### ISSUE TITLE
Add info about installing Java Cryptography Extension

### ISSUE THREAD

**Issue by fernandodiacenco** [sismics/docs#187]
Hello,

Deploying SismicsDocs 1.5  war file on a Tomcat version 8.5.28 on Windows Server 2012r2 x64 I've got the following error:

> FAIL - Application at context path [/C:DISCOSSismicsDocsdocs-web-1.5] could not be started
> FAIL - Encountered exception [org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/C:DISCOSSismicsDocsdocs-web-1.5]]]

Interestingly it appears that the path is wrong, it should be a subfolder on C:\Discos, but this behavior doest not happen for example deploying Libreplan 1.4.1 on the same server

Is there anything wrong on my end?

Thanks.

**Comment by jendib** [comment]
I extract a blank version of Tomcat 8.5 on Windows 10 and just dropped the war file in webapps/, and it works fine.
Can you detail the configuration you did to get this context path?

**Comment by fernandodiacenco** [comment]
Thanks for answering!

I selected the file and clicked on deploy, nothing fancy

![01](https://user-images.githubusercontent.com/2643364/36947467-e68f3c8a-1faa-11e8-9106-065dbd34a9a1.jpg)

---

![02](https://user-images.githubusercontent.com/2643364/36947468-e6b6d970-1faa-11e8-900d-e817d439f0de.jpg)

---

If i just drop the war file on the webapps folder, will it work?

Thanks.

**Comment by jendib** [comment]
The context path is strange, but I don't think the problem comes from here. Can you provide the log file?
It should be in `C:\Users\<You>\AppData\Roaming\Sismics\Docs\log`

**Comment by fernandodiacenco** [comment]
Logs were not helpful, something about not being able to create directory in the webapps folder, even with full permissions

BUT I've got it working now

Followed your tip and put the .war file on webapps folder, but instead I used the menu above the "select file" menu to deploy the war file, and it started working correctly now

![03](https://user-images.githubusercontent.com/2643364/36947981-7ab289d8-1fb2-11e8-89cf-1d60611faf42.jpg)

It appears there is something wrong in the way my tomcat installation "autodeploy" the application

But anyway its not a SismicsDocs issue, thanks for the help!

**Comment by jendib** [comment]
Great! 👍

**Comment by fernandodiacenco** [comment]
Oops sorry to reopen, I takled too soon, I can't upload a single file without getting "Upload Error"

The server log page only shows: 

> 3/4/18 2:11 PM | ServerException | FileError: Error adding a file

The more compreensive log fil is cryptic to me:

[sismicslogs.txt](https://github.com/sismics/docs/files/1778720/sismicslogs.txt)

**Comment by jendib** [comment]
You need to install the Java Cryptography Extension from Oracle.
If you are using Java 7, it's here: http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html

I will add explanations on the README to make this clear.

**Comment by fernandodiacenco** [comment]
I tried the extension but the app ended in a state of always "loading"

So I upgraded to Tomcat 9 and the latest Java Runtime 8 and everything worked out of the box, thanks!

**Comment by jendib** [comment]
Ok great. I will still keep this open to document the JCE.
