### ISSUE TITLE
Document expiration date with reminder

### ISSUE THREAD

**Issue by fernandodiacenco** [sismics/docs#191]
Hello again,

Is it possible to define a file expiration date and warnings?

For example, I upload a contract which will expire in a year or so, when nearing the expiration date I receive an email from Sismicsdocs warning me about it

If its not available at this time, can this be added to the wishlist?

Thanks!

**Comment by jendib** [comment]
It's indeed not available, but it can be added for sure!

**Comment by theodormachnich** [comment]
Maybe you can also add a calendar or task scheduler.
It's a idea in the same direction.
Thank you, great work!

**Comment by jendib** [comment]
I think it's better to keep services separated. There is already great calendar out there to handle this perfectly. However I could do a ical export for this feature.

**Comment by srigurubyo** [comment]
Hi, wondering, do you have any outlook on this feature?

**Comment by jendib** [comment]
I'm still not sure how to integrate it nicely. I would like it to be part of the workflow system.

**Comment by srigurubyo** [comment]
In my opinion, adding it as part of metadata would look nice as we already have 'Creation Date".

"Expiration Date" property after "Creation Date" will make it uniform and look good.
