### ISSUE TITLE
Add ability to see if document has OCR data or not and rescan it

### ISSUE THREAD

**Issue by schemen** [sismics/docs#201]
Right now I have to check in the logs to see if a document has been OCR'd. It would be great to see an indication, maybe in the activity block that shows that a document finished the OCR process. Also, it would be great to be able to "re-ocr" a document (In case of a language change?).

Cheers!

- [x] File processing indicator
- [ ] Reprocess a file manually

**Comment by jendib** [comment]
Good idea!

**Comment by jendib** [comment]
File processing indicator done:
![image](https://user-images.githubusercontent.com/2623413/37373356-8c9ee194-2716-11e8-9620-473d00b3216f.png)

**Comment by schemen** [comment]
That looks really good! I suppose those that are done will be a check =)

**Comment by jendib** [comment]
No, the indicator will be just gone, but maybe a check would be useful to be sure it's processed
