### ISSUE TITLE
Outgoing actions for workflow transition

### ISSUE THREAD

**Issue by torak1981** [sismics/docs#202]
- [x] For each transition of each workflow step, affect a list of actions
- [x] Implement a first action: add a tag

**Comment by jendib** [comment]
You are thinking of a new workflow step type?
Or just extending the current system by adding some kind of outgoing action for every transition (validate, appove, reject) ? I think this would be actually more flexible. We could add more action afterward (starting with "Add a tag" action).

**Comment by torak1981** [comment]
You're right. A outgoing action would be more flexible and you could add different tags based on the result (approved/declined).

**Comment by schemen** [comment]
To add to that, any chance that documents with certain Tags (i.e. "Pending") enter a workflow automatically and not get OCR'd?

With that you can have the basic workflow of checking metadata, fixing language if necessary and once approved it will get OCR'd

**Comment by jendib** [comment]
OCR could be another action, so the document would be OCR'd again after exiting a certain workflow step.
Starting it automatically is something else. The importing tool (if not using the UI) could be responsible for this (you can start a workflow through the API).

**Comment by schemen** [comment]
Sounds good!
And yes I think it would be good to add the ability to push a document into a workflow directly from any action. I'm currently testing the inbox scanner, auto-tagging is already possible, workflow addition would be great

**Comment by jendib** [comment]
I finished the workflow definition. It starts to look a bit messy, but it should do for now.

![image](https://user-images.githubusercontent.com/2623413/37300664-cd4d06d0-2626-11e8-82b4-abb9d18cf892.png)

**Comment by torak1981** [comment]
Nice work. That‘s exactly what I had in mind :)


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schemen** [comment]
Very nice!

**Comment by jendib** [comment]
All done 👍

**Comment by schemen** [comment]
Sorry to dig out a closed issue but is it possible to add "Remove Tag" in parallel to this?

**Comment by jendib** [comment]
See #205
