### ISSUE TITLE
Need your help for context path

### ISSUE THREAD

**Issue by tat32446** [sismics/docs#209]
i had deployed the application in my machine by downloading code from https://github.com/sismics/docs

can some one help me with context path?

**Comment by jendib** [comment]
How did you install it? Which container (Tomcat, Jetty, ...)?

**Comment by tat32446** [comment]
I have tomcat server ..I had used build command to generate war and deploy the same to tomcat server

**Comment by jendib** [comment]
If you didn't configure anything else, the context path should be the WAR filename (without .war)

**Comment by tat32446** [comment]
Yaa..but same is not working..I had try with jetty as well 

It is giving me 

:8080

Directory :/ word in red color

**Comment by jendib** [comment]
It's hard to help you without more informations. Can you please detail what is not working and what you did precisely? With screenshots if possible.

**Comment by tat32446** [comment]
after below 2 commands 

mvn clean -DskipTests install
  cd docs-web
mvn jetty:run

i got below image in browser..

![image](https://user-images.githubusercontent.com/37444864/37528098-b93d0358-2959-11e8-96a1-8a55d1d6f23c.png)

**Comment by tat32446** [comment]
adding image of cmd console.

![image](https://user-images.githubusercontent.com/37444864/37528287-46c71682-295a-11e8-93cc-d159dee6b1f1.png)

**Comment by jendib** [comment]
The documentation says you have to execute another command to build (https://github.com/sismics/docs#build-a-war-to-deploy-to-your-servlet-container).
Also you can download pre-build war files here: https://github.com/sismics/docs/releases

**Comment by tat32446** [comment]
i just went through the code and got the context path...thank you for the help 

it look like this: http://localhost:8080/docs-web/src/#/login

**Comment by jendib** [comment]
But you are using an uncompiled webapp (big javascript files, nothing packaged). You built the war with the wrong command.

**Comment by tat32446** [comment]
no no above command is for running using jetty server and below command is for building war
mvn -Pprod -DskipTests clean install. i had tried both the things ... but the problem was struggling for context path... url path  is little tricky not like the normal web application .. so i went through the code and finally found correct url path.. :)

**Comment by jendib** [comment]
But still, you are using uncompiled unpackaged files.
You should run `mvn -Pprod -DskipTests clean install` to build a war, and then drop this war in Tomcat or Jetty.
`mvn jetty:run` is only for development purpose and should not be used otherwise.
