### ISSUE TITLE
File Importer: directly create document without quick upload

### ISSUE THREAD

**Issue by torak1981** [sismics/docs#210]
Hi,

I think it would be useful, if you could choose between import to quick upload queue or directly creating a document with the file name and a defined tag (or a defined workflow). So you could setup a user "scanner" and poll a directory where the scanner puts all the scanned documents. The documents would end up as a real document in the system and with the tag rights management a defined user set could edit the document.
With the quick upload queue only one user can edit the scanned documents.
I hope it's understandable ;)

**Comment by jendib** [comment]
Yes it's a good idea. The tag on the created document could come from the folder name for example.
If you have any Javascript skill, feel free to submit a pull request 😎

**Comment by jendib** [comment]
We can now choose a tag before importing documents (and not quick upload files).
