### ISSUE TITLE
Deploying error docs-web-1.5.war with tomcat 8 

### ISSUE THREAD

**Issue by OmarAllouzi95** [sismics/docs#217]
hello 
thank you for This professional work but i have a problem in deploy war file with tom cat 8 

when i upload the war file and press deploy button the browser give me 
This site can’t be reached
The connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_RESET

this is my UrL
http://localhost:8085/manager/html/upload?org.apache.catalina.filters.CSRF_NONCE=95AE85A9F3730D1E1FBF8EFEC902EA2D

and dont look to the port number because i change it 

by the way i deploy another war file on tom cat 8 and it success 
but with your war file i have this problem so what i have to do ??

**Comment by jendib** [comment]
Do you have some logs? It's hard to say like this

**Comment by OmarAllouzi95** [comment]
mmm thanks for your quick reply i solved this problem but i want to ask you 

how can i Add Arabic Language ??

**Comment by jendib** [comment]
To add a language, you have to translate this file: https://github.com/sismics/docs/blob/master/docs-web/src/main/webapp/src/locale/en.json
However the interface is not designed for right to left language like arabic, it may be an issue 🙄

**Comment by OmarAllouzi95** [comment]
mm thank you very much 
after i translated where i suppose to but the Arabic file ??

**Comment by jendib** [comment]
you can do a pull request if you know how to do it or send it to me: b.gamard@sismics.com

**Comment by OmarAllouzi95** [comment]
OK boss i will translate it and send it to you 
but what we have to do with the interface ???

**Comment by jendib** [comment]
It will be displayed left to right like English, I don't know if it's acceptable for Arabic readers.

**Comment by OmarAllouzi95** [comment]
aha its ok 

i will send you the translated file soon 

the last question 
how i can change the default admin user and password ?? 
(admin,admin) ??

**Comment by jendib** [comment]
When you are connected as admin, go to Settings > User account

**Comment by OmarAllouzi95** [comment]
OK Done 
thank you very much 
i will contact you soon on email to send the file 
thanks thanks ^_^

**Comment by OmarAllouzi95** [comment]
Can i ask you smth  

the files iam uploading it in tomcat 

Where i can found it ?? 

were the place that the file upload on ??

**Comment by jendib** [comment]
On Windows its: C:\Users\<You>\AppData\Roaming\Sismics\Docs

**Comment by OmarAllouzi95** [comment]
Many Thanks

**Comment by OmarAllouzi95** [comment]
soryy i know i ask so much 

the last one hhh 

what is the max size that i can upload to it ?? 

10 GB Or can be more ??

**Comment by jendib** [comment]
I never tried with 10GB files, but it shouldn't be an issue. However it will take time to encrypt the file. It's a document management system, not really designed to store massive multi-GB files ;)
