### ISSUE TITLE
How to Backup

### ISSUE THREAD

**Issue by schemen** [sismics/docs#225]
I wonder on how to backup/bulkexport the documents. Any chance to maybe allow to have the files unencrypted as in my (selfhosted) case the datastore is trusted.

Is there a way?

**Comment by jendib** [comment]
To do a full backup, save the directory where the app files are (location OS dependant), but then the files are encrypted yes.

To do an export, you will need to make a script using the API (documentation here: https://demo.sismicsdocs.com/apidoc/)

**Comment by gkoerk** [comment]
How does this feature work? I can't seem to figure out how to monitor a local directory.
