### ISSUE TITLE
Upload lager files not possible

### ISSUE THREAD

**Issue by 14r5** [sismics/docs#228]
Hi,
it's not possible to upload lager files (lager than 1MB). I get the following error:

`docs.min.js?1522949435442:7 PUT https://<HOST>/api/file 413 (Request Entity Too Large)`

Maybe the upload file size has to be set. http://www.eclipse.org/jetty/documentation/current/setting-form-size.html

Cheers,
Lars

**Comment by 14r5** [comment]
I used the docker image sismics/docs:latest and did a refresh today.

**Comment by 14r5** [comment]
Hi @jendib ,
I'm sorry it was my false. An involved nginx proxy had an upload limit of 1MB (thats the nginx default value). 
Thank you!

**Comment by jendib** [comment]
Ok great. I was doing some tests and was confused because I have no limit ;)
