### ISSUE TITLE
Scanner recommendations

### ISSUE THREAD

**Issue by stefnats** [sismics/docs#233]
Hi,

awesome project! Can you recommend scanners for integration with sismics docs?
For me, such a scanner should have

- ADF (automatic feeding)
- duplex
- scan to an FTP / Cloud / Mailbox
- scan without pc

**Comment by jendib** [comment]
I'm personally using the HP Officejet 6950 (ADF, printer/scanner, scan to PC/sdcard) and it's working quite nicely.
Other than that I don't have any more experience in this kind of product :)
