### ISSUE TITLE
Automatically fill the `Title` of a document when creating from the Quick upload

### ISSUE THREAD

**Issue by kevynb** [sismics/docs#238]
I think it would be nice to auto-fill the `title` field of the new document form with the title of the first uploaded file when coming from the Quick upload view.

If my files are already named properly, this cuts down the time I need to create a new document.

This could also be done when the user clicks on the `Add a document` button and selects a file to upload before typing the title (but maybe people don't do that 🤔 )

**Comment by jendib** [comment]
What if the user selects more than one file?
