### ISSUE TITLE
Users and groups list visibility

### ISSUE THREAD

**Issue by Sup3rlativ3** [sismics/docs#239]
Hi,

I was wondering if there is currently a way to limit what a user can see. For example, I don't want **User1** in **GroupA** to see that **User2** in **GroupB** is there. As far as I can see if **UserA** goes to the _Users & Groups_ page they can see all users and groups in the system. The use case I am evaluating for would mean this is a deal breaker.

![image](https://user-images.githubusercontent.com/1555043/42550792-20cb4eda-8517-11e8-856f-b45cb4915542.png)

Users are also able to assign any workflow they like. It would be fantastic if there were a way to restrict workflows to specific groups/users for assignment.

![image](https://user-images.githubusercontent.com/1555043/42550860-749be704-8517-11e8-8320-62f2901eeb8d.png)

Is there currently a way to do these things? If not, can they be implemented?

Kind Regards,
James

**Comment by jendib** [comment]
Hello, sorry for the late answer.
Indeed all users can list all users and groups, there is no access rights on this.
Same for the workflow list.

This feature could be added of course :)

**Comment by jendib** [comment]
I am considering developping this feature soon.
The idea I had to keep it simple would be to add a checkbox in the user profile saying "Restrict access to own groups".
This way, if UserA is in GroupA, he will only be able to see users and sub-groups from GroupA.

For workflows, we could also assign access groups to them. For example if WorkflowA is assigned to GroupA, then users in GroupB with the checkbox enabled couldn't see it.

What do you think?

**Comment by jendib** [comment]
Workflow permissions done in #252
