### ISSUE TITLE
Search typeahead and preview

### ISSUE THREAD

**Issue by jkathir** [sismics/docs#241]
type-ahead search,
number of hits
auto-complete suggestion
preview and easy navigation through the results

**Comment by jendib** [comment]
Thanks for the suggestions. As always we accept the pull requests 👍

**Comment by jendib** [comment]
Hello again,
I am considering developping those features.
Could you be more specific about:
- type-ahead search: we could type-ahead on all the words contained in doc title and description?
- number of hits: actually this is already done  (see bottom right corner of results list)
- auto-complete suggestion: is it the same as type-ahead?
- preview and easy navigation through the results: do you have suggestions to improve the current search results?

**Comment by jkathir** [comment]
1. type-ahead search - not just title and description but find a word or sentence in entire document - full text search. example, http://www.prabhupada.com/Vedabase/images/VB-programscr4.jpg

2. number of hits - number of hits found in entire document for the given word or sentence. refer the same example in the above.

3. it is not type-ahead but giving suggestions even before completing the word like in google suggestion....

4. preview and easy navigation. refer: https://img.informer.com/screenshots/568/568140_1_4.png

**Comment by jendib** [comment]
Thanks for clarifying, I'll see what I can do.

**Comment by jkathir** [comment]
one for example for you to explore - http://table.branham.org/#/en/main  ex: type - holy ghost - you will see 8847 hits and on go all the words in 1120 messages with results very quickly in less than a second.

**Comment by jendib** [comment]
I finished the typeahead feature (base on document title).
The terms highlight should also be doable easily. For the rest it's probably out of scope of Lucene.

**Comment by jendib** [comment]
Highlights:
![image](https://user-images.githubusercontent.com/2623413/47259636-604e2e80-d4ac-11e8-8548-acf787839656.png)
