### ISSUE TITLE
LDAP configuration is not available for admin

### ISSUE THREAD

**Issue by tedstriker** [sismics/docs#242]
For unknown reason the LDAP configuration isn't available to the admin user anymore.
I'm running the docker container.

Is there a way to restore the LDAP configuration page or access the settings from somewhere else?

These are the navigation entries I can see as administrator:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/795203/45925006-46511880-bf0d-11e8-8fa1-6d8c6070bfd1.png">

**Comment by jendib** [comment]
The docker container runs the CE (community edition) version, which never had the LDAP features.
This feature is part of the EE (enterprise edition) version available on https://www.sismicsdocs.com
