### ISSUE TITLE
Cant start docker image from example after server restart

### ISSUE THREAD

**Issue by petrk94** [sismics/docs#248]
Hello,
Im facing the issue, that I cant get it back running after a server shutdown.
The server has restarted, but the fresh docker install doesnt started up. 
After looking where the image is, I found it still in docker.

But now I dont get it back to the client:
With `docker inspect sismics_docs_latest`
I get this 

```
"Ports": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
```

and some more information.
I have set  "DOCS_BASE_URL= XXXXXXXXXx" with my Host IP I got from my hoster. After its starting, I tried to open it in my browser window, but only get the default index.html from apache "It works!" displayed. How I can get it back working?
When entering the example code `docker run --rm --name sismics_docs_latest -d -e DOCS_BASE_URL='http://[your-docker-host-ip]:8100' -p 8100:8080 -v sismics_docs_latest:/data sismics/docs:latest
`
Im not getting it back running, only get an ID number: d2d5a0131dbf5118b0c635d8638552a4d6b9c24fd5f0577377a404936939884c

With `docker logs sismics_docs_latest` I get this log:

```
2018-10-22 00:09:05.248:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@4dfa3a9d{/,file:///tmp/jetty-0.0.0.0-8080-docs.war-_-any-2083212522786420006.dir/webapp/,AVAILABLE}{/docs.war}
2018-10-22 00:09:05.272:INFO:oejs.AbstractConnector:main: Started ServerConnector@26ee56fa{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2018-10-22 00:09:05.273:INFO:oejs.Server:main: Started @11508ms
```

Any idea?
Thanks

**Comment by jendib** [comment]
Are you sure you didn't start the container twice?
What is the result of `docker ps`? And the full result of `docker inspect sismics_docs_latest`?

**Comment by petrk94** [comment]
@jendib 
I got it finally back running. It was my fault in docker.  But I would like to know an explanation of the example code mean `docker run --rm --name sismics_docs_latest -d -e DOCS_BASE_URL='http://[your-docker-host-ip]:8100' -p 8100:8080 -v sismics_docs_latest:/data sismics/docs:latest`

Additional, how to access the web application without entering the port number at the end of the domain. For now I have xxx.de:8100, what is not looking nice.
Thanks

**Comment by jendib** [comment]
All the `docker run` options are described here: https://docs.docker.com/engine/reference/run/
In the command line you can put 80 instead of 8100 to have a nicer address, however it will consume the port 80 on your Docker host.
The best way is to use a reverse proxy container and a SSL certificate for more security (see https://traefik.io/ for an example, but there is many others).

**Comment by petrk94** [comment]
@jendib 
alright, thanks. This with the SSL certificate im facing right now as issue. I have installed letsencrypt (apache2) and the domain is getting loaded over HTTPS successfully, but when Im adding the port number on the end, I get SSL error. Even after killing and restarting in docker with https:// as DOCS_BASE_URL, it didnt helped.

With this
`root@sismicsdms:~# docker run --rm --name sismics_docs_latest -d -e DOCS_BASE_URL='https://archive.vertical-farming.net' -p 80:8080 -v sismics_docs_latest:/data sismics/docs:latest`

I get this error message:
```
ef9761ef1723e9a717aa01b45e4471a580fa595b2cdf8c7cf4fbbe44d9abd8b2
docker: Error response from daemon: driver failed programming external connectivity on endpoint sismics_docs_latest (6563e733730174b4f7ba630e4706666418b7f98a9925dafd68cc934f8fbd3378): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.

```

**Comment by jendib** [comment]
Sorry it's out of scope of Sismics Docs, it's a pure Docker issue. You should ask for help on stackoverflow for example.

**Comment by petrk94** [comment]
Thanks for the help
