### ISSUE TITLE
backup for docker image

### ISSUE THREAD

**Issue by martinscheu** [sismics/docs#249]
Hello Benjamin

What would be the recommended backup procedure when using the docker docs image?

Thank you.
Martin

**Comment by jendib** [comment]
if you used the command line from the README.md with a named volume: `-v sismics_docs_latest:/data`, you just need to backup this volume. Everything is in there.

**Comment by martinscheu** [comment]
will try that, thanks.

**Comment by martinscheu** [comment]
I thought under "data" I will find only the uploaded files.
So I was wondering where to find the DB, etc.

But looking on what you find under /data made it clear:

/db
/log
/lucene
/storage
/theme

Thanks again for the support.
