### ISSUE TITLE
how to improve ocr

### ISSUE THREAD

**Issue by martinscheu** [sismics/docs#250]
Hello Benjamin

Is there any possibility to improve the OCR? 
Or what is recommended input, like pdf or tif and 300 dpi or more?

Thank you.
Martin

**Comment by jendib** [comment]
We have very good results (almost 100% recognition) with 300dpi JPEG out of the scanner.
Anything below 300dpi gives bad results from experience.
Internally, Docs rotate the document to make it straight and convert it to TIFF before sending it to Tesseract.

**Comment by martinscheu** [comment]
Thank you.

**Comment by martinscheu** [comment]
Hello, I reopen the issue as the OCR struggles with German signs ö,ä,ü, e.g. "Bitte wÃ¤hlen Sie Ihre Lieferad
o Bitte wÃ¤hlen Sie eine gÃ¼ltige Lieferadresse aus," even though I did set the language in the primary metadata to German. I tried with 300 dpi JPEG / PDF and 600 dpi JPEG/ PDF, same result. Thank you.

**Comment by jendib** [comment]
There is not much we can do about it, it's all in Tesseract handles afterwards.
Which Tesseract version are you using? The new version 4 using neural net seems way better (but still in development).

**Comment by martinscheu** [comment]
I am using the docker version, that would be Tesseract 4.0, right? And how is the language passed to Tesseract? I guess in the docker version I have no influence on it. Thank you.

**Comment by jendib** [comment]
Tesseract 4.00-beta.1 in the Docker image, it's the Ubuntu package. They released a final 4.0 version 23 days ago, but the Ubuntu package is not updated yet.
The language passed is the one of the document, as you did.
