### ISSUE TITLE
Thumbnail document view

### ISSUE THREAD

**Issue by fivestones** [sismics/docs#254]
It would be great if there was an option to change the view listing all the documents so that it includes previews/thumbnails there. The same thumbnails that are shown on the right when you click on a document name could be shown directly under the document name. This would visually make it much easier to spot things, especially documents that consist more of images than text and so can't be easily searched for.

**Comment by fivestones** [comment]
Alternatively, or in addition, something great would be a page that simply shows a grid view of thumbnails of all the files from all the documents. This would be similar to what is seen when viewing a document with a large number of files, except that it includes all files from all documents.

**Comment by jendib** [comment]
Great idea!

**Comment by jendib** [comment]
I think I'm going to make a "grid view" for the document list.
When activated, it will display the documents in grid form, using the first file of each document as thumbnail.
What do you think?
