### ISSUE TITLE
Versioning of files

### ISSUE THREAD

**Issue by Franklin89** [sismics/docs#256]
It would be nice if I could version a file. For example I upload a new file and then it is in Version 0.1. If I download that file, edit it and then upload it again, instead of creating a second document change the Version to 0.2.

Thinking a bit further: It would also be possible to show the diff of the document or roll back to another version.

Is that something you would consider implementing?

**Comment by jendib** [comment]
Yes definitely.
The only difficulty I see is how to know that an uploaded file in a new version or a whole new file to add.

**Comment by Franklin89** [comment]
Fair question.
**Thinking out loud:** You could check the filename and in case of a match show a dialog where you let the user choose what to do.

**Comment by jendib** [comment]
Or a new option in this menu "Upload a new version":
![image](https://user-images.githubusercontent.com/2623413/48200456-7f2f3a80-e35f-11e8-90fe-ef6917f9d500.png)

**Comment by Franklin89** [comment]
That would be a clean solution. How would you handle it if the user would change the file type/extension or the file name?

Let's say the original document was a pdf and now they upload a txt file?

**Comment by jendib** [comment]
It doesn't really matter for the system, and I don't think it's a good idea to block it.
At worst the file comparison would not work if the file type changes, but the user should have the choice.

**Comment by Franklin89** [comment]
Sounds like a feature I would be looking forward too :-)

**Comment by srigurubyo** [comment]
> Or a new option in this menu "Upload a new version":
> ![image](https://user-images.githubusercontent.com/2623413/48200456-7f2f3a80-e35f-11e8-90fe-ef6917f9d500.png)

This sounds to be a option.  User should use this feature in discrete manner to avoid any versioning issues.  I guess Alfresco also handles versioning in this mode, if I am not wrong.

**Comment by srigurubyo** [comment]
I see the code has been checked in, so if I rebuild it from ground versioning APIs will work?
