### ISSUE TITLE
Force delete the index and re-index all if the Lucene directory is unusable

### ISSUE THREAD

**Issue by martinscheu** [sismics/docs#260]
Hello
I upgraded to the latest docker image and running into "Error creating the directory reader" and "Error in running index writing"
Same result when trying "Start full reindexing"
Any other way to rebuild the index?
Thanks.

**Comment by jendib** [comment]
Yes you have to stop the server, delete the content of the `/data/lucene` directory and restart the server. After that you can do a full reindexing.
I should make this automated, keeping this issue as reminder.

**Comment by martinscheu** [comment]
manual procedure worked fine, thanks.
