### ISSUE TITLE
FUSE filesystem for accessing uploaded files

### ISSUE THREAD

**Issue by AnalogJ** [sismics/docs#264]
It would be nice to access the Sismics managed files via a filesystem, for sharing via Sambda/FTP/etc.

A general purpose solution would be to have a FUSE adapter that queries the API and allows files to be accessed transparently.

**Comment by jendib** [comment]
The only problem is that Sismics Docs documents and files are not in hierarchical structure, which would make it hard to transpose to a filesystem.
Maybe a read-only system could be designed.

**Comment by jendib** [comment]
After reading about FUSE, it seems the drive cannot be remote right?
You have to install the Docs server on the same machine you want to mount your drive.
It seems a bit counterintuitive for a server-based app.

**Comment by niicoooo** [comment]
Done: https://github.com/niicoooo/docs-fuse

Read-only, files and documents prefixed by their id.

**Comment by jendib** [comment]
That's great!
I reopen this to put a link to your project in the `README.md`

**Comment by AnalogJ** [comment]
This is great @niicoooo 
I just recently started looking into it as well: https://github.com/mediadepot/fuse-teedy

One of the features I was really interested in was creating a pseudo file system based on tags/categories

Would you be interested in adding that as a feature/open to pull requests?

**Comment by niicoooo** [comment]
It is almost done!
