### ISSUE TITLE
Please add OCR support for Dutch (Nederlands)

### ISSUE THREAD

**Issue by Freekers** [sismics/docs#265]
Awesome project! Would it be possible to add support for Dutch (Nederlands) ?
Tesseract has a Dutch package available. It's called `tesseract-ocr-nld`

Many thanks!

**Comment by jendib** [comment]
I can just add this package, but it's only about the OCR. If you want to
translate the interface it's another story.

**Comment by Freekers** [comment]
Sorry, I've should've been more specific; only the OCR is fine, that's all I need. Thank you!
