### ISSUE TITLE
Question about SQLCipher

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#273]
Hey,
is it possible to retrieve the SQLCipher which is used to encrypt the SQLite *.db file in /var/docs/db/ ? I tried to get into the db to make some external checks with SQLiteBrowser. Is this cipher some static value or does it change dynamically? I have no idea about this technology in detail yet.

![grafik](https://user-images.githubusercontent.com/5631071/50619322-dc2b1500-0ef8-11e9-8f7f-a4517c9166e3.png)

regards and thanks for info, Mario

**Comment by jendib** [comment]
The database is not SQLite, it's H2 database.

**Comment by vmario89** [comment]
Hi, thanks for the info. The thing i wanted to do could be solved by me with the great API functionality. I just built some bash script to get some documents out of it dynamically :-)

kind regards, Mario

**Comment by jendib** [comment]
It's indeed to best way to do (using the API).
