### ISSUE TITLE
Roadmap 2019?

### ISSUE THREAD

**Issue by petrk94** [sismics/docs#274]
Hello,
I would like to know, what are the plans for a roadmap in 2019?

Thanks

**Comment by jendib** [comment]
- Fix the issues marked as "bug" first
- Prioritize a few "enhancement" issues and implement them

Some are way more important than other (versioning should be in the top 3), but I don't really have an idea of which one should be done first except my own judgment. It should be a good idea to discuss it here.

**Comment by petrk94** [comment]
Ah I see, well bug fixing is never bad ;)
