### ISSUE TITLE
Add list view presentation for files of a document

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#277]
Hi,

at the moment when viewing files of a document there's a grid view. It would be great to have some button to switch over to list mode to show file names only. I have some document consisting of 80 files with some generic file name pattern. For this list view would fit better.

![grafik](https://user-images.githubusercontent.com/5631071/50867904-6cf86980-13ad-11e9-9475-ae87e7ceb805.png)

regards, Mario

**Comment by jendib** [comment]
Great idea.
