### ISSUE TITLE
Search field does not work

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#281]
Hi,
i recognized that when building android app from master branch and running with Sismics 1.6 the search function does not work in Android app. The result list just does not change - nothing happens.
any idea?

regards, Mario

**Comment by jendib** [comment]
You have to confirm your search with the "enter" button (bottom right on the virtual keyboard for me).

**Comment by vmario89** [comment]
Hi,
i know this. and i tried. But it does not work. I am using standard keyboard of Android 9 (Huawei Honor 10, EMUI 9.0.0). Other applications work without problems. Is there any possibility to have some debug output on the phone to see if there is some listener/trigger problem?

![grafik](https://user-images.githubusercontent.com/5631071/50973371-08422980-14e9-11e9-99e9-b04f4bde5a45.png)

**Comment by jendib** [comment]
When the search starts, the loading spinner should appear, so if you have nothing it's just not starting.
Maybe an issue with the Swift keyboard (I'm using the Google keyboard) but it would be surprising.

You can try starting the app in debug mode in Android Studio and put a breakpoint here https://github.com/sismics/docs/blob/master/docs-android/app/src/main/java/com/sismics/docs/activity/MainActivity.java#L257

When you start the search it should stop there.

**Comment by vmario89** [comment]
When debugging the app via Android Studio 3.3 the search works correctly. 

But it returned some error belonging to the style:

D/HwAppInnerBoostImpl: asyncReportData com.sismics.docs,2,2,1,5 interval=196
E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
D/Editor: sendUpdateSelection: Spannable name is SpannableStringBuilder, text length:0
    sendUpdateSelection: selectionStart=0, selectionEnd=0, candStart=-1, candEnd-1

**Comment by jendib** [comment]
I don't think it's related. I don't have a device to reproduce your error (on mine it's good), so I won't be able to fix your issue. Feel free to work on it and keep me updated.
