### ISSUE TITLE
Wild-card search not working

### ISSUE THREAD

**Issue by Freekers** [sismics/docs#284]
Suppose I've uploaded a document that contains the word 'administrator' somewhere in the text.
If I do a full text search using the search term 'administrator', it finds/retrieves the document fine.
However, if I perform a full text search using the search term 'admin', the document is not returned, nor when using 'admin*' or '*admin*'.

Are wild-cards not supported yet or not implemented yet in (full text) search?

Thank you!

**Comment by jendib** [comment]
It's not implemented.
