### ISSUE TITLE
Search suggestions are only based on document titles

### ISSUE THREAD

**Issue by Freekers** [sismics/docs#285]
Currently, search suggestions are only based on document titles. However, 99% of my document have no  title because these documents are scans, sent from my scanner and automatically imported Sismics Docs using the IMAP functionality. Hence my search suggestions are always empty, since the title of every document is the same; SCAN (DUPLEX).

Is it possible to also use words found in the document using full text indexing as search suggestions?

Thank you!

**Comment by jendib** [comment]
It's possible, however the user should be able to differenciate between title suggestion and fulltext suggestion, because the search would be different (with the full: prefix).
