### ISSUE TITLE
Feature Request: Version Control + Whole History Saved

### ISSUE THREAD

**Issue by jtelleria** [sismics/docs#288]
Could a Feature be implemented in "Sismics Docs" that, whenever a document is imported with the same file name multiple times 

E.g: DocA.pdf Uploaded Once; DocA.pdf Uploaded Twice.

Only the second document remains visible in the main screen; but there is a button that, If I click on it, I could see the whole history of documents (First and Second), plus an import timestamp? Google drive, for instance, already supports this feature.

Thank you!

Best,
Juan

**Comment by jendib** [comment]
It's actually already handled by #256 and I started working on it.
I'm closing your issue as duplicate, you can follow #256 to be updated about this feature.
