### ISSUE TITLE
Wild-card search

### ISSUE THREAD

**Issue by Freekers** [sismics/docs#289]
Suppose I've uploaded a document that contains the word 'administrator' somewhere in the text.
If I do a full text search using the search term 'administrator', it finds/retrieves the document fine.
However, if I perform a full text search using the search term 'admin', the document is not returned, nor when using 'admin*' or 'admin'.

Hence my feature request: Please implement wild-card search.

Thank you.

**Comment by manlife007** [comment]
I hope they fix the search quickly If I write 2 letters of the word it doesn't find it I must write the full word 

Pleas Help 

Thank you

**Comment by jendib** [comment]
Search queries now supports wildcard search at the end of search terms (like admin*).
