### ISSUE TITLE
Error when processing PDF file

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#290]
Hey, i got an error processing a pdf file with 85 pages. It might have to do with the format it was made. I tried to "misuse" Sismics for its quick file upload to process a file with OCR. The file i tried: https://bit.ly/2S9GLXW is some patent^^

> 28 Jan 2019 03:48:38,672 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:75) File updated event: FilUpdatedAsyncEvent{file=File{id=4ec9f213-9db0-47ce-9b35-bea20595ef2e, name=WO2017193026A1.pdf}, language=deu}
> Exception in thread "pool-1-thread-6" java.lang.NoClassDefFoundError: Could not initialize class com.levigo.jbig2.JBIG2ImageReader
>         at com.levigo.jbig2.JBIG2ImageReaderSpi.createReaderInstance(JBIG2ImageReaderSpi.java:118)
>         at java.desktop/javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
>         at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:532)
>         at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:516)
>         at org.apache.pdfbox.filter.Filter.findImageReader(Filter.java:155)
>         at org.apache.pdfbox.filter.JBIG2Filter.decode(JBIG2Filter.java:67)
>         at org.apache.pdfbox.cos.COSInputStream.create(COSInputStream.java:77)
>         at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:175)
>         at org.apache.pdfbox.pdmodel.common.PDStream.createInputStream(PDStream.java:241)
>         at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.createInputStream(PDImageXObject.java:729)
>         at org.apache.pdfbox.pdmodel.graphics.image.SampledImageReader.from1Bit(SampledImageReader.java:286)
>         at org.apache.pdfbox.pdmodel.graphics.image.SampledImageReader.getRGBImage(SampledImageReader.java:210)
>         at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:443)
>         at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:424)
>         at org.apache.pdfbox.rendering.PageDrawer.drawImage(PageDrawer.java:1034)
>         at org.apache.pdfbox.contentstream.operator.graphics.DrawObject.process(DrawObject.java:62)
>         at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:848)
>         at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:503)
>         at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:477)
>         at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:150)
>         at org.apache.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:254)
>         at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:245)
>         at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:153)
>         at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:140)
>         at com.sismics.docs.core.util.format.PdfFormatHandler.generateThumbnail(PdfFormatHandler.java:40)
>         at com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:116)
>         at com.sismics.docs.core.listener.async.FileProcessingAsyncListener.lambda$on$1(FileProcessingAsyncListener.java:80)
>         at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:47)
>         at com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:78)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
>         at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
>         at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>         at java.base/java.lang.Thread.run(Thread.java:844)
> 

i checked the compiled .war archive. The library levigo-jbig2-imageio-1.6.5.jar is in place in WEB-INF/lib/

After reprinting the PDF with Adobe PDF Printer i uploaded it again. Then OCR started accordingly.

any idea?

regards, Mario

**Comment by jendib** [comment]
I tried to import this PDF in a document but I had no issue.
I'm using Java 8/Windows 10 and also tried with Java 8/Docker.
What is your environment?

**Comment by vmario89** [comment]
Hi, i am running Sismics on bare metal Ubuntu 18.04 LTS + Java 11

**Comment by vmario89** [comment]
I tried it on another server running Ubuntu 16 and Java 11, there i am not able to upload
![grafik](https://user-images.githubusercontent.com/5631071/51985718-d6483580-249e-11e9-9cfc-f7541263cf14.png)

I checked the server logs but there is really no single log lines which tells anything about what went wrong

**Comment by jendib** [comment]
I just tested with OpenJDK 11 and it's working.
Which application server are you using? Tomcat or Jetty?

**Comment by vmario89** [comment]
Hey, i am using Jetty9 in latest version and using OpenJDK 11 too

**Comment by jendib** [comment]
That's quite weird. Do you reproduce with a full empty Docs (a new database)? Is there any error on boot except this one?

**Comment by vmario89** [comment]
Hi, no my docs instance contains some documents already and they work properly. The full log when restarting jetty9 is:

> 2019-02-01 11:29:21.446:INFO:oejs.Server:main: jetty-9.2.14.v20151106
> 2019-02-01 11:29:21.475:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:/var/lib/jetty9/webapps/] at interval 1
> 2019-02-01 11:29:21.722:INFO:root:main: Warning: No org.apache.tomcat.JarScanner set in ServletContext. Falling back to default JarScanner implementation.
> 2019-02-01 11:29:21.853:INFO:oajs.TldScanner:main: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
> 2019-02-01 11:29:21.906:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@2a17b7b6{/,file:/var/lib/jetty9/webapps/root/,AVAILABLE}{/root}
> 2019-02-01 11:29:23.800:INFO:dms:main: Warning: No org.apache.tomcat.JarScanner set in ServletContext. Falling back to default JarScanner implementation.
> 2019-02-01 11:29:23.963:INFO:oajs.TldScanner:main: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
> 01 Feb 2019 11:29:24,203 INFO com.sismics.util.filter.RequestContextFilter.init(RequestContextFilter.java:42) Using base data directory: /var/docs
> 01 Feb 2019 11:29:24,244 INFO com.sismics.util.jpa.EMF.getEntityManagerProperties(EMF.java:84) Configuring EntityManager from environment parameters
> 01 Feb 2019 11:29:25,163 INFO com.sismics.util.jpa.DbOpenHelper.open(DbOpenHelper.java:57) Opening database and executing incremental updates
> 01 Feb 2019 11:29:25,169 INFO com.sismics.util.jpa.DbOpenHelper.open(DbOpenHelper.java:106) Found database version 22, new version is 22, executing database incremental update scripts
> 01 Feb 2019 11:29:25,170 INFO com.sismics.util.jpa.DbOpenHelper.open(DbOpenHelper.java:108) Database upgrade complete
> 01 Feb 2019 11:29:25,171 INFO com.sismics.util.jpa.EMF.getEntityManagerProperties(EMF.java:84) Configuring EntityManager from environment parameters
> 01 Feb 2019 11:29:27,848 INFO com.sismics.util.ClasspathScanner.findClasses(ClasspathScanner.java:48) Found 1 classes for IndexingHandler
> 01 Feb 2019 11:29:27,904 INFO com.sismics.docs.core.util.indexing.LuceneIndexingHandler.startUp(LuceneIndexingHandler.java:93) Using RAM Lucene storage
> 01 Feb 2019 11:29:28,030 INFO com.sismics.docs.core.service.FileService.startUp(FileService.java:39) File service starting up
> 01 Feb 2019 11:29:28,036 INFO com.sismics.docs.core.service.InboxService.startUp(InboxService.java:49) Inbox service starting up
> 01 Feb 2019 11:29:28,042 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:76) Synchronizing IMAP inbox...
> 01 Feb 2019 11:29:28,237 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:84) 0 messages found
> 2019-02-01 11:29:29.600:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@1460a8c0{/dms,file:/var/cache/jetty9/data/jetty-0.0.0.0-8080-dms.war-_dms-any-4183635819236460745.dir/webapp/,AVAILABLE}{/dms.war}
> 2019-02-01 11:29:29.618:INFO:oejs.ServerConnector:main: Started ServerConnector@26101efc{HTTP/1.1}{0.0.0.0:8080}
> 2019-02-01 11:29:29.625:INFO:oejs.Server:main: Started @9461ms

if i upload now the mentioned document in the system just nothing happens than the visual error and no log line. On the other instance upload is fine but processing to OCR fails with the log i posted previously.

**Comment by vmario89** [comment]
hi, seems somebody enable 2FA with demo account xD cannot login^^
![grafik](https://user-images.githubusercontent.com/5631071/52125889-2570a080-262e-11e9-8d42-d354dba1f915.png)

**Comment by jendib** [comment]
You can try again.

**Comment by vmario89** [comment]
hey. there uploading and OCR works quick and without problems. did it 14:35 o'clock

**Comment by vmario89** [comment]
Hi, issue can be closed. Seems that it works in current release. I tested it again
