### ISSUE TITLE
Remove "Give us feedback" for non-admin users

### ISSUE THREAD

**Issue by petrk94** [sismics/docs#291]
Hello,

please add option to the admin panel to remove the "Give us feedback" button on the right side of the application. 

Thanks

**Comment by jendib** [comment]
It's kind of defeating the purpose of a feedback isn't it? This form is here to collect user suggestions.

**Comment by petrk94** [comment]
@jendib yes, I agree, it has definitely its purpose. But the application get used by other people who dont know about it, because they are just user and this is irritating. Who is getting the feedback there? The admin? I dont talk to remove it in general, just that the admin can disable this for the user.

**Comment by jendib** [comment]
The feedback is going to a mail address I'm managing, and then I'm adding a Github issue if the suggestion is legit. However I agree normal users shouldn't see it, only the administrator users.
