### ISSUE TITLE
Add Read only function to Guest mode / group role

### ISSUE THREAD

**Issue by petrk94** [sismics/docs#292]
Hello,

Please add the functionality, to disable the upload function in guest mode or other specific group roles.
For the moment the workaround is to set the quota on 0MB, but this is not the good solution.

Thanks

**Comment by jendib** [comment]
Why not just set the ACL to "Read" and not give the Write access to the documents?

**Comment by petrk94** [comment]
No, I dont mean it specific for the documents, I mean to disable the visible upload functionality, like "Add a Document"-button and the quick upload area (See screenshot). 
Im looking for to hide this from specific roles, so in worst case someone try to upload something and wonder why its not working etc.
![sismics_docs_test](https://user-images.githubusercontent.com/19719052/52004697-0a841c00-24c8-11e9-8bb3-95c5948e220f.PNG)

**Comment by jendib** [comment]
I see. Maybe it could go even further and we could add/remove specific rights for a specific group/user.
However now there is just one "right" (called function) which is "admin", it's not as fine grained as you request...

**Comment by jendib** [comment]
I'm closing this issue for now, we don't intend to do it as part of the open source project.
You can always contact us for some custom developement needs.
