### ISSUE TITLE
Search function buggy

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#295]
Hi,
since latest release i think something with seach function is messed up. I noticed that the search field does not look up in the document's titles, but only in the description. It seems to fail only for already existing documents. But newly created documents are searchable with title.

If i open an existing document and fill in the same content into description, i can search for it with positive result. The tag: search works normally. Some screenshots to see what i mean:

![grafik](https://user-images.githubusercontent.com/5631071/52551364-72960480-2ddc-11e9-8634-29dc544af948.png)

![grafik](https://user-images.githubusercontent.com/5631071/52551383-8b9eb580-2ddc-11e9-9280-f5f1de4ebed0.png)

![grafik](https://user-images.githubusercontent.com/5631071/52551394-98230e00-2ddc-11e9-9601-438955c62c6b.png)

![grafik](https://user-images.githubusercontent.com/5631071/52551406-a2dda300-2ddc-11e9-8a9e-4568c4c29f3a.png)

Newly created doc search works:
![grafik](https://user-images.githubusercontent.com/5631071/52551652-b5a4a780-2ddd-11e9-8e5b-8c0c56b1b635.png)

I think some database sql statement has to be applied to fix it.

I checked the Sismics Demo https://demo.sismicsdocs.com. There it works normally.
In The Jetty9 logs i have no error. Any idea what could be the reason or how i could fix it?

By the way is it possible to get some precompiled .war archive on Github?

**Comment by vmario89** [comment]
okay i figured out that if i open non working documents in edit mode and just clicking save (without changes) then it will be displayed in search result list. I think i can handle this for my documents because i only have ~100 docs in sismics yet. but might be a problem for older instances with more content

**Comment by jendib** [comment]
Did you try a full reindexing from the admin menu?

**Comment by vmario89** [comment]
haha good hint. i did not recognize that function yet. It did the job! Sorry for bugging you.

regards, Mario

**Comment by jendib** [comment]
It's still kind of weird that it happened, it did not update Lucene (the indexing engine) or anything related to search...

**Comment by vmario89** [comment]
By the way is there some option to add multiple wildcards in search? I also tried to use wildcard at the beginning of a word but that does not work like exspected.

regards, Mario
