### ISSUE TITLE
Changing item order opens file for view automatically

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#296]
Hi,
i noticed that when dragging files in a document to change sort order, the dragged item will open automatically. I think this should not happen - because if you have to sort about 20 files you have to click 20x extra to close the popup view:

![grafik](https://user-images.githubusercontent.com/5631071/52552032-141e5580-2ddf-11e9-8811-77994cb7548c.png)

![grafik](https://user-images.githubusercontent.com/5631071/52552064-2ef0ca00-2ddf-11e9-9d02-c8bc0de5a41a.png)

**Comment by jendib** [comment]
Which browser are you using? I don't have this issue in Chrome 74 (Windows 10).

**Comment by vmario89** [comment]
Hi, it occures in FireFox on different machines

![grafik](https://user-images.githubusercontent.com/5631071/57101087-c7cd1c80-6d20-11e9-904e-b2d299d49c62.png)

indeed in Chrome it does *not* happen. 

regards, Mario
