### ISSUE TITLE
Add Download Button

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#301]
Hi,
just a small feature request: Add a Download Button directly to dropdown menu:
![grafik](https://user-images.githubusercontent.com/5631071/53610706-1862b500-3bcc-11e9-8521-db7a1361351a.png)

i have a lot of documents where i know they are the right files. So i dont want to view them to get to download button. i'd like to download it saving mouse clicks and web traffic :-) 

regards, Mario

**Comment by petrk94** [comment]
But you can download the whole document as pdf. Why download it separately? Than upload the files and create separate documents, doesnt make more sense or I do not understand the use case?

**Comment by vmario89** [comment]
Hi, simple use case: imagine you have a document representing a scanned book with 300 single pages and you only need one page containing a table of number values which i'd like to pin on my desk.  I dont want to download the whole pook - only that page. at the moment this is already possible opening the file and pressing the download button there:
![grafik](https://user-images.githubusercontent.com/5631071/53634366-538bd500-3c1a-11e9-88f6-9a900d6af88e.png)

my request is only about copying that copy button down to the dropdown before opening the file visually
