### ISSUE TITLE
Add a "notag" search criteria

### ISSUE THREAD

**Issue by niicoooo** [sismics/docs#305]
Hi ,

It can be useful:
- to be able to select tagless documents
- to be able to exclude documents with some tags

Regards,

**Comment by jendib** [comment]
The syntax is (for example):
```
!tag:accounting
```
We can exclude multiple tags, and merge included/excluded tags (excluded has priority).

**Comment by torak1981** [comment]
So with this syntax I can include and exclude tags. Is the search for documents without tags possible?
