### ISSUE TITLE
Renaming/deleting groups breaks workflow configuration

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#306]
Hey,
i noticed a bug when editing a workflow. Please do the following:

- open a workflow which contains the assigned group "administrators" (which is default)
- rename the group administrators to "Administratoren" (which is german equivalent)
- open workflow again to edit and change something, but not the group
- click save. there no error is shown BUT the workflow is not saved

the problem: the mask recognized that the group changed and checked that it does not exist, but it does not warn about. So user wonders why it did not change

**Comment by jendib** [comment]
Nice catch. An issue also happens when deleting a group referenced in a workflow.
The easy solution would be to disable group renaming and show a warning when deleting a group referenced by a workflow.
