### ISSUE TITLE
Deleting a file doesn't reset the user quota

### ISSUE THREAD

**Issue by aceonline666** [sismics/docs#308]
How to reproduce:
* Starting a teedy instance with docker and login with admin.
* Upload a large file (to see the difference, for example 100MB).
* You will see the quota increased "100MB (1%) used of 10,000 MB"
* Delete the file again
* The quota stays the same. I would have expected that the quota falls back to 0.

**Comment by jendib** [comment]
Thanks for reporting this. Indeed there were an issue when deleting a document containing files, to quota wasn't updated accordingly.
