### ISSUE TITLE
Allow to disable "first time usage"

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#309]
Hi,
always when i remove browser cache the popup shows again:
![grafik](https://user-images.githubusercontent.com/5631071/54749487-f958b100-4bd4-11e9-9f94-34fe43bd94a1.png)

it would be cool if the user could disable this popup in his configuration settings to avoid clicking yes all the time. It's enough when user recognizes this information once and for all.

regards and thanks, Mario :-)

**Comment by jendib** [comment]
Indeed it should be stored in user preference server-side.

**Comment by SmartPhoneLover** [comment]
Is that change already applied to the latest v1.6? Or for next docker releases?
Thanks.

**Comment by jendib** [comment]
The issue is opened, it means it's not done.
