### ISSUE TITLE
Index corrupted after restart

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#310]
Hi,
i recognized that when i restart my linux machine and access sismics again the search does not work correctly because it does not return results correctly. I always have to run re-indexing once after restart, to make search results working again. After that process everything is up and fine gain.

Is there some possibility to have some auto-reindexing in place? Or some clean shutdown-mechanism? 

I am running with jetty9 and jetty will start and stop automatically, loading .war archives automatically

kind regards, Mario

**Comment by jendib** [comment]
I personnally restarted some instances tens of times without search issue.
You need to terminate the Jetty process with a SIGTERM not a SIGKILL, otherwise it's not letting the database and index to close properly.
