### ISSUE TITLE
Remove administrators from the ACL target list

### ISSUE THREAD

**Issue by tedstriker** [sismics/docs#313]
Using docker to run teedy.
It's not possible to assign users or user groups to a tags ACL anymore.
User / user group is still selectable, but upon save, nothing get's written to the ACL.

If you need more information to reproduce the error let me know.

**Comment by jendib** [comment]
Do you have an error in the network console? (F12 on Chrome, Network tab).

**Comment by tedstriker** [comment]
After selecting the administrators group, selecting read+write permission and clicking "add", two PUT requests occur:
- request1
  - address: https://example.com/api/acl?perm=READ&source=d8f5aee4-b261-4ecd-9778-7b1754f0f33d&target=administrators&type=GROUP
  - respsonse: `{}`
- request2
  - address: https://example.com/api/acl?perm=WRITE&source=d8f5aee4-b261-4ecd-9778-7b1754f0f33d&target=administrators&type=GROUP
  - respsonse: `{}`

so error codes and no issues in the console.

**Comment by jendib** [comment]
Administrators can see all by default, so no need to add them.
The system should not even suggest it actually, it's confusing.

I leave this issue open to fix this.
