### ISSUE TITLE
Docker image fails on ARM (RPi)

### ISSUE THREAD

**Issue by popovanton0** [sismics/docs#315]
When I am trying to run docs docker image with command `sudo docker run --name teedy_latest -d -e DOCS_BASE_URL='http://192.168.0.101:8100' -p 8100:8080 -v teedy_latest:/data sismics/docs:latest` on Raspberry Pi 3B with Raspbian Stretch Full (version April 2019) container instantly stops with log message `standard_init_linux.go:207: exec user process caused "exec format error"`. People on [Stackoverflow](https://stackoverflow.com/a/52793714) suggest that this error is related with ARM architecture.

**Comment by jendib** [comment]
The image is only for x86.
Pull request welcome to support ARM.
