### ISSUE TITLE
Be able to choose tag colors in hexa code

### ISSUE THREAD

**Issue by SmartPhoneLover** [sismics/docs#317]
I think would be useful if we can choose the color of a tag by manually introducing the hexadecimal code directy too. Overall if we want to have, just for personal needs, same color on a specific amount of tags.
Or if adding such feature is not an option, a workaround would be to allow us to clone/copy tags. So, color (+ other info) will be kept.

![Captura](https://user-images.githubusercontent.com/42898749/57024804-ce329a00-6c35-11e9-828c-238cf8a077a8.JPG)

**Comment by junpet** [comment]
Currently updating in the db manually. 🔨

**Comment by jendib** [comment]
I added a small button to open the manual hex code field (hidden for non technical users).
![image](https://user-images.githubusercontent.com/2623413/74595610-eef0a280-5043-11ea-97b7-0f673ff273c8.png)

**Comment by petrk94** [comment]
@jendib thanks :) I really missed that feature. It was a mess to make many labels with trying to get somehow the correct color
