### ISSUE TITLE
add document/OCR language: Hebrew

### ISSUE THREAD

**Issue by vasilevich** [sismics/docs#319]
Dear teedy development team

please consider adding the hebrew language into your OCR detection system aswell as choosing document language in the list.

tessaract already has packages dealing with this language please add it.

thank you!

**Comment by jendib** [comment]
Hi,
If you can, could you provide a pull request similar to this one?
https://github.com/sismics/docs/pull/304/files
It should be pretty straightforward with the ISO 3 letters code for hebrew.

**Comment by vasilevich** [comment]
Hello, yes I have made a pull request here  :  https://github.com/sismics/docs/pull/320 according to your instructions.

thanks!

**Comment by jendib** [comment]
It's merged, thanks!
