### ISSUE TITLE
API issues, dont get full list of documents

### ISSUE THREAD

**Issue by petrk94** [sismics/docs#324]
Hello,

Im trying to work with the API with PHP, unfortunately, I need the full list of the documents inside the system (total: 200), but I get only displayed as response the first 99, even after set limit to 200, it doesnt changed. Can you help?

Greets

**Comment by jendib** [comment]
Yes the max page size is 100, so you will never get more than 100 documents per page.
For your case, I strongly suggest you to use the `offset` parameter (together with `limit` at 100) and loop over.

In the response you have a `total` field, so you know how many pages you have to query.

Please see: https://demo.teedy.io/apidoc/#api-Document-GetDocumentList

**Comment by petrk94** [comment]
@jendib what is limiting the page size?

**Comment by jendib** [comment]
It's just an arbitrary limit to prevent killing the database.
