### ISSUE TITLE
Delete users?

### ISSUE THREAD

**Issue by Toucan-Sam** [sismics/docs#325]
Is there somewhere I've missed that I can delete a user? Or if users can't be deleted (because their documents would also be lost) can I at least disable the user completely somehow?

In particular I'd prefer that it was clear that the default 'guest' user wouldn't have any access whatsoever. They may not be able to see documents, but that doesn't mean I want friends and family visiting to accidentally find my life insurance policy if I've mislabeled it. :)

**Comment by jendib** [comment]
As an admin user, Settings > Users. You can also disable the guest user in
Configuration
