### ISSUE TITLE
Document environment variables

### ISSUE THREAD

**Issue by Toucan-Sam** [sismics/docs#326]
Is there a list of all the environmental variables that I can use in a docker-compose file?

In particular I'm interested in how to do things like specify which PostgreSQL database and credentials to use.

I've just bought a new scanner and have a whole pile of things to catch up on. :)

**Comment by jendib** [comment]
It's not precisely documented unfortunately, except the `DOCS_BASE_URL`.
I keep your issue open as a task to improve on this.

**Comment by vmario89** [comment]
hi. looking for the same things. I'd like to migrate from H2 to PostgreSQL. There is no documentation on how to setup the postgresql with teedy. By API i could push the data from H2 to PostgreSQL hopefully

**Comment by vmario89** [comment]
I tried to setup Teedy with PostgreSQL but had no luck yet. I looked at hte EMF.java code which takes system properties. So i added them like docs.com

unfortunately it won't change the behaviour to use H2 instead.

```
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/dms</Set>
  <Set name="war"><SystemProperty name="jetty.data" default="."/>/webapps/dms.war</Set>
 
  <Call class="java.lang.System" name="setProperty">
    <Arg>docs.home</Arg>
    <Arg>/mnt/data/sismics/data/psql-test</Arg>
  </Call>
  <Call class="java.lang.System" name="setProperty">
        <Arg>DATABASE_URL</Arg>
        <Arg>postgresql://localhost:5432/teedy_db/Arg>
  </Call>
  <Call class="java.lang.System" name="setProperty">
        <Arg>DATABASE_USER</Arg>
        <Arg>teedy</Arg>
  </Call>
  <Call class="java.lang.System" name="setProperty">
        <Arg>DATABASE_PASSWORD</Arg>
        <Arg>password</Arg>
  </Call>
</Configure>
```

What a i doing wrong?

**Comment by jendib** [comment]
It's actually an environnement variable you need to use, not a Java system property.
Otherwise the values you used seem OK for PGSQL.

**Comment by vmario89** [comment]
Hi,

thanks. i modified the jetty9 parameters in service to the following
`Environment="JAVA_OPTS=-Djava.awt.headless=true -Xms1024m -Xmx3584m -Ddatabase_url=postgresql\://localhost\:5432/teedy_db -Ddatabase_user=teedy -Ddatabase_password=password"`
but they are ignored. If i type them wrong journalctl reports errors on parsing. So i know that the variables are respected themselves, but not used. How do you configure it?
i tried with uppercase/lowercase. This makes no difference. :-(

regards, Mario

**Comment by jendib** [comment]
I think you have some syntax issues, you put the variables in the JAVA_OPTS variables.
Also it's supposed to be in all capital letters.

**Comment by vmario89** [comment]
Hi @jendib,
thanks. Now i got it. Edited the /lib/systemd/system/jetty9.service file again

```
#
# Systemd unit file for Jetty
#
 
[Unit]
Description=Jetty 9 Web Application Server
Documentation=https://www.eclipse.org/jetty/documentation/current/
After=network.target
 
[Service]
 
# Configuration
Environment="JETTY_HOME=/usr/share/jetty9/"
Environment="JETTY_STATE=/var/lib/jetty9/jetty.state"
Environment="JAVA_OPTS=-Djava.awt.headless=true"
Environment="DATABASE_URL=jdbc:postgresql://127.0.0.1:5432/teedy_ldb"
Environment="DATABASE_USER=teedy"
Environment="DATABASE_PASSWORD=password"
```

Some side note to this:
I was fixated on how to do this configuration in a webapp-context all the time (if running 2 or more instances of Teedy on same machine). The global configuration configures whole jetty with same config for all instances i think. At the moment i am using one Teedy but was thinking about setting up a second Teedy later as a library for my books and manuals. I could use docker but i don't want to dockerize all the stuff. 

cheers ,Mario

**Comment by jendib** [comment]
You can run 2 Jetty server.
The overhead is quite minimal, and you keep the memory management separated in 2 processes.

**Comment by vmario89** [comment]
hey, indeed this should be possible by copy&paste to just make another *.service file which could be enabled by systemctl. Thanks for that simple but great idea :-)
