### ISSUE TITLE
I have uploaded an image but the hash of md5 sum does not match with my local image

### ISSUE THREAD

**Issue by kamlesh-grmtech** [sismics/docs#327]
![Screen Shot 2019-06-06 at 5 52 45 AM](https://user-images.githubusercontent.com/12132074/59034232-703e3700-881f-11e9-9c30-e4bffec46dbd.png)

**Comment by jendib** [comment]
Can you send me your image so I can reproduce the issue?

**Comment by kamlesh-grmtech** [comment]
You can check any jpg file I checked by uploading multiple images in it.

**Comment by jendib** [comment]
I understand. You are checking the MD5 sum of the file in the Teedy storage. However all files are stored encrypted, so it's normal you have a different file (and you cannot open it).
