### ISSUE TITLE
Code contribution for oauth

### ISSUE THREAD

**Issue by vikaskedia** [sismics/docs#329]
Very well written software. Congratulations!!

Would you be interested in code contribution to add oauth feature?

Or maybe you can set up a system where we can fund features.

thank you,

**Comment by jendib** [comment]
What do you have in mind for oauth? Like an external authentication?

You can contact me on my email address to discuss contribution and funding: b.gamard@sismics.com

**Comment by vikaskedia** [comment]
> What do you have in mind for oauth? 

We have an internal enterprise application.

Once the user logs into the enterprise application they do not need to login anymore in other applications like:

1. Rocketchat https://github.com/RocketChat/Rocket.Chat
2. Discourse https://github.com/discourse/discourse

This makes the chat and discussion forum feel very integrated with the internal enterprise application.

**Comment by jendib** [comment]
No news since last june. Closing.

**Comment by zerosnugget** [comment]
I would really love to see an OAuth2/OIDC implementation in Teedy. This would be the last bit for me to make it perfect. I hope someone else is going to look into it in the near future!
