### ISSUE TITLE
Edit tag font color

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#332]
Hi, working a lot with Teedy and having thousands of docs and hundreds of labels, i recognized some labels which are hard to read due to the color scheme. some example:
![grafik](https://user-images.githubusercontent.com/5631071/59885614-1bbcbf00-93bc-11e9-9981-debeb7ee085f.png)

so my simple FQ would be to allow setting the font color next to the background color. makes sense for brighter colors. 

kind regards, Mario :-)

**Comment by jendib** [comment]
The color is now automatically choosen between black and white for the maximum legibility:
![image](https://user-images.githubusercontent.com/2623413/74595830-d03fdb00-5046-11ea-8ec6-b1f454f38120.png)
