### ISSUE TITLE
Fix selection in document'S file list view

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#334]
Hi,

i got another really small fix request for the following: If i have a document with more files and when i am hovering over one file, the background of the item changes to grey. this is nice because i can see which one i select. But the problem: after clicking on that item so that it will display the grey selection color changes to white. So when closing the view i am not able to see the last selected file i was looking on. It would help to do it the way that the selected item leaves the color.
the behaviour i am exspecting is working nicely in the document list view on the left side. So i guess its a small CSS fix or something.

![grafik](https://user-images.githubusercontent.com/5631071/60042414-fc74a900-96bd-11e9-998e-272ce857079f.png)

regards, Mario

**Comment by jendib** [comment]
I see. On the left side there is actual code to do this. I could replicate it for files also.
