### ISSUE TITLE
Bug with tags

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#337]
Hi,
i figured out a bug that's prevents rearranging tags in the tree structure. Please do the following
1. Add some Tag like "house"
2. Add some other Tag like "door" and assign it to be a child of "house"
3. Add a new Tag like "village"
4. Now try to change "house" to be a child of "village". The tag "house" with its children "door" and "window" stays where it is. But it should now be a sub item of "village".

**Comment by jendib** [comment]
I cannot reproduce, maybe the bug was fixed since then:
![image](https://user-images.githubusercontent.com/2623413/74589954-58ec5600-500a-11ea-9c55-281a45d856f6.png)

**Comment by vmario89** [comment]
indeed i cannot reproduce it too now. thanks for having a check. regards, Mario
