### ISSUE TITLE
Negate the tag search

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#339]
Hi,

got another feature idea which would be very helpful to work with. I'd like to be able to find all documents which do NOT contain one or more defined tags. I know that implementing all the regex stuff is hard. Maybe there's some pattern out there which could be used for this

kind regards, Mario :)

**Comment by jendib** [comment]
Actually it's already available by adding a "!" in front. For example: `!tag:house` will return all documents without the tag "house".
