### ISSUE TITLE
Highlight specific files matching a fulltext search

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#343]
Hey,

sorry for all those issues. I am working so much with teedy that i have a big wish list of things which would be neat.

I wish i have had time to contribute with code instead of wishes only :-(

got a feature request to improve the full text search functionality. I have some documents in my DMS which contain over 50 similar files. Let's say 5 of those files in the doc contain my name "Mario". If i type "full:mario" into search i will find this document (and maybe others) and it will show results. But now i am not able to find out which 5 files of the document contain "mario". So it would be great to have a search box inside the document to get a list of files which contain the result only. Otherwise i need to check 50 files insteaf of 5.

kind regards, Mario

regards, Mario

**Comment by junpet** [comment]
Won't be implemented? :(
