### ISSUE TITLE
Option to disable OCR temporarily + mass processing

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#344]
Hi,

my machine is running with 3,5GB memory for JVM. I installed the tesseract libraries and teedy is going to process all the uploaded files fine. But when pushing ~500 files at once it is really slow. I'd like to be able to disable the OCR temporarily so the upload turns quicker. After uploading i'd like to be able to have a checkbox at each file in a document to select which files should be processed again. At the moment this can be done by clicking "..." and "reprocess". It would help to seperate the job of getting done the upload and the "detail work" per document.

Maybe there could be some option to (re)process only not yet processed files or files which don't have a thumbnail yet too.

kind regards, Mario

**Comment by jendib** [comment]
OCR is now multithreaded and I don't want users to have to fiddle with this kind of technical considerations.

**Comment by alexanderadam** [comment]
Is it still not possible to disable OCR nowadays?

**Comment by alexanderadam** [comment]
Just FYI: I created [a Pull Request](https://github.com/sismics/docs/pull/768) for that

**Comment by Enrice** [comment]
We disabled OCR, but uploaded documents are still OCR-processed. It seems the PR doesn't fully work.
