### ISSUE TITLE
Corrupted database, slow search

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#345]
Hi,

i think i did some overkill with the H2 embedded database. I put a mass of files into system. Seems that the database has some defects now. I added ~ 8000 files in ~ 100 documents. I removed them again. But now my values look stupid. It shows -538 MB (-2,2%) of 25.000 MB. The search function now reacts really slow when loading the whole document list on start page. 

Once loaded, the search functionality itself works quickly as usual.

I made a little video. It takes 5-10 seconds to show values. I did a reboot of Jetty and i also reindexed using the button in backend. Makes no difference. :-(

![Video_2019-07-24_135056](https://user-images.githubusercontent.com/5631071/61794890-79f91980-ae22-11e9-8c63-dafb956ea1ef.gif)

Now i am trying to get into the H2 database to check what could be the cause. I  guess it has to be sth. DB related. I downloaded H2 tool from http://www.h2database.com/h2-2019-03-13.zip and tried to connect to the embedded/in-memory database. I looked into hibernate.propieres and EMF.java

i tried to login but it won't show anything:
```
cd C:\Users\mario\Downloads\h2-2019-03-13\h2\bin
java -jar h2-1.4.199.jar -url jdbc:h2:mem:docs:~/Downloads/docs.mv.db -driver "org.h2.Driver" -user "sa" -password "";CACHE_SIZE=65536;LOCK_TIMEOUT=10000
```

same with DBVisualizer:
![grafik](https://user-images.githubusercontent.com/5631071/61795251-3e128400-ae23-11e9-9998-d74dfd48ed12.png)

in the /var/docs/log/docs.log file there is nothing special. Maybe i have to change to DEBUG output but how to do this? I screwed some things in /etc/jetty9 but with no difference.

Can you maybe help?

regards, Mario

**Comment by vmario89** [comment]
after dropping thousands of files the index reacts quick as usual again. But the quota is still wrong. id like to fix it in H2 database. And in general id like to migrate to PostgreSQL. i left some comments at https://github.com/sismics/docs/issues/326

**Comment by vmario89** [comment]
okay now i found out how to dive into H2. I just did not know that i need to ignore the extension of the database file "*.mv.db". So instead of opening "docs.mv.db" you need to enter simply "docs":

![grafik](https://user-images.githubusercontent.com/5631071/61989085-63251380-b02a-11e9-8b97-588bd9886aa4.png)

`java -jar h2-1.4.199.jar -url "jdbc:h2:file:~/Downloads/docs.mv.db;CACHE_SIZE=65536;LOCK_TIMEOUT=10000;IFEXISTS=TRUE;" -driver "org.h2.Driver" -user "sa" -password ""`

**Comment by vmario89** [comment]
After checking some code i think the problem with the negative quota (my case) occured due to some deletion exceptions which leads to missing totalSize calc executions. I think there's a need to recalculate the totalSize completely from scratch by some additional function. That might be done with pure java code to update the database value USE_STORAGECURRENT_N. Another idea would be to store the file size of each file in an additional column in database. With stored file sizes in db a recalculation could be done with SQL statement.

In my case i only have one user (me) so i can recalc the totalSize by getting the filesize from filesystem with unix commands.

**Comment by jendib** [comment]
Do you still have the deletion exception? It seems to be the root of the issue here. The quota should never go out of sync.

**Comment by vmario89** [comment]
Hi. No the exception did not occure again. I cannot reproduce it. Its still the fact that the quota can be modified by exception that way. Thats the reason i think the filesize should be stored in database to guarantee a correct quota calculation or some function to re-scan over files and owners to regenerate the correct values :-/

**Comment by jendib** [comment]
Yeah that's what I'm saying, even if there is an exception, the quota shouldn't be broken.
Actually an API to recompute the user quota existed some time ago but I removed it during a cleanup: https://github.com/sismics/docs/commit/d0335b6b161058250ec8cc44eeb2357f96176f54#diff-54e77110186f974f07aeb29c2673496fL690
