### ISSUE TITLE
Permissions on custom metadata

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#349]
Hi,

i have another sort of idea which came up to my mind a while ago. I think it would be a good deal to be able to define what users or groups are able to see certain fields of a document. So for example it would be nice to configure that a user "normal user" may not see some custom meta data, the description or comments for example.

**Comment by deliciouslytyped** [comment]
Teedy seems good but without more fine-grained permissions everywhere it's iffy for me to use in a multi-user environment.

**Comment by jendib** [comment]
Most big document management system (Nuxeo, Alfresco, ...) don't go as far as giving permissions on specific metadata. It's very often only document based.

**Comment by deliciouslytyped** [comment]
I would like to be able to limit groups to being able to upload/not see documents with certain tags/not, and similar. (more specifically I probably want everything to be hidden by default, except for administrators and the user that uploaded something).

**Comment by jendib** [comment]
All this is already possible with the current permission system. @deliciouslytyped

**Comment by jendib** [comment]
Duplicated by #349
