### ISSUE TITLE
Quick upload delete button deletes instantly

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#354]
Hi, the delete button in quick upload should spawn a confirmation popup when deleting file i recognized today. Otherwise its too easy to kill documents forever

![grafik](https://user-images.githubusercontent.com/5631071/64538153-647d7780-d31c-11e9-96d2-27bad4193379.png)

regards, Mario

**Comment by jendib** [comment]
The purpose of this Quick Upload is to add/remove temporary files quickly before putting them in permanent documents. A confirmation dialog would slow down this process significantly.
