### ISSUE TITLE
Removing default admin user

### ISSUE THREAD

**Issue by Andrioshe** [sismics/docs#355]
Is there a way existing to remove or disable the default admin user?

**Comment by jendib** [comment]
No you cannot. What is your use case for wanting to delete it?

**Comment by Andrioshe** [comment]
is there a possibility to change the name? Actually I dont feel good having a administrator account named "admin".

**Comment by jendib** [comment]
You cannot change the name of the default one, but you can create a new administrator user with another name. Just put it in the "administrators" group.
