### ISSUE TITLE
How to get all files related to a document via REST api

### ISSUE THREAD

**Issue by tonny1983** [sismics/docs#357]
According to the document of REST api, if I get a document with its id, I can only know the number of files in the document. On the other hand, there is no api of files to show the relationship between files and their document. Hence, how can I download all files in a document if only known the document id?

**Comment by petrk94** [comment]
same here, I would like to be able, to display the documented as a list in a php application, to reduce need of direct access to the DMS, if there is already an API.

**Comment by jendib** [comment]
You are looking for this endpoint: https://demo.teedy.io/apidoc/#api-File-GetFileList
You can pass an `id` parameter which is the document ID you are looking for.

**Comment by tonny1983** [comment]
@jendib Thanks a lot for your kind reply, and it is the api that I want to use.
