### ISSUE TITLE
Is there Mariadb/Mysql support 

### ISSUE THREAD

**Issue by BobWs** [sismics/docs#358]
Hi,
Is mariadb or mysql database supported? If so how do I link Teedy to mysql database?

**Comment by jendib** [comment]
There is no support for MariaDB/MySQL and it's not planned.
Use a PostgreSQL database instead.

**Comment by BobWs** [comment]
Okay, but where can I find the documentation on how to link PostgreSQL?

**Comment by jendib** [comment]
Please see https://github.com/sismics/docs/issues/326
