### ISSUE TITLE
is there anyway to run this offline to just index pdf files in a locally stored folder?

### ISSUE THREAD

**Issue by alih1029** [sismics/docs#359]
is there anyway to run this offline to just index pdf files in a locally stored folder?

**Comment by jendib** [comment]
What do you mean by "offline"?

>

**Comment by alih1029** [comment]
I went to docker, used the pull command, downloaded the image and did the run command and go to localhost:8080 but I don't get anything coming up?

I'm a student and want to use your software to index my pdfs and search through them for medical research.

**Comment by jendib** [comment]
It should work. It's more a Docker question than a Teedy issue however.
