### ISSUE TITLE
Best Export/Backup Solution

### ISSUE THREAD

**Issue by fictionalname** [sismics/docs#361]
Hi!

I'm really interesting in implementing the open source version of your great looking software, but I'm concerned that there doesn't seem to be a prescribed full export or backup solution.  I have had a look at your web site and in the demo and I can't see and documentation or mention of this.

Since all new documents are deleted after they ingested by the software, the only copy of my documents would reside within the application database.  This concerns me if I cannot bulk export the files or perform a reliable backup.

Can you please let me know the best solution to export the files or backup the database to restore, should there be an issue.

Thanks for your help and all your hard work with this great software.

**Comment by jendib** [comment]
The best way to backup is to just copy the data directory or the data volume if you use Docker.
To extract the documents, a simple script using the REST API would be easy to do.
Please see #249 and #331

**Comment by fictionalname** [comment]
Awesome, thanks!
