### ISSUE TITLE
Additional bulk import settings

### ISSUE THREAD

**Issue by doughnet** [sismics/docs#362]
At the moment the bulk import will toss the imported files into the quick upload.  A few requests:

- Is it possible to provide a flag/environment to have it automatically create a new "title" for each individual file using the filename. Also able to provide a tag

- To run the daemon without deleting the original files?

- Have a way for the actual server utilize a watched folder to import automatically versus using a separate client to do this?

**Comment by mackzzz** [comment]
Thumbs up for this idea! I'm migrating from Evernote with hundreds of properly named PDFs and that would honestly be a godsend. Only solution I can think of right now is creating a custom script using the API, which would extract the file name and set it as the title of a newly created document, then attach the file to the document and run it as a cronjob on a folder, triggering every time a new file is added. If this could be included in the bulk uploader it would make this piece of software even better!

**Comment by jendib** [comment]
The issue I have with that is that everyone has a special case for how they want to import stuff. If the importer evolve and is integrated into Teedy, it needs to be extensible somehow to adapt to all situations.

**Comment by jendib** [comment]
Closed by #415
