### ISSUE TITLE
Document ID - Why no such feature?

### ISSUE THREAD

**Issue by swissbyte** [sismics/docs#364]
Hi there

I rellay thought that i have found my future DMS. 
But stop... There is not DocumentID for the documents... Really?

Did i oversee something or is it true that there is no unique, upcounting DocumentID per Document visible in the WebInterface?

If yes: why? Could it be integrated in the future?
If no: what do i wrong?

Beneath that: Thank you for your effort! The tool looks great! Really great!

**Comment by vmario89** [comment]
hi, 
Teedy has got document IDs and file IDs for each file being inside a document. Please have a look at your browser's URL and in API docs too: https://demo.teedy.io/apidoc/#api-Document-GetDocument
The IDs are hashed values which are unique
