### ISSUE TITLE
Question about OCR extracted data

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#365]
Hi, 

i am looking deeply at the code for a while to find out how/where OCR text data is stored. Prior i used H2 database where the column "fil_content_c" stored text data extracted from file. But since migration to PostgreSQL i performed, the OCR data seems to be stored elsewhere/other format. How does that work? In PostgreSQL instead of text data the values are just numbers. Will the OCR be stored directly into the encrypted file "vault" ?
From reading the java files i am not fully able to solve those questions for me

 I asking because
* i need to reprocess all the files due to my database migration (because i had to truncate fil_content_c". there are thousands of files
* i wonder if it is possible to modify the OCR extracted content. Often tesseract creates crap which could be improved by hand (similar to using a tool with GUI like VietOCR)

regards, Mario

**Comment by jendib** [comment]
Whatever the database backend, the OCR output is always in fil_content_c unencrypted.

**Comment by vmario89** [comment]
Hi @jendib,
thanks for the hint. i played a bit with it. i did not know that this is stored as large object (LOB).

![grafik](https://user-images.githubusercontent.com/5631071/72276061-6d19ed80-362f-11ea-8814-28dfcc69b496.png)

![grafik](https://user-images.githubusercontent.com/5631071/72276107-815dea80-362f-11ea-96a3-0da4159f60d4.png)

i am trying to find out how to get the unecrypted content right now. found to use lo_open so far, but not the correct parameters
`loread(lo_open(fil_content_c::int,` 131072), 999999999)

**Comment by jendib** [comment]
I don't really know how to convert a LOB in text format, I don't need to do it in Java. But the data you need is definitely in this column.
