### ISSUE TITLE
/api/file/:id/process problems generating _thumb and _web correctly for GUI

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#366]
Hi,

I have an issue which i am not able to solve programmatically since my migration from H2 to postgresql. I merged all data except OCR content to the new database. I left this blank in psql  because extraction of fil_content_c from H2 to csv is really hard.

so my plan was to just let Teedy refill all OCR data by processing all files again using API. I found out that the api endpoint seems to only create OCR data but does not correctly handle _web and _thumb files as it seems. It will create them on file system but they do not work in the GUI. After the first re-processing of all files all _thumb and _web disappeared like this:

![grafik](https://user-images.githubusercontent.com/5631071/72284732-fb976a80-3641-11ea-8d74-4eb6ecf8fe4b.png)

In contrast if i go to a document by using GUI frontend i can reprocess (OCR, _thumb, _web) the file completely and it works. the images are generated and everything is fine.

Do you have some idea how i can solve this by code? At the moment i have had to re-process ~3000 files in one instance and ~4.800 on the second instance manually :-(

**Comment by jendib** [comment]
Using the API manually or clicking on the button in the UI should do exactly the same (the UI is calling the exact same API). Are you sure it's what's happening?

**Comment by vmario89** [comment]
hi,
i am testing different stuff and i dont find out whats the reason for this behaviour. but it hehaves like there must be some difference.

let me give an example: i am having a document with some ~30 files. For re-processing all files inside the doc i am running the following script:

```
#!/bin/bash
BASE_URL="https://dms.yourdomain.de"
DB_USER="teedy"
DB_NAME="teedy_db"
TEEDY_USER="admin"
AUTH_TOKEN=$(psql -t -U$DB_USER $DB_NAME --command="SELECT aut_id_c FROM t_authentication_token AS A JOIN t_user AS U ON U.use_id_c = A.aut_iduser_c WHERE use_username_c = '$TEEDY_USER' LIMIT 1;")
for FILE_ID in $(psql -t -U$DB_USER $DB_NAME --command="SELECT fil_id_c FROM t_file WHERE fil_iddoc_c = 'SOME-DOC-ID';"); do
    echo PROCESSING "$FILE_ID"
    curl --silent -X POST -H "Cookie: auth_token=$AUTH_TOKEN" "$BASE_URL/api/file/$FILE_ID/process"
done
```

curl return "{"status":"ok"}" for each file. the async log looks fine and output is the same for API call or in-GUI usage:
![grafik](https://user-images.githubusercontent.com/5631071/72299662-c7cc3d00-3661-11ea-87a2-d86ec381136b.png)

after that i restart jetty. the preview _thumb and _web are existent on filesystem but do not show correctly in GUI. 


--------
if i open the doc in GUI and click reprocess the file it works. After refreshing the page (CTRL + SHIFT +R in firefox) thumbnail is visible:
![grafik](https://user-images.githubusercontent.com/5631071/72300024-ef6fd500-3662-11ea-8851-d03e7f5e92a9.png)
if the files are existent on filesystem but have described trouble the GUI looks like this:
![grafik](https://user-images.githubusercontent.com/5631071/72299972-ca7b6200-3662-11ea-862a-e75f28c461ae.png)
if i delete the files without restarting jetty, GUI looks:
![grafik](https://user-images.githubusercontent.com/5631071/72299998-d9621480-3662-11ea-93cd-1b475f3282b7.png)

i have no idea :-/

**Comment by vmario89** [comment]
by the way here you can find my complete documentation for migration and for other Teedy things: https://wiki.fablabchemnitz.de/display/FCT/Teedy+1.8+Migration+from+H2+to+PostgreSQL

**Comment by jendib** [comment]
That's quite weird. Are you sure it's not a browser caching issue? (trying to eliminate the most obvious things)

**Comment by vmario89** [comment]
hi. yes it happens on different devices with different browser software (tried with chrome and firefox, even using private windows and so on). i think there happens sth. belonging to the document owner. i did not find out yet what happened. issue is persistent. when i have time again i will get another try to look what i can do to repair it. 

i noticed in the meantime that some of the document's files even cant be re-processed successfully manually from GUI. the _web view is missing sometimes. Don't know if there is any logical pattern behind

**Comment by vmario89** [comment]
i think i found the issue. i made some coffee and took another short try. 

it seems that only the creator of the file or the document can re-process it correctly. I took some documents with failed previews and checked who participates in the document. then i logged in as the other user and ran reprocess again for files of that document. That time it worked for those files.

i believe the root cause is that even if another user has granted permission to edit/delete stuff  (by group ACL) the re-processing is bound to the root creator of the item. Could you maybe validate this? I guess in a normal production environment this would not noticely appear because the re-processing will be done once the file created and thats it. So normally nobody would care.

**Comment by jendib** [comment]
Very nice catch 👍 
I fixed it!

**Comment by vmario89** [comment]
hallelujah. Thanks. now it works! :-)

**Comment by vmario89** [comment]
i adjusted my SQL script to loop over each user to kick on the reprocessing.

```
#!/bin/bash
BASE_URL="https://dms.yourdomain.de"
DB_USER="teedy"
DB_NAME="teedy_db"
TEEDY_USERS=$(psql -t -U$DB_USER $DB_NAME --command="SELECT use_username_c FROM t_user;")
 
for TEEDY_USER in $TEEDY_USERS; do
echo LOGGING IN AS $TEEDY_USER
#this reads exactly one token from the given user. If the user is not logged in it will be null and the token will be null too!
AUTH_TOKEN=$(psql -t -U$DB_USER $DB_NAME --command="SELECT aut_id_c FROM t_authentication_token AS A JOIN t_user AS U ON U.use_id_c = A.aut_iduser_c WHERE use_username_c = '$TEEDY_USER' LIMIT 1;")
for FILE_ID in $(psql -t -U$DB_USER $DB_NAME --command="SELECT fil_id_c FROM t_file AS F JOIN t_user AS U ON U.use_id_c = F.fil_iduser_c WHERE F.fil_deletedate_d IS NULL AND U.use_username_c = '$TEEDY_USER';"); do
echo PROCESSING "$FILE_ID"
curl --silent -X POST -H "Cookie: auth_token=$AUTH_TOKEN" "$BASE_URL/api/file/$FILE_ID/process"
sleep 2
done
done
#do not logout after processing (to keep the token alive!)
```
