### ISSUE TITLE
What is the database system and the location it stores files?

### ISSUE THREAD

**Issue by SamanChalian** [sismics/docs#367]
What is the database system and the location it stores files? and how can I found any documentation about it? I run it from scratch but every files was cleaned after restarting server!

**Comment by vmario89** [comment]
hey,
the database is either H2 or PostgreSQL. Belongs to the kind of installation you perform. You can check out my documentation i did: https://wiki.fablabchemnitz.de/display/FCT/Teedy+1.8dev+-+Unofficial+Documentation

we work with Teedy for a year now and digged a little bit deeper into sys config, SQL statements and so on.

**Comment by jendib** [comment]
Also if you are using the Docker image, the [README.md](https://github.com/sismics/docs/blob/master/README.md) says you have to mount a volume on `/data`
