### ISSUE TITLE
[Question] Is it possible re-OCR already OCRed pdf documents?

### ISSUE THREAD

**Issue by junpet** [sismics/docs#370]
I just recognized my scanned `.pdf` files have been OCRed during scanning. The result is trash. I thought Teedy will re-OCR the documents, for the better result. I could manage remove the OCR from one file my document, uploaded to my Teedy, and Tesseract made magick, it's almost perfect. 

My question/request is: Is there a hidden settings to re-OCR already OCRed documents? I've tried `Reprocess this file`, but the result is the same. If not, it would be nice such settings to overwrite the default OCR with the Tesseract one.

**Comment by jendib** [comment]
So you have OCR text embedded in your scanned PDF document? I didn't know it was possible. Could you upload the PDF (without anything sensitive)?

**Comment by junpet** [comment]
[This](https://mega.nz/#!6Ys0hAab!3jbrnnSRiRKo4Q0oXRaFA2bEqtsUN8o1JFZlawZr-HI) is the OCRed pdf (I got this by default if I scan a document). And [this](https://mega.nz/#!7J00iCqD!6iv-qYBVNu_Ltta3ELYHjT9q4ri4jahPwljPigv2ntc) is after I removed the text from it (with ghostscript).

**Comment by jendib** [comment]
Teedy decides if OCR is needed if there is no text in the PDF document. So in the first case, the text is just used as content and OCR never happens.

**Comment by junpet** [comment]
Well, that's logical. But it would be good to have an option to force OCR with Tesseract. What do you think, is it a valid feature request? By the way thanks for the answer.

**Comment by jendib** [comment]
Well yes it's possible, but it's a very niche use case. It would probably be easier to just disable the OCR from your scanner software.
