### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by deliciouslytyped** [sismics/docs#371]
Do you have user documentation anywhere?

~~For example, how can I see a list of all documents?~~ (I misunderstood the box in the bottom left, on the demo.)

**Comment by jendib** [comment]
@vmario89 made an unofficial technical documentation here: https://wiki.fablabchemnitz.de/display/FCT/Teedy+1.8dev+-+Unofficial+Documentation

However there is not user documentation yet.
