### ISSUE TITLE
Questions about the  Docker version

### ISSUE THREAD

**Issue by CoolMike77** [sismics/docs#372]
Hi

I just tested Teedy and love it so far. I'm using the Docker version on a VPS.

In the instruction it was mentioned to mount a Volume to the data directory. How do I do this? 

If a new version of Teedy is released, how do I upgrade whithout loosing my stored documents?

Regards
Michael

**Comment by jendib** [comment]
All data are in the `/data` folder inside the container. Please see https://docs.docker.com/storage/volumes/ for more informations about mounting volumes.

If you do this, no data will be lost on upgrading.

**Comment by CoolMike77** [comment]
Thanks for your answer. Just to be sure, when I use the following command, it does automatically mount this data directory?

docker run --rm --name sismics_docs_latest -d -e DOCS_BASE_URL='http://10.88.0.25:8100' -p 8100:8080 -v sismics_docs_latest:/data sismics/docs:latest

To upgrade, I just need to stop the container and execute the command above to start with the newest version of sismics and mounting the same data volume?

**Comment by jendib** [comment]
You need to create the named volume first. And also there is multiple way to mount a volume to a container that's why I sent you the Docker documentation. You can also have a network drive as a volume, it really depends what you want to do and is out of scope of Teedy.

Also with this command you will run the latest unstable version where upgrades are not necessarly automatic. You should use the stable versions for production usage.

**Comment by CoolMike77** [comment]
Ok, I think I got it:

First I create the volume:

docker volume create sismics-data

Afterwards I start the container with version 1.7 (latest stable):

docker run --rm --name sismics_docs -d -e DOCS_BASE_URL='http://10.88.0.25:8100' -p 8100:8080 -v sismics-data:/data sismics/docs:v1.7

In case of an update, I stop the container and start the new version with the same volume:

docker stop sismics_docs

docker run --rm --name sismics_docs -d -e DOCS_BASE_URL='http://10.88.0.25:8100' -p 8100:8080 -v sismics-data:/data sismics/docs:v1.8

**Comment by jendib** [comment]
This should work perfectly yes 👍
