### ISSUE TITLE
Bad OCR quality

### ISSUE THREAD

**Issue by CoolMike77** [sismics/docs#373]
Hi

I have a problem with the OCR quality in Teedy. When I upload a PDF, I choose the language german, but it does still have a lot of mistakes in the text. My scanner does create the PDF with 300 dpi. 

Here you can see an example PDF: 

http://teedy.brunner.ws/test.pdf

Does Teedy really use the correct language for the OCR processe? 

I just tested the free OCR service at https://www.newocr.com/ and it did detect nearly 100% correct with my example PDF. But when I use the same pdf in Teedy, I get so many mistakes.

Regards
Michael

**Comment by jendib** [comment]
Teedy uses the document language to pass it to Tesseract for OCR.
It also depends on the Tesseract version installed on your server. Maybe try calling Tesseract directly to compare the result (it should be exactly the same).

**Comment by CoolMike77** [comment]
I'm using the docker version, how can I test it directly with Tesseract?  Or is the quality of my pdf not ok?

**Comment by CoolMike77** [comment]
Ok, I found out how to use tesseract inside the docker container. But Teseract can not convert a pdf to text. What are you using to convert the pdf first to a format which tesseract understands? I can't find gs or convert in this container.

**Comment by CoolMike77** [comment]
As I don't know how you convert the pdf to a image, I just did this step with convert on my local machine. I did convert the above mentioned pdf to a tiff and then  executed the following command inside the teedy container:

tesseract -l deu ./test.tiff ./test.txt

The result is 100% perfect, nearly no mistakes at all. 

There must be something wrong in Teedy. This problem does exist also in the demo at teedy.io.

**Comment by jendib** [comment]
A unit test needs to be written with your PDF example and try to figure out what's wrong.
Teedy is doing some processing before sending it to Tesseract (upscale and make the image straight), it may come from here.

**Comment by CoolMike77** [comment]
Perfect, thanks! Is there anything I can help you?

**Comment by jendib** [comment]
Well if you can code the unit test it would be great :) Contributions are always welcome.

**Comment by CoolMike77** [comment]
Sorry, I'm not a coder... I hope you can find the problem and fix it. Teedy is such a nice solution. Thanks for developing it!

**Comment by jendib** [comment]
I fixed it, it was the PDF to image conversion (before passing it to Tesseract) which was of low quality.

**Comment by CoolMike77** [comment]
Thank you so much for fixing this problem. I'm using the docker version, how long does it take until this modification is in the latest?

**Comment by jendib** [comment]
It's already done, the `sismics/docs:latest` Docker image is automatically built at each commit on the master branch.

**Comment by CoolMike77** [comment]
Amazing, thanks a lot. The problem is fixed, the OCR quality is now perfect.
