### ISSUE TITLE
Build WAR for Github releases

### ISSUE THREAD

**Issue by deliciouslytyped** [sismics/docs#374]
The readme says ```The latest release is downloadable here: https://github.com/sismics/docs/releases in WAR format. The default admin password is "admin". Don't forget to change it before going to production.``` but there are no WAR files for the last two releases.

**Comment by jendib** [comment]
Most people are using the Docker image, but you're right, it should be a good idea to build the war files too.

**Comment by jendib** [comment]
Done.
