### ISSUE TITLE
Create new tags when creating a document

### ISSUE THREAD

**Issue by deliciouslytyped** [sismics/docs#377]
When you create a new document; it would be nice if new tags could be created on the fly, without separately opening the tags tab. 
![image](https://user-images.githubusercontent.com/47436522/74395224-0dba2380-4e0f-11ea-950f-7334228be6e6.png)

**Comment by deliciouslytyped** [comment]
Nevermind, I just found the "new tag" button. Maybe put another one next to the tags field?

**Comment by jendib** [comment]
I'm not sure it's really useful, and would make the UI too cluttered.
