### ISSUE TITLE
Remove "request body has been consumed" logs

### ISSUE THREAD

**Issue by skoe** [sismics/docs#378]
To test Teedy, I started it using mvn jetty:run. When I set up some users, I was surprised to see passwords in plaintext in log messages:

Feb. 13, 2020 2:50:36 NACHM. org.glassfish.jersey.servlet.WebComponent filterFormParameters
WARNUNG: A servlet request to the URI ..../docs-web/api/user?email=xyz%40example.com&**password=secret**&**passwordconfirm=secret**&storage_quota=100000000000&username=voehringer contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.

I think that nobody should be able to see passwords, not even root/admin. Is this caused by my (non) deployment and can never happen in real life installations? Are the passwords stored encrypted in a secure way?

**Comment by jendib** [comment]
I don't have this warning in production indeed (using the Docker image), but after seeing your log, it seems it happen when you create a new user.

And all password are obviously stored encrypted using BCrypt as you can confirm yourself in the code and by opening the database.

**Comment by skoe** [comment]
Thanks for the response and good to hear that you use BCrypt :) In the meantime I managed to deploy a WAR build using jetty9 on Ubuntu. Unfortunately I have the same log message in /var/log/syslog now:

Feb 14 09:58:59 dmsbox jetty9[2393]: WARNUNG: A servlet request to the URI http://192.168.5.98:8080/docs-web-1.7/api/user?email=...&password=secret123&passwordconfirm=secret123&storage_quota=100000000000&username=... contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.

Some discomfort remains that there is the potential that passwords appear in a log. You could leave this issue as a feature request for client-side hashing with, e.g., scrypt. Or maybe you have an idea how to avoid log messages with cleartext passwords in general to make sure there are no potential plaintext password leaks when a server gets attacked.

In any case, thank you for the great software!

**Comment by jendib** [comment]
Yes you are right, and this log is useless anyway. I could try to see how to remove it completely.

**Comment by skoe** [comment]
Thanks for the quick fix!
