### ISSUE TITLE
Add document content to api

### ISSUE THREAD

**Issue by pBauma** [sismics/docs#383]
It would be very helpful if the content of a document could be obtained by the `/api/document/:id` api call.

**Comment by jendib** [comment]
Documents have no content. Files are carrying it and are accessible with another endpoint.

**Comment by pBauma** [comment]
Sorry for the confusion, i updated the issue accordingly

**Comment by jendib** [comment]
File data is accessible with `/api/file/:id/data`

**Comment by pBauma** [comment]
With content i mean the result of tesseract-ocr

**Comment by jendib** [comment]
`/api/file/:id/data?size=content` is what you seek.

**Comment by pBauma** [comment]
Thank you!
