### ISSUE TITLE
Data subdirectory distribution

### ISSUE THREAD

**Issue by davidmichaelhuber** [sismics/docs#384]
I want to use Teedy using Docker in the following manner because I only have one fast drive which's capacity is very limited.

```
docker run -p 8080:8080 \
-v /ssd/teedy/db:/data/db \
-v /ssd/teedy/log:/data/log \
-v /ssd/teedy/lucene:/data/lucene \
-v /ssd/teedy/theme:/data/theme \
-v /hdd/teedy/storage:/data/storage \
sismics/docs:v1.7
```

 - Is it known if the distribution of the data subdirectories to different drives can cause any trouble? 
 - Also does it make sense to store the `/data/db` and `/data/lucene/` directories on a faster drive performance wise? Is there an in-memory database in use or will a faster drive affect individual database queries?

**Comment by jendib** [comment]
- I don't see any problem doing this, but I never actually tried.
- Faster drives for /db and /lucene will definitely increase performances. There is some memory caching involved for the database and Lucene, but of course not everything is cached so a fast drive is better.
