### ISSUE TITLE
Default language bug / set lang in docs

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#385]
Hi, since some commits i cannot change the default language in the backend settings and i cannot change the document's language to another one. Clicking on save it will not be stored. There is no error in logs :-(

Could somebody validate the same behaviour?
regards, Mario

**Comment by jendib** [comment]
It works on the demo server. Do you have any error in the javascript console when you try to edit the language?

**Comment by vmario89** [comment]
Hey, no there is no error shown. I checked in Firefox console :-/
i have no idea what happens here. I will try to recompile Teedy with fresh pull. Last time i just did git pull to update the repo and did a regular build with cleaning before. maybe something is weird
