### ISSUE TITLE
Teedy v1.8 question about /api/file/list ?

### ISSUE THREAD

**Issue by mmuallem** [sismics/docs#393]
Hello everyone!

I am using Teedy as a headless DMS self hosted in my own infra. Currently I am running v1.8 through the official sismics/docs docker images.

Everything is working as expected and I am happy, bar one issue. 

I am trying to fetch the files of a certain document. I have the document Id, and querying the document clearly shows multiple files in the `file_count` property. Additionally, I can see the files normally in the Teedy UI.

The problem is. Using the api call `api/file/list` with the `id` params as the desired document id, I keep getting this response 

```
{
    "files": []
}
```

The same occurs even if I create a share link and use its Id. 

Help please!

**Comment by jendib** [comment]
If you can see it in the UI you should be able to see it through the API because the UI is using the same API directly.
You can try to compare your request with the one from the UI using the browser debugger (F12).

**Comment by mmuallem** [comment]
Many thanks @jendib ,

I traced my issue to improper content type

I have an additional question please. Why does `file_id` when querying with `document/list` not always have a value even when a document does exist?

Thanks again!

**Comment by jendib** [comment]
As described in the API documentation `file_id` is the "main" file ID of the document. If the document contains zero files you will have no value here. If it contains more than one file, it will be the first.
It's used in the UI to display a document thumbnail in grid view.
