### ISSUE TITLE
Add files form quick upload to an existing document

### ISSUE THREAD

**Issue by Gabisonfire** [sismics/docs#394]
Hi,

First, thank you so much for this great software, I've been looking forever for a robust solution like Teedy.

Only one issue I'm having: I'm using the docs-importer to scan a directory, the scanned files appear in the "Quick Upload" section, I can create a new document with these files but I'd like to know if it would be possible to add these files to an existing document.

If I go on an existing document and click "Add files", I can only select files from my computer.

Thank you!

**Comment by jendib** [comment]
No you cannot add those "quick upload" files to an existing document currently.

**Comment by Gabisonfire** [comment]
Ok, thank you, It would be a nice feature :)

**Comment by jendib** [comment]
I agree :)

**Comment by mannp** [comment]
Its the main thing stopping me from going all in with docs.

I'd prefer to upload and the system create the doc for me and then flag it as not verified or something.

At least though the doc is added and can be searched etc, even if the name and details are not 100% correct.

**Comment by jendib** [comment]
Actually the latest importer is creating one document per imported file, it's not putting the files in "quick upload" anymore. Maybe that would be better for you. https://github.com/sismics/docs/tree/master/docs-importer

**Comment by Gabisonfire** [comment]
@jendib That's nice, I did not build the importer, I've used the latest binaries (from the 1.5 tag).

I will try it out but perhaps it would be nice to provide them :)

**Comment by mannp** [comment]
Okay that sounds better and worth another try then :)

Only found the binary for v1.5 too....

**Comment by jendib** [comment]
I've added the binaries for the 1.8 version 👍

**Comment by mannp** [comment]
That's slick, thanks for the update and binary, now to find out how I export all I have in quick uploads, so I can re import.
