### ISSUE TITLE
Import specified Folder in Mailbox

### ISSUE THREAD

**Issue by ryperx** [sismics/docs#395]
Hey,
thanks for the tools. I tried it out today and would like one additional feature.
Is it possible to import a specified folder in the mailbox? 

I have filter rules defined that put all mails into a specified folder. It would be great if i can only monitor this folder and not the complete inbox.

Is this possible or is it a enhancement?

**Comment by jendib** [comment]
Currently the folder is "inbox" and it's hardcoded there: https://github.com/sismics/docs/blob/master/docs-core/src/main/java/com/sismics/docs/core/service/InboxService.java#L175
