### ISSUE TITLE
Default Search and Bulk Operations Questions

### ISSUE THREAD

**Issue by fictionalname** [sismics/docs#397]
Hello,

I'm new to this software, but I'm really impressed so far.  Thanks for your hard work!

I have 2 questions, which may be something I'm missing or a feature request.

1.  How do I default the search option to full text search without having to prepend the search with full:?  I always want to to search the entire document, so this would save some typing.

2.  How do I perform bulk operations on the documents?  I used the bulk import tool to import 800 documents before I figured out tagging in the application.  Now I need to either delete everything and re-import with the right tag, or tag all the current documents with the right tag.  Is there a way of selecting all and performing an operation?

Thanks for your help.

**Comment by jendib** [comment]
1. Not currently possible, you have to prepend with "full:"
2. Not possible through the UI, your best solution would be to use the API to do this

**Comment by fictionalname** [comment]
Hello, 

Thanks for the fast response.  

Would it be able to add these options to the list of feature requests then please?

Thank for your hard work!

**Comment by jendib** [comment]
Bulk tagging is handled by #109 already
