### ISSUE TITLE
original file name is lost when uploaded/stored in teedy

### ISSUE THREAD

**Issue by Knaui** [sismics/docs#399]
Uploaded documents are saved in the /storage folder but are automatically renamed, so that the original file name is totally lost.
This makes it very nearly impossible to use those files without teedy, for example by syncing them or using them with another program, because the information which file is which is gone.
Is there a way to keep the original file name intact (on the file system) but add a teedy identifier to the file name when importing ??

**Comment by jendib** [comment]
No it's not supported. The best way to do what you need is to use the API.
