### ISSUE TITLE
File can't be renamed shortly after it is added

### ISSUE THREAD

**Issue by hrvylein** [sismics/docs#412]
I added a large amount of files over the RESTful API. Right after I added the file and got it's ID, I tried to rename the file. The server response was ok, but the file wasn't renamed. It took me several hours of debugging my scripts to resolve this problem. Right now I wait for ~60 seconds after retrieving the file id to start the renaming. Even tho every response from the server says ok, some files aren't renamed.

Maybe the logic how the API checks if a file was renamed must be changed or the json response must return a specific error (like "file pending") so developers can retry to rename the file some seconds later.

If this is a wanted behaviour the docs should give little more information about that specific API endpoint.

**Comment by jendib** [comment]
Can you provide more info on how to reproduce the issue? From my side file renaming works no problem.

**Comment by hrvylein** [comment]
Sure! Using a node.js cli to bulk add files (~50 files per run, sometimes more, sometimes less).

1. `/api/user/login` get credentials
2. create new document and get its id from `/api/document`
3. add a new file to the document over `/api/file` and get its id

The exact moment the promise resolves successfully for `/api/file` i try to rename the file over `/api/file/:id` which always returns ok, but the file isn't updated. To mitigate the problem I wait for 60 seconds after adding the file. This still doesn't works all the time but lessens the problem to a few missing files.

I don't have these problems when using the webif. I think the problem arouses from the strict timings when using the API through scripts.

**Comment by jendib** [comment]
Any error or info in logs?

**Comment by hrvylein** [comment]
No errors in the logs when bulk adding files.

`16 May 2020 14:19:50,701 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:33) Document created event: DocumentCreatedAsyncEvent{document=Document{id=c7ab6724-134e-43c5-b0e5-507f9053901e}} 
16 May 2020 14:19:50,743 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:33) Document created event: DocumentCreatedAsyncEvent{document=Document{id=7259ee97-a276-4e20-911c-f66b8e8fa7c9}} 
16 May 2020 14:19:50,795 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:33) Document created event: DocumentCreatedAsyncEvent{document=Document{id=17251ace-5662-46c3-9aa6-c767eeb3b9af}} 
16 May 2020 14:19:50,842 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:33) Document created event: DocumentCreatedAsyncEvent{document=Document{id=210805f7-1487-43a2-a98f-ef4ecd99e2a4}} 
16 May 2020 14:19:50,846 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:33) Document created event: DocumentCreatedAsyncEvent{document=Document{id=334113fa-f48e-474a-8f44-3e9b28262b0a}} 
16 May 2020 14:19:50,858 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:33) Document created event: DocumentCreatedAsyncEvent{document=Document{id=fbaec805-49c9-4bae-8bf0-81d6603fe9a7}} 
16 May 2020 14:19:51,438 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:33) Document created event: DocumentCreatedAsyncEvent{document=Document{id=77df9036-9a82-42e0-a2ee-a02006fba1d7}} 
16 May 2020 14:19:52,048 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:33) Document created event: DocumentCreatedAsyncEvent{document=Document{id=6c4d0ef9-a3f6-456f-9456-24c407765913}} 
16 May 2020 14:19:52,075 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:33) Document created event: DocumentCreatedAsyncEvent{document=Document{id=ac161953-c74d-4b7d-853a-65f0c219f6f7}} 
16 May 2020 14:19:52,248 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{file=File{id=d0ded04d-05d9-45cc-8c3c-42d987d9984f, name=07_14.pdf}, language=deu} 
16 May 2020 14:19:52,595 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=c7ab6724-134e-43c5-b0e5-507f9053901e} 
16 May 2020 14:19:52,600 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{file=File{id=b4f35101-ff36-42b5-8d57-40bc6da2c417, name=05_14.pdf}, language=deu} 
16 May 2020 14:19:52,606 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{file=File{id=d2656b92-d9c9-4915-84a9-c7bab046d81c, name=04_14.pdf}, language=deu} 
16 May 2020 14:19:52,599 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=77df9036-9a82-42e0-a2ee-a02006fba1d7} 
16 May 2020 14:19:52,598 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{file=File{id=8fbe6d9d-f155-4ca1-b703-8d9833a5ca88, name=06_14.pdf}, language=deu} 
16 May 2020 14:19:52,608 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=7259ee97-a276-4e20-911c-f66b8e8fa7c9} 
16 May 2020 14:19:52,605 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=17251ace-5662-46c3-9aa6-c767eeb3b9af} 
16 May 2020 14:19:55,045 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:147) File content extracted in 85ms `

File contents extract after the first update events fire. Maybe sth is blocking the update event for the file?

**Comment by jendib** [comment]
I made a few changes which should improve things. Can you try it out? (wait for Travis build to finish)

**Comment by hrvylein** [comment]
```
18 May 2020 20:15:17,739 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:35) Document created event: DocumentCreatedAsyncEvent{documentId=5ec1de82-c6b3-4977-821d-74a24edf379b} 
18 May 2020 20:15:17,762 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:35) Document created event: DocumentCreatedAsyncEvent{documentId=2a50f43f-a98e-447c-bc61-0ff5052cf6f5} 
18 May 2020 20:15:18,177 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:35) Document created event: DocumentCreatedAsyncEvent{documentId=bf332023-6412-408b-a7ed-cf23e0576677} 
18 May 2020 20:15:18,561 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:35) Document created event: DocumentCreatedAsyncEvent{documentId=a9489b31-53d0-4817-bd65-2a3590454787} 
18 May 2020 20:15:18,657 INFO com.sismics.docs.core.util.FileUtil.startProcessingFile(FileUtil.java:221) Processing started for file: 2151694d-3432-4080-815f-1637b6391b85 
18 May 2020 20:15:18,669 INFO com.sismics.docs.core.util.FileUtil.startProcessingFile(FileUtil.java:221) Processing started for file: 8e1c49fc-dc83-4ff4-b507-22f36de0568c 
18 May 2020 20:15:18,695 INFO com.sismics.docs.core.util.FileUtil.startProcessingFile(FileUtil.java:221) Processing started for file: 0ad1d6ad-03ab-4699-bf15-830d3ff100f2 
18 May 2020 20:15:18,786 INFO com.sismics.docs.core.util.FileUtil.startProcessingFile(FileUtil.java:221) Processing started for file: 1b4eb14c-4df3-4e22-8776-ed5c5b88e9fa 
18 May 2020 20:15:18,877 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:35) Document created event: DocumentCreatedAsyncEvent{documentId=a7ddb413-7895-41ef-886f-346d4e1f58fe} 
18 May 2020 20:15:18,893 INFO com.sismics.docs.core.util.FileUtil.startProcessingFile(FileUtil.java:221) Processing started for file: 99f1da7d-6366-498b-91e3-f100ec6f3e9a 
18 May 2020 20:15:18,994 INFO com.sismics.docs.core.util.FileUtil.startProcessingFile(FileUtil.java:221) Processing started for file: 3a4e0cd1-8ebb-45ef-9b62-e96c148c0523 
18 May 2020 20:15:19,249 INFO com.sismics.docs.core.util.FileUtil.startProcessingFile(FileUtil.java:221) Processing started for file: ed34485e-3327-4ed4-ad55-11ce524294ac 
18 May 2020 20:15:19,280 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:35) Document created event: DocumentCreatedAsyncEvent{documentId=25b0169b-4f96-4b40-ac49-c74679a4c151} 
18 May 2020 20:15:19,306 INFO com.sismics.docs.core.util.FileUtil.startProcessingFile(FileUtil.java:221) Processing started for file: b6a0c44c-720b-4c33-a2f8-74de34f31189 
18 May 2020 20:15:19,542 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:35) Document created event: DocumentCreatedAsyncEvent{documentId=d7172ba7-afb2-4dd7-97e1-408c4ba93730} 
18 May 2020 20:15:19,788 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:35) Document created event: DocumentCreatedAsyncEvent{documentId=5c234564-c657-4f17-a8aa-fff9b482ceed} 
18 May 2020 20:15:20,068 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{fileId=2151694d-3432-4080-815f-1637b6391b85, language=deu} 
18 May 2020 20:15:20,326 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=5c234564-c657-4f17-a8aa-fff9b482ceed} 
18 May 2020 20:15:21,313 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{fileId=8e1c49fc-dc83-4ff4-b507-22f36de0568c, language=deu} 
18 May 2020 20:15:21,359 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:155) File content extracted in 18ms: 2151694d-3432-4080-815f-1637b6391b85 
18 May 2020 20:15:21,965 INFO com.sismics.docs.core.util.FileUtil.endProcessingFile(FileUtil.java:231) Processing ended for file: 2151694d-3432-4080-815f-1637b6391b85 
18 May 2020 20:15:21,969 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=a7ddb413-7895-41ef-886f-346d4e1f58fe} 
18 May 2020 20:15:22,433 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{fileId=0ad1d6ad-03ab-4699-bf15-830d3ff100f2, language=deu} 
18 May 2020 20:15:23,176 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:155) File content extracted in 72ms: 8e1c49fc-dc83-4ff4-b507-22f36de0568c 
18 May 2020 20:15:23,945 INFO com.sismics.docs.core.util.FileUtil.endProcessingFile(FileUtil.java:231) Processing ended for file: 8e1c49fc-dc83-4ff4-b507-22f36de0568c 
18 May 2020 20:15:23,949 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=2a50f43f-a98e-447c-bc61-0ff5052cf6f5} 
18 May 2020 20:15:23,992 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:155) File content extracted in 29ms: 0ad1d6ad-03ab-4699-bf15-830d3ff100f2 
18 May 2020 20:15:24,612 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{fileId=1b4eb14c-4df3-4e22-8776-ed5c5b88e9fa, language=deu} 
18 May 2020 20:15:25,213 INFO com.sismics.docs.core.util.FileUtil.endProcessingFile(FileUtil.java:231) Processing ended for file: 0ad1d6ad-03ab-4699-bf15-830d3ff100f2 
18 May 2020 20:15:25,215 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=a9489b31-53d0-4817-bd65-2a3590454787} 
18 May 2020 20:15:25,636 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{fileId=99f1da7d-6366-498b-91e3-f100ec6f3e9a, language=deu} 
18 May 2020 20:15:26,027 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:155) File content extracted in 27ms: 1b4eb14c-4df3-4e22-8776-ed5c5b88e9fa 
18 May 2020 20:15:26,320 INFO com.sismics.docs.core.util.FileUtil.endProcessingFile(FileUtil.java:231) Processing ended for file: 1b4eb14c-4df3-4e22-8776-ed5c5b88e9fa 
18 May 2020 20:15:26,333 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=25b0169b-4f96-4b40-ac49-c74679a4c151} 
18 May 2020 20:15:26,796 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{fileId=3a4e0cd1-8ebb-45ef-9b62-e96c148c0523, language=deu} 
18 May 2020 20:15:26,881 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:155) File content extracted in 18ms: 99f1da7d-6366-498b-91e3-f100ec6f3e9a 
18 May 2020 20:15:27,522 INFO com.sismics.docs.core.util.FileUtil.endProcessingFile(FileUtil.java:231) Processing ended for file: 99f1da7d-6366-498b-91e3-f100ec6f3e9a 
18 May 2020 20:15:27,527 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=5ec1de82-c6b3-4977-821d-74a24edf379b} 
18 May 2020 20:15:27,980 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{fileId=ed34485e-3327-4ed4-ad55-11ce524294ac, language=deu} 
18 May 2020 20:15:28,563 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:155) File content extracted in 77ms: 3a4e0cd1-8ebb-45ef-9b62-e96c148c0523 
18 May 2020 20:15:29,540 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:155) File content extracted in 46ms: ed34485e-3327-4ed4-ad55-11ce524294ac 
18 May 2020 20:15:29,577 INFO com.sismics.docs.core.util.FileUtil.endProcessingFile(FileUtil.java:231) Processing ended for file: 3a4e0cd1-8ebb-45ef-9b62-e96c148c0523 
18 May 2020 20:15:29,579 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=d7172ba7-afb2-4dd7-97e1-408c4ba93730} 
18 May 2020 20:15:29,864 INFO com.sismics.docs.core.util.FileUtil.endProcessingFile(FileUtil.java:231) Processing ended for file: ed34485e-3327-4ed4-ad55-11ce524294ac 
18 May 2020 20:15:29,866 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{fileId=b6a0c44c-720b-4c33-a2f8-74de34f31189, language=deu} 
18 May 2020 20:15:30,567 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=bf332023-6412-408b-a7ed-cf23e0576677} 
18 May 2020 20:15:31,119 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:155) File content extracted in 49ms: b6a0c44c-720b-4c33-a2f8-74de34f31189 
18 May 2020 20:15:31,430 INFO com.sismics.docs.core.util.FileUtil.endProcessingFile(FileUtil.java:231) Processing ended for file: b6a0c44c-720b-4c33-a2f8-74de34f31189 
```

With `docker pull sismics/docs:d9ad69c7` I'm not getting a server response for `/api/file/:id` for half of the files.

**Comment by jendib** [comment]
Sounds related to #402, you should use PostgreSQL database. H2 is only suitable for very light usage.

**Comment by hrvylein** [comment]
Can you point me to the documentation on how to setup the Postgres connection and where to find the db scheme? Is migration available?

**Comment by vmario89** [comment]
Hey,
i did a migration from H2 to PSQL successfully some months ago. It's a bit tedious but i documented on how i did it because i had a growing instance which required more power :https://wiki.fablabchemnitz.de/display/FCT/Teedy+1.8+Migration+from+H2+to+PostgreSQL

just leave some comments for the parts which are not understable right now. I think the docs have to be reworked.

regards, Mario

**Comment by jendib** [comment]
@hrvylein By the way I made a few more changes which should improve things for large imports (even on H2 database).
If you have some time please give it a try.

**Comment by hrvylein** [comment]
Wow, great fix. Now I'm not encountering any errors and it seems like all file names are renamed correctly!

**Comment by jendib** [comment]
That's great! If you have some out of memory errors (can happen in the OCR processing if you upload a lot of files), you can increase the Java heap size (currently at 1GB max).
