### ISSUE TITLE
How to specify tags when adding a document with API

### ISSUE THREAD

**Issue by Cornelicorn** [sismics/docs#413]
I’m currently trying to add the ability to give tags by # in the filename for the docs-importer.
Before it was just one tag. Now when I want to do multiple tags I’m struggling to find the exact formatting.
The Code before:
https://github.com/sismics/docs/blob/d428e89c305bc7f0605c94262a40fe680dddfda7/docs-importer/main.js#L273-L279

The API documentation says a List of ID tags should be given:
![image](https://user-images.githubusercontent.com/40914430/82329145-2a06c700-99e1-11ea-98fc-e93733f29f55.png)
But giving a list of tags doesn't work:
`tags: ["2071fdf7-0e26-409d-b53d-f25823a5eb9e","594f9926-0f7c-4187-bea8-f929e4fe97b1"]`
Both UUIDs are grapped from `/api/tag/list` but this creates the document without any tags.
What would be the correct formatting?

**Comment by jendib** [comment]
`tags: ["2071fdf7-0e26-409d-b53d-f25823a5eb9e","594f9926-0f7c-4187-bea8-f929e4fe97b1"]`should indeed work.
The parameters need to be sent in URL encoded format, like this: `tags=2071fdf7-0e26-409d-b53d-f25823a5eb9e&tags=594f9926-0f7c-4187-bea8-f929e4fe97b1`

**Comment by Cornelicorn** [comment]
ok, but if `tags: ["2071fdf7-0e26-409d-b53d-f25823a5eb9e","594f9926-0f7c-4187-bea8-f929e4fe97b1"]` should work, should I open another issue for that? Or will you relabel this one as a bug?

**Comment by jendib** [comment]
There is no bug, the UI is using this same API and it works. There should be something wrong in your code.

**Comment by Cornelicorn** [comment]
It works with URL encoding: `tags=2071fdf7-0e26-409d-b53d-f25823a5eb9e&tags=594f9926-0f7c-4187-bea8-f929e4fe97b1`
But if I take `docs/docs-importer/main.js` and just change https://github.com/sismics/docs/blob/d428e89c305bc7f0605c94262a40fe680dddfda7/docs-importer/main.js#L278 to `tags: ["2071fdf7-0e26-409d-b53d-f25823a5eb9e","594f9926-0f7c-4187-bea8-f929e4fe97b1"]` it doesn't add the Tags. I'm really sorry if I'm missing something here.

`tags: '594f9926-0f7c-4187-bea8-f929e4fe97b1'` works, `tags: ['594f9926-0f7c-4187-bea8-f929e4fe97b1']` doesn't.

**Comment by Cornelicorn** [comment]
Request formats the tags array like this:
`&tags%5B0%5D=2071fdf7-0e26-409d-b53d-f25823a5eb9e&tags%5B1%5D=594f9926-0f7c-4187-bea8-f929e4fe97b1`
The problem is with the request library.
Request has been deprecated btw [https://github.com/request/request/issues/3142](url)
