### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by ah332m** [sismics/docs#419]
when i add file or upload document it shows "upload error" and i can't upload to the folder , do i need to download teedy importer ? how to fix it ?

and i want to know how to compile the build to use it in windows

**Comment by ah332m** [comment]
ok no problem

**Comment by ah332m** [comment]
give me your email i'll send you the logs and any info you want it

**Comment by jendib** [comment]
You can anonymize the logs and put it here.

**Comment by ah332m** [comment]
ok no problem just tell me which logs i need to send over here ?

**Comment by ah332m** [comment]
hello ben is there any solution ??
you didn't response on my issue

**Comment by Xosten** [comment]
Hi I have the same issue some times. I noticed this is maybe linked with the file size. For me when I upload more than 1Mo file size I get this error. 

I assume that you have to change your upload limited in your webserver maybe?

**Comment by ah332m** [comment]
idk man but i tried to upload 60kb file and still get the same error , i hope any one can get me solution for this problem ....
@jendib

**Comment by Xosten** [comment]
> idk man but i tried to upload 60kb file and still get the same error , i hope any one can get me solution for this problem ....
> @jendib

I never used Tomcat, but you should search on google how you can modify the upload limit in tomcat? Normaly this should fix the issue.

I use Nginx and by modifying the upload limit, it fixed for me.

**Comment by ah332m** [comment]
> > idk man but i tried to upload 60kb file and still get the same error , i hope any one can get me solution for this problem ....
> > @jendib
> 
> I never used Tomcat, but you should search on google how you can modify the upload limit in tomcat? Normaly this should fix the issue.
> 
> I use Nginx and by modifying the upload limit, it fixed for me.

I MEAN i never used nginx !!
if you have a link on how to deploying the app and how to update the limit i'd be thankful man .
