### ISSUE TITLE
tmp folder is getting very large with 30000 documents

### ISSUE THREAD

**Issue by dangerfish96** [sismics/docs#420]
Hi, thank you very much for the project again.
I get a problem that my /tmp in the docker container is growing in size very much.
I had to clean the /tmp directory which got to 850GB even though the data folder is only 30GB

**Comment by jendib** [comment]
I will need a reproduction scenario from an empty Teedy instance.

**Comment by dangerfish96** [comment]
I try to deliver it in the next few days
