### ISSUE TITLE
Search preferences

### ISSUE THREAD

**Issue by Dodoooh** [sismics/docs#423]
Is it possible to change the search preferences, I would like to always do a fulltext search. Also, I would like not to have to type the whole word. 
Thanks for this great software, I will probably spend the next days scanning my files ;)

**Comment by aliaskimber** [comment]
> Is it possible to change the search preferences, I would like to always do a fulltext search. Also, I would like not to have to type the whole word.
> Thanks for this great software, I will probably spend the next days scanning my files ;)

I second this request.

Additionally, I would love if the search results could mention the filename instead of just the document name. This makes it much easier to find what you're looking for in case you have a few files in a document.

Keep up the good work!

**Comment by jendib** [comment]
The fulltext search is now used by default, it makes more sense indeed.
The previous simple search is still possible by using "simple:"
