### ISSUE TITLE
Pin stable version of document

### ISSUE THREAD

**Issue by cspk** [sismics/docs#428]
It would be nice to have ability to mark a document version as stable/current. This version would be the one that downloads by default. Any following versions uploaded would have to be reviewed and approved to become stable, and remain in "draft" state until the approval.

**Comment by jendib** [comment]
Documents don"t have versions currently, only files within documents do.

**Comment by cspk** [comment]
Any plans for document versions instead of files? Any plans to pin stable version of a file?
