### ISSUE TITLE
Docker-compose 

### ISSUE THREAD

**Issue by Aruscha** [sismics/docs#430]
Hello,
Does anyone have a Docker-compose file with postgres for me?

I tried to build mine, but I can't get it to work, so I deleted them all :D

**Comment by robov** [comment]
This is part of it...
NOT WORKING COMPLETELY YET
Teedy does start up, and I can login etc, but uploading fails

version: "3"

services:
  db:
    image: postgres:alpine
    container_name: teedy_db
    environment:
      POSTGRES_USER: teedy
      POSTGRES_DB: teedy
      POSTGRES_PASSWORD: teedy

  docs:
    image: sismics/docs
    container_name: docs
    restart: always
    ports:
      - "8222:8080"
    environment:
      DOCS_BASE_URL: "https://docs.main.local"
      DATABASE_URL: "jdbc:postgresql://db:5432/teedy"
      DATABASE_USER: "teedy"
      DATABASE_PASSWORD: "teedy"
    volumes:
      - /teedy/docs:/data

**Comment by Aruscha** [comment]
Hey,

thank you very much, uploading is not possible, is it maybe because of postgres ?

**Comment by Aruscha** [comment]
Yeah lol, fixed your BUG :D
                                                                                             

version: "3"

services:
  teedy_db:
    image: postgres:alpine
    container_name: teedy_db
    environment:
     POSTGRES_USER: user_teedy
     POSTGRES_DB: teedy_password
     POSTGRES_PASSWORD: teedy

  docs:
    image: sismics/docs
    container_name: docs
    restart: always
    user: root
    ports:
     - "8222:8080"
    environment:
#     DOCS_BASE_URL: "https://docs.main.local"
#     DATABASE_URL: "jdbc:postgresql://db:5432/teedy"
     DATABASE_USER: "user_teedy"
     DATABASE_PASSWORD: "teedy_password"
     DATABASE_DB: "teedy"
     DATABASE_HOST: "teddy_db"

**Comment by jendib** [comment]
YAML si indentation sensitive, so providing a Docker compose without proper formatting will not work.
Also in your "fix" you remove the volume, meaning data won't be persisted after a restart.

**Comment by Aruscha** [comment]
you are right, i just copied and pasted it, so you have to indent it manually, removing the volume does not delete the data in my example, because it is now in the working directory where teedy.yml is.

Furthermore I have linked the database differently to each other

**Comment by jendib** [comment]
Trust me, without volume data won't be kept.

**Comment by Aruscha** [comment]
oh now I see it's true, I accidentally didn't copy the volume I thought you meant the other volume which is normally included in such a thing,

Sorry, everything else is going very well now

**Comment by robov** [comment]
Sorry about pasting without identation.. at least we have a working docker-container.yml now
(although uploading does not work for me but that is another issue)

**Comment by robov** [comment]
@Aruscha awesome ! thanks... however there is a misconfiguration in your docker (db=teedy_password)
and you are storing the data relative to the docker-compose directory (might be intentional)
This is mine now... all working (including uploading)

`version: "3"

services:
  teedy_db:
    image: postgres:alpine
    container_name: teedy_db
    environment:
      POSTGRES_DB: teedy
      POSTGRES_USER: teedy_user
      POSTGRES_PASSWORD: teedy_password

  teedy:
    image: sismics/docs
    container_name: teedy
    restart: always
    user: root
    ports:
      - "8222:8080"
    environment:
      DATABASE_USER: "teedy_user"
      DATABASE_PASSWORD: "teedy_password"
      DATABASE_DB: "teedy"
      DATABASE_HOST: "teedy_db"
    volumes:
      - /teedy/docs:/data`

**Comment by Aruscha** [comment]
Did you manage to add the "import" to the compose file?

**Comment by robov** [comment]
Not yet... open to suggestions ..

**Comment by robov** [comment]
getting close: https://github.com/sismics/docs/issues/436

**Comment by maspiter** [comment]
https://github.com/maspiter/teedy
