### ISSUE TITLE
Error trying to build for Docker

### ISSUE THREAD

**Issue by webmin88** [sismics/docs#431]
Hi there,

Whenever I try to build docs for docker, I get the following output:

Sending build context to Docker daemon  35.83MB
Step 1/6 : FROM sismics/ubuntu-jetty:9.4.12
 ---> f2007575e1ab
Step 2/6 : MAINTAINER b.gamard@sismics.com
 ---> Using cache
 ---> 9c88e6aede66
Step 3/6 : RUN apt-get update && apt-get -y -q install ffmpeg mediainfo tesseract-ocr tesseract-ocr-fra tesseract-ocr-ita tesseract-ocr-kor tesseract-ocr-rus tesseract-ocr-ukr tesseract-ocr-spa tesseract-ocr-ara tesseract-ocr-hin tesseract-ocr-deu tesseract-ocr-pol tesseract-ocr-jpn tesseract-ocr-por tesseract-ocr-tha tesseract-ocr-jpn tesseract-ocr-chi-sim tesseract-ocr-chi-tra tesseract-ocr-nld tesseract-ocr-tur tesseract-ocr-heb tesseract-ocr-hun &&     apt-get clean && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> f4745566167f
Step 4/6 : RUN rm -f /opt/jetty/lib/mail/javax.mail.glassfish-*.jar
 ---> Using cache
 ---> d63020222a1c
Step 5/6 : ADD docs.xml /opt/jetty/webapps/docs.xml
 ---> Using cache
 ---> 1655bfede3aa
Step 6/6 : ADD docs-web/target/docs-web-*.war /opt/jetty/webapps/docs.war
ADD failed: no source files were specified

I've checked docs-web and there's nothing like docs-web/target/docs-web-

mnt  c  …  Documents  Code  docs   v1.8  ERROR  $    ls docs-web
pom.xml  src

Is there something I am missing? I'd appreciate any help anyone can offer.

Thanks

**Comment by jendib** [comment]
You need to build the project before creating the Docker image, please see the README.md
