### ISSUE TITLE
Exception on scanning document

### ISSUE THREAD

**Issue by robov** [sismics/docs#433]
When I upload a file , uploading looks ok, BUT i cannot open the file (file not found)
and after I attach it to a document I get an exception
The value is the content from the document (some xerox pdf i downloaded) 

7/23/20 4:30 PM | RequestContextFilter | An exception occured, rolling back current transaction
-- | -- | --
7/23/20 4:30 PM | SqlExceptionHelper | Bad value for type long : Xerox SMARTsend 3.0 Brochure Xerox® SMARTsend® 3.0 Scanning made fast and secure 2 Use the power of scanning to transform the way you work. It’s possible with SMARTsend® software

**Comment by robov** [comment]
Apparently the file IS uploaded and created on my shared volume
![image](https://user-images.githubusercontent.com/8173436/88300905-4fc38b80-cd04-11ea-824a-3470c3a01a99.png)

**Comment by robov** [comment]
the 694994 corresponds with the actual pdf file size

**Comment by jendib** [comment]
Can you send me the PDF file at b.gamard@sismics.com please?

**Comment by robov** [comment]
Sure I can send the document, but that is not the issue, so you would be looking in the wrong direction I guess. Because I tested 2 documents on your hosted demo and they both work find, and both document have this error on my local version

**Comment by robov** [comment]
Solved, related to : https://github.com/sismics/docs/issues/430
It seems when I add the user root to the docker, then it does work

**Comment by robov** [comment]
Maybe it is better to create a new user instead of root to use the container internally ?
