### ISSUE TITLE
Auto Tag adding on Importer

### ISSUE THREAD

**Issue by robov** [sismics/docs#437]
How can I automatically add specific tags to imported files. 
Preferably on folder stucture, so that
|- books
    |- fantasy
       |- 2020
           harry.pdf

So that when I import harry.pdf, it automatically creates the missing tags (books, fantasy, 2020), in that hierarchy if they are not existing and adds those tags to harry.pdf

Next best thing is to add those tags to harry if the tags exist.

Please assist how to do this

**Comment by jendib** [comment]
there is no way to do this with the importer currently

**Comment by robov** [comment]
Ok, thanks for the clarification
