### ISSUE TITLE
How to migrate from embedded H2 to PostgreSQL using Docker-Compose?

### ISSUE THREAD

**Issue by shearesss** [sismics/docs#439]
Hi!

Is there any way to migrate from a running installation of teedy with H2 to PostgreSQL? We're experiencing some performance issues that I think might be easily solved with PostgreSQL

**Comment by vmario89** [comment]
voila -> https://wiki.fablabchemnitz.de/display/FCT/Teedy+1.8+Migration+from+H2+to+PostgreSQL

**Comment by shearesss** [comment]
Hi, just wondering, but is the link broken?

**Comment by vmario89** [comment]
Hey. Sorry for late reply. No it was just updated. You can find it at https://wiki.fablabchemnitz.de/display/TEED/Teedy+1.9+Migration+from+H2+to+PostgreSQL

regards and happy new year, Mario
