### ISSUE TITLE
Option to encrypt / not encrypt files

### ISSUE THREAD

**Issue by zombefy** [sismics/docs#446]
Is there an option not to encrypt uploaded/imported files? If not, is it viable to provide this as an option during initial configuration for example? I have a personal use case within a docker container on a trusted local host and would like the simplicity and assurance that my original files are always readable.

**Comment by jendib** [comment]
There is currently no option, it's all encrypted by default.

**Comment by nixn** [comment]
I wanted this too and wrote a patch (PR #495).
