### ISSUE TITLE
Why L1 cache is disabled?

### ISSUE THREAD

**Issue by Nufirdy** [sismics/docs#448]
Hey, I've been looking through code for your project and stumbled upon [this file](https://github.com/sismics/docs/blob/master/docs-core/src/main/java/com/sismics/util/context/ThreadLocalContext.java). To be more specific what I find interesting are these lines
```
if (entityManager != null && entityManager.isOpen()) {
            // This disables the L1 cache
            entityManager.flush();
            entityManager.clear();
        }
```
I'm not very experienced developer and can't understand what could be benefits of disabling L1 cache in JPA. What I see is that it can severly limit ability to modify entities.
Could you please explain what was design choice for this decision?

**Comment by jendib** [comment]
Updates are done as much as possible using native queries. We try to avoid Hibernate automagic behaviors, which are very often non predictable and leading to strange errors.
That being said, some entities are still modified using JPA.
