### ISSUE TITLE
Greek Translation

### ISSUE THREAD

**Issue by gdepountis** [sismics/docs#455]
I can help if I have the english stings file.

**Comment by jendib** [comment]
It's all there : https://github.com/sismics/docs/blob/master/docs-web/src/main/webapp/src/locale/en.json

**Comment by gdepountis** [comment]
Is ready and you can use it if you like. Could you please advise how I insert it?
[gr.txt](https://github.com/sismics/docs/files/5363893/gr.txt)

**Comment by jendib** [comment]
I committed your translation, however I'm using "angular-timeago" to display dates, and they don't have a greek translation apparently.
If you want, you can provide one based on https://github.com/yaru22/angular-timeago/blob/master/src/languages/time-ago-language-en_US.js and I will integrate it.

**Comment by gdepountis** [comment]
'use strict';

angular.module('yaru22.angular-timeago').config(function(timeAgoSettings) {
  timeAgoSettings.strings['en_US'] = {
    prefixAgo: null,
    prefixFromNow: null,
    suffixAgo: 'πριν',
    suffixFromNow: 'από τώρα',
    seconds: 'λιγότερο από ένα λεπτό',
    minute: 'περίπου ένα λεπτό',
    minutes: '%d λεπτά',
    hour: 'περίπου μια ώρα',
    hours: 'περίπου %d ώρες',
    day: 'μια μέρα',
    days: '%d μέρες',
    month: 'περίπου ένα μήνα',
    months: '%d μήνες',
    year: 'περίπου ένα χρόνο',
    years: '%d χρόνια',
    numbers: []
  };
});

**Comment by jendib** [comment]
It's done, thanks for your contribution! 👍
