### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Pyr0x1** [sismics/docs#456]
Hi, if it can be of any use I can provide an italian tranlsation. Is it enough to create a new file under https://github.com/sismics/docs/blob/master/docs-web/src/main/webapp/src/locale ?

**Comment by jendib** [comment]
There is a few more things to do, but you can simply do the translation from https://github.com/sismics/docs/blob/master/docs-web/src/main/webapp/src/locale/en.json and I will make sure to insert it (and credit you).

**Comment by jendib** [comment]
Handled by #465
