### ISSUE TITLE
API usage - update document deletes data

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#457]
Hi,

i recently made some script to iterate over all documents to add some metadata from a csv file. After running i recognized a big issue: relations, tags, description were deleted and creation_date was set to the timestamp of performing.

```
while IFS=, read -r DOC_ID METAID_DATA
do
#some static definitions
#curl --silent -X GET -H "Cookie: auth_token=$AUTH_TOKEN" "$BASE_URL/api/metadata" -k #at first we need to find out the correct metaid of the metadata we want to set
METAID_ID="66b76b61-f8ff-4306-8325-ef5af250cb62"
 
#we must get the document name (title) because updating metadata also requires to set a title (even if it does not change). We can use the static doc title of csv file or we can get the recent one by calling API
DOC_NAME=$(curl --silent -k -X GET -H "Cookie: auth_token=$AUTH_TOKEN" "$BASE_URL/api/document/$DOC_ID" | jq '.|{title}|.[]')
DOC_NAME=$(echo ${DOC_NAME:1:-1}) #cut off "" from beginning and end
echo "$DOC_ID|$METAID_DATA ($DOC_NAME)"
curl -k -X POST -H "Cookie: auth_token=$AUTH_TOKEN" "$BASE_URL/api/document/$DOC_ID" -d "title=$DOC_NAME" -d "language=deu" -d "metadata_id=$METAID_ID" -d "metadata_value=$METAID_DATA"
done < metadata.csv
```
i had to repair this using a backup dump. 

is there any chance to update a document by API more convenient way? How to use the update document call for updating only some of the specifications instead the whole document? How to deal if i really only want to change something like metadata or title?

At the moment if i want to fix my script i have had to read all the static data i dont want to change and pass this data with the update statement too to keep it. I think thats not the intended way to work. 

Maybe i did something wrong. Happy to get some idea, tip, feedback.

kind regards, Mario

**Comment by vmario89** [comment]
edit: for understanding: the meta field i wanted to update is just named "id" because i added a short integer number for all documents because i want to use this integer to embed into a datamatrix barcode. The internally used UUID are just too long to work with for my specific case.

**Comment by jendib** [comment]
It is indeed working as intended, the API requires you to send all metadata. The reason why is to be able to empty metadata values, otherwise it would not be possible.

**Comment by vmario89** [comment]
hi @jendib,
that makes sense! Thanks for the explanation. I will try to fix my script or find some quicker psql alternative. Maybe i can do some modifications the same way by updating t_document and the other tables connected together
