### ISSUE TITLE
No content after upgrade from 1.8 to 1.9-snapshot (master)

### ISSUE THREAD

**Issue by terba** [sismics/docs#464]
I built the current master for a new installation as I needed the LDAP authentication. It works fine.
Later on I upgraded from 1.8 an other install with the same 1.9-snapshot.war and everything works, the database was updated, no errors in the logs, but viewing a file's content show only a number like ```25562```.

Creating a new document on this upgraded install works fine. Reprocessing an old one also creates the content.
Is there a way to repair this? I don't want to reOCR all the files I have. Reindexing makes the lucene folder much smaller.

Running on Tomcat 9, Java 11 and PostgreSQL 11.9

Thanks in advance!

**Comment by terba** [comment]
I restored the lucene content from backup, but it doesn't get used by Teedy, full text searches are not working, and ```/api/file/:id/data?size=content``` shows just a number.

**Comment by terba** [comment]
Sorry, I was wrong, the full text searches are working after a lucene folder restore from backup, but the content is not shown. Reindexing clears the lucene database, so no searches are working after a reindex without reprocessing the files.

**Comment by jendib** [comment]
Are you using PostgreSQL ? It may be related to #451
