### ISSUE TITLE
v1.8 docker displaying empty web page

### ISSUE THREAD

**Issue by maspiter** [sismics/docs#468]
Trying out the v1.8 docker image but the web page renders empty with the following error:

Uncaught Error: [$injector:modulerr] Failed to instantiate module docs due to:
[$injector:modulerr] Failed to instantiate module yaru22.angular-timeago due to:
[$injector:unpr] Unknown provider: a
http://errors.angularjs.org/1.6.6/$injector/unpr?p0=a

**Comment by jendib** [comment]
Which Docker image exactly? This is a duplicate of #460 but it only exists for the current dev branch.

**Comment by maspiter** [comment]
sismics/docs:latest and sismics/docs:v1.8 and sismics/docs:sismics_prod

jdreinhardt/teedy:latest is working OK

**Comment by jendib** [comment]
I cannot reproduce the issue on Chrome or Firefox.
