### ISSUE TITLE
OCR takes too long and too resource consumptive. 

### ISSUE THREAD

**Issue by Jamie96ITS** [sismics/docs#470]
Hello. I'm trying to understand what may be going wrong with my Teedy install that OCR is tying up the CPU in perpetuity to OCR a document. 

I have 1 document, uploaded via the web, that is been using multiple threads, and 100% CPU usage of my host NUC, to OCR for the last 10 minutes, and it is still not complete. 

No errors noticed in the logs, just 

10/24/20 2:00 PM | PdfFormatHandler | OCR page 1/4 of PDF file containing only images

which looks to me like it hasn't even finished the first page. That same document, fed to an OCRmyPDF container, takes 45 seconds to fully process with that tool, even while the system is tied up with teedy.

**Comment by jendib** [comment]
OCR is done with https://github.com/tesseract-ocr/tesseract so I guess I cannot do anything about it  unless you can find if it comes from somewhere else.

**Comment by Jamie96ITS** [comment]
Alright.  I checked the logs again. It is taking up to 10 minutes per page to OCR.


>10/24/20 2:32 PM | FileProcessingAsyncListener | File content extracted in 1,924,923ms
>10/24/20 2:30 PM | PdfFormatHandler | OCR page 4/4 of PDF file containing only images
>10/24/20 2:21 PM | PdfFormatHandler | OCR page 3/4 of PDF file containing only images
>10/24/20 2:10 PM | PdfFormatHandler | OCR page 2/4 of PDF file containing only images
>10/24/20 2:00 PM | PdfFormatHandler | OCR page 1/4 of PDF file containing only images


It did eventually successfully complete, so it's not terribly broken. And, in actuality, the trade off may be worth it. The results from Teedy seem to be a bit more accurate but also a lot better formatted. I've gotten used to a certain standard of OCR between paperport and ocrmypdf, the results from Teedy are better than I thought possible. 

I'm just going to have to try not to think too hard about my power bill and wear and tear from running 100% CPU 10 minutes per page. Maybe it's time to rent a VPS....

**Comment by jendib** [comment]
Teedy is upscaling, greyscaling, and straightening the images before sending them to Tesseract, that's why the result is as good as possible. Also it's using Tesseract 4 with a neural net.
