### ISSUE TITLE
Importer not using filename #tags

### ISSUE THREAD

**Issue by Jamie96ITS** [sismics/docs#471]
I was going to make another request, but I realized a mistake. Apparently the importer does not use #tags in the filename?

**Comment by Jamie96ITS** [comment]
I get it now, silly me. That's not ready yet.

**Comment by Cornelicorn** [comment]
You can already use that feature if you build the importer yourself or use the docker image.
You can build it with docker:
```
docker run --rm -it \
    -v $PWD:/output \
    node:14.2-alpine \
    /bin/ash -c \
    " apk add git;
    git clone https://github.com/sismics/docs.git /docs;
    cd /docs/docs-importer;
    npm install;
    npm install -g pkg;
    cd /output;
    pkg /docs/docs-importer
    "
```
