### ISSUE TITLE
Tag synonyms and icons

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#473]
Hi,
some idea i had a long time ago was to be able to enter synonyms to already defined tags to a document by different words but with same sense. For example lets say we have a tag "power" but we want to find a document with the word "energy". We could map "energy" to "power". So we could find that document by "power" and/or "energy".

same could be also used to add tag translations. So i could filter the document by "power" or "Kraft" (german) or "Energie" (german too) for example.

another idea was to add some small icon to a tag for better visualization

**Comment by jendib** [comment]
It feels a bit too complicated to fill a very niche use case. I don't really see myself using this. Using multiple tags or putting 2 words in the same tag should be enough in most cases.
