### ISSUE TITLE
Enhancement: Support REMOTE_USER header for SSO

### ISSUE THREAD

**Issue by shamoon** [sismics/docs#475]
Thank you for this awesome project.

I currently have Teedy (and all my apps) behind the excellent [Authelia](https://github.com/clems4ever/authelia) for SSO. Both that and Teedy are hooked up to LDAP so the users are the same but if Teedy supported the `REMOTE_USER` this would allow the user to 'automatically' login.

Thanks for considering!

**Comment by jendib** [comment]
It's supported: https://github.com/sismics/docs/blob/master/docs-web-common/src/main/java/com/sismics/util/filter/HeaderBasedSecurityFilter.java
but undocumented. You need to add a `-Ddocs.header_authentication=true` to the Java command line, and the header is called `X-Authenticated-User`.

**Comment by shamoon** [comment]
Cheers @jendib is it possible to pass that command to Java if Im running within Docker?

**Comment by shamoon** [comment]
Maybe `JAVA_OPTIONS`? e.g. `JAVA_OPTIONS=-Ddocs.header_authentication=true -Xmx512m`

**Comment by jendib** [comment]
It should work yes. The default value is `-Xmx1g` as you can see in the project's Dockerfile

**Comment by shamoon** [comment]
Hmm, appreciate the help but still no dice. Im not sure how I can really test/debug this...

**Comment by shamoon** [comment]
I think the issue is Authelia uses `REMOTE_USER` and my reverse proxy (Traefik) doesnt do header transformation (yet). I know its a long shot but any chance we could allow setting the header as a config option? For example, [Guacamole does this](http://guacamole.apache.org/doc/gug/header-auth.html#guac-header-config). e.g. `System.getProperty("docs.header_authentication.user_header")` ?
