### ISSUE TITLE
Proxy Header Authentication

### ISSUE THREAD

**Issue by Typhonragewind** [sismics/docs#479]
Hello!

I couldn't find it in the documentation, but I wanted to make sure whether this would be possible or not.

Is it possible to use a reverse proxy that includes a Remote-User header (or similar) to automatically authenticate the correct user in Teedy?

For example, i defer all the authentication for my exposed services through a nginx reverse proxy behind Authelia, and in many cases i can set this header to authenticate automatically (such as in Calibre-Web or Organizr)

**Comment by jendib** [comment]
Please see #475
