### ISSUE TITLE
Trying to add tags or documents via API and am receiving HTTP 500 errors

### ISSUE THREAD

**Issue by paradizelost** [sismics/docs#480]
I am able to successfully upload a file and pull lists of documents/files/tags, but no matter what method i'm trying i'm getting a 500 server error, so i'm guessing i'm just missing something, but no matter how i try i cannot get it to add a doc or tag. i've tried on the public demo site and my own.
here's the commands i've tried in powershell

Here's the code. tried pasting it but it got mangled.
https://github.com/paradizelost/Powershell-Public/blob/master/teedy.ps1

**Comment by jendib** [comment]
If you have a error 500 you should have an error in your server logs

**Comment by paradizelost** [comment]
Ok, looks like i was just missing setting it to urlencode contenttype.
https://github.com/paradizelost/Powershell-Public/blob/master/teedy.ps1
This now has working code to create a doc and create a tag via the api in powershell.

**Comment by paradizelost** [comment]
Didn't realize i could close it, should have done so with my previous comment.
