### ISSUE TITLE
Descriptive image tags on Docker Hub

### ISSUE THREAD

**Issue by zbig-t** [sismics/docs#483]
First of all, thank you for all the good work on this great product.

I'm self-hosting my Teedy instance on Docker and have rather hard time telling which image is the latest stable release going just by the automated image tags on the Docker Hub. Would be great to have some more  descriptive tags that clearly indicate that and differentiate between automated builds and official releases.

**Comment by jendib** [comment]
It's written here : https://github.com/sismics/docs#install-with-docker
- Master branch, can be unstable. Not recommended for production use: sismics/docs:latest
- Latest stable version: sismics/docs:v1.8
