### ISSUE TITLE
Unable to locate Android application

### ISSUE THREAD

**Issue by paradizelost** [sismics/docs#485]
The documentation mentions an Android application I'm unable to find it can the documentation be updated with a link to said application?

**Comment by vmario89** [comment]
hey, you will need to compile it yourself. The app code is inside this github repository

i did a compile some months ago. you can check out https://cloud.stadtfabrikanten.org/d/b7fe5e83324f4d51ba4c/?p=%2FSismics%20Docs%20Teedy%2FAndroid%20App%20APK&mode=list

building yourself see https://wiki.fablabchemnitz.de/display/TEED/Teedy+1.9+App+for+Android for example

**Comment by paradizelost** [comment]
Thanks, was hoping it was something just available from the app store.  Thanks for the info!
