### ISSUE TITLE
Upgrade bcrypt library

### ISSUE THREAD

**Issue by Vec7or** [sismics/docs#488]
Is there a reason why a specific version prefix of bcrypt, namely `$2a$` is necessary for `DOCS_ADMIN_PASSWORD_INIT`?

**Comment by jendib** [comment]
we are using mindrot.jbcrypt as a library to handle this, the answer should be somewhere in it

**Comment by Vec7or** [comment]
The problem seems to be that the [library](https://www.mindrot.org/projects/jBCrypt/) has been last updated in 2015 and therefore does not know of the new versions (the maven package was last updated in 2017). 

I would propose to replace this component since it is safety relevant and will not receive updates anytime soon.
Alternatives may be: 
* Java Spring security [bcrypt](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/bcrypt/BCrypt.html) (Might be difficult to implement since only bcrypt is needed.)
* Standalone [bcrypt](https://github.com/patrickfav/bcrypt)

What do you think? In general it should not be a big adjustment since the library is only used inside `UserDao.java`.

**Comment by jendib** [comment]
Sound good, I like the standalone library. It should be an easy swap, we just need to make sure the old password are still ok with the new lib.

**Comment by Vec7or** [comment]
I added the needed changes to my pull request. I have tested it locally and can confirm that it works with the old passwords. But please run all tests on your machine and cross check with me, since i have only tested this with one instance. The application can now also handle the `y` and `b` version of bcrypt hashes.

Additionally following questions have popped up during development:
1. For the bcrypt work-factor I have chosen `10` since this was the value written into the database. Do you think we should adjust this?
2. During the build process I had to add grunt to my `$PATH`, I think this should be adjusted so that grunt is either linked or directly taken from the `node_modules` directory?
3. There are many old versions within the npm-dependencies, should i create a new issue in order to address this problem?

**Comment by jendib** [comment]
1. I think 10 is a good middle ground between security and performance, but I'm no expert
2. Grunt is indeed expected, not sure if that should be changed or not
3. Those old version are actually only for building, actual JS libraries are committed in https://github.com/sismics/docs/tree/master/docs-web/src/main/webapp/src/lib so as long as the build process works there is no security incentive to upgrade package.json

**Comment by Vec7or** [comment]
1. Well it is a difficult topic not even [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#work-factors) wants to define a number. Since the work-factor is heavily dependent on the machine the application runs on maybe we could set `10` as default and then create a environment variable like `DOCS_BCRYPT_WORK`?
2. `grunt` is being installed as npm dependency therefore I think it would be easier to just take that version directly.
3. Oh ok. Then it is merely a suggestion in order to keep the dependencies clean. But if `2.` should take the npm installed `grunt` then there would be a incentive to at least upgrade that dependency.
