### ISSUE TITLE
Steps for migrating Teedy from embedded H2 to PostgreSQL

### ISSUE THREAD

**Issue by shearesss** [sismics/docs#492]
Hi!

Is there any way to migrate from a running installation of teedy with H2 to PostgreSQL? I previously posted about this, and received a link to documentation for Teedy on Atlassian, but that link appears to have expired!

https://github.com/sismics/docs/issues/439#issuecomment-671488798

**Comment by jendib** [comment]
The link was fixed in the other issue. Closing.
