### ISSUE TITLE
Make it possible to turn off full-text search

### ISSUE THREAD

**Issue by shearesss** [sismics/docs#493]
Certain applications don't need full-text search, and it may slow Teedy down when using full-text search on very large documents (>100 page word docs/pdfs). Could we maybe make full-text search optional?

**Comment by vmario89** [comment]
Hi. I am running Teedy for ~1.5 years now on regular computers and servers (different instances). Have instances with thousands of documents and files. Teedy is still really quick. Never had to wait for a search result for longer time than maybe 3 seconds. 

But indeed a way to select the desired standard search type in the instance options could help maybe (some commits ago regular search was default. to search for full-text it was required to type "full:"). To search in titles only use "simple:" in the search field

**Comment by jendib** [comment]
Indeed there is no need to disable it. If you have specific performance problems please open an issue with details.
