### ISSUE TITLE
Deploying .war file Browser said HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by vijendraj** [sismics/docs#500]
Hi, I am trying to install teedy in ubuntu 18.04.
When I try to deploy .war file its deployed, But when opening link /docs-web-1.8 its giving me error like this 
HTTP Status 404 – Not Found
Type Status Report

Message The requested resource [/docs-web-1.8/] is not available

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.41

**Comment by vmario89** [comment]
hi, what's the file name of your .war archive? if it is named "docs.war" you can access it via /docs. So your war should be named "docs-web-1.8.war" in your case.

Additionally maybe check the file permissions and ownerships of the war file. Target file path is /usr/share/jetty9/webapps/
Please also have a look in jetty log using "journalctl -u jetty"

it could also be you have a file called "/var/lib/jetty9/webapps/dms.xml" which contains another contextPath than usual?

**Comment by vijendraj** [comment]
> hi, what's the file name of your .war archive? if it is named "docs.war" you can access it via /docs. So your war should be named "docs-web-1.8.war" in your case.
> 
> Additionally maybe check the file permissions and ownerships of the war file. Target file path is /usr/share/jetty9/webapps/
> Please also have a look in jetty log using "journalctl -u jetty"
> 
> it could also be you have a file called "/var/lib/jetty9/webapps/dms.xml" which contains another contextPath than usual?

**Comment by vijendraj** [comment]
Hi, I am running with tomcat9 
![image](https://user-images.githubusercontent.com/77285827/104302635-099af800-54ef-11eb-8aa1-e85bc626c1fd.png)
When I click on /docs-web-1.9-SNAPSHOT
Its gives error 
HTTP Status 404 – Not Found
Type Status Report

Message The requested resource [/docs-web-1.9-SNAPSHOT/] is not available

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.41

checked with full permission

**Comment by vmario89** [comment]
does your system allow the jetty service to write files into directoy /var/docs?

on some systems using systemd the  /lib/systemd/system/jetty9.service has to be adjusted. Might be the case you need to add ReadWritePaths=/var/docs - if not set that might prohibit to correctly run the war file

**Comment by vijendraj** [comment]
> etty service to write files into directoy /var/docs?

I am not using jetty i am using tomcat 9

**Comment by vmario89** [comment]
woops sorry. :-O But might be same issue for tomcat belonging to write permissions using systemd tomcat.service

**Comment by vijendraj** [comment]
> woops sorry. :-O But might be same issue for tomcat belonging to write permissions using systemd tomcat.service

Can you please help me with installation teddy with tomcat or jetty.
No issue in creating .war file or any build steps.
Help me if you have documents for setup with tomcat or jetty.

**Comment by vmario89** [comment]
Hi,
you can check out my docs at:

- https://wiki.fablabchemnitz.de/display/TEED/Teedy+1.9+Tomcat+9
- https://wiki.fablabchemnitz.de/display/TEED/Teedy+1.9+Environment+Configuration
- https://wiki.fablabchemnitz.de/display/TEED/Teedy+1.9+Build+web+application+server+from+Source
- https://wiki.fablabchemnitz.de/display/TEED/Teedy+1.9+Basic+installation+with+Jetty+and+H2+Database
and other sub pages from there

regards, Mario :-)
