### ISSUE TITLE
Is OCR with Tesseract in some way dependent on the primary metadata language input field?

### ISSUE THREAD

**Issue by vegardhw** [sismics/docs#501]
It seems like I can get proper search results for Norwegian text in pdfs with "full:" but will the search quality be even better with a potential Norwegian metadata label?

**Comment by jendib** [comment]
Yes, the language of the document is passed to Tesseract which takes advantage of it to refine character recognition.

**Comment by vegardhw** [comment]
Ok - What are the chances of adding Norwegian language support? :)

**Comment by jendib** [comment]
You can provide a PR based on this one: https://github.com/sismics/docs/pull/438

**Comment by vegardhw** [comment]
Done :)
