### ISSUE TITLE
Subject based mail filtering

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#508]
HI,
just stumbled upon some fork of Teedy which seems to contain subject based mail filtering:
https://github.com/gaurav21/docs/commit/73ece52c972fa041de1a08859e2b64d42b37bb25
maybe this could be some useful addition to Teedy

regards, Mario

**Comment by jendib** [comment]
The implementation in this fork is very specific to what they want to achieve. It would need to be reworked to be integrated.
