### ISSUE TITLE
Need all Steps for install in ubuntu 18

### ISSUE THREAD

**Issue by vijendraj** [sismics/docs#512]
Hi Team,

Can you please share me all installation steps for teddy.

I tried my self but not able to take dms.war on localhost:8080

**Comment by vmario89** [comment]
hey,
made this documentation some time ago and working on from time to time.
https://wiki.fablabchemnitz.de/display/TEED/Teedy+1.9+Build+web+application+server+from+Source

**Comment by vijendraj** [comment]
Hi 
After i successfully done all steps but after installed when I try to check localhost:8080 got only this
![image](https://user-images.githubusercontent.com/77285827/105671784-49a7a500-5f09-11eb-9a7b-bb76c37b6b70.png)

**Comment by vmario89** [comment]
hey, you will need to access another context path which is localhost:8080/docs-web-19-SNAPSHOT, not localhost:8080 - this is the jetty default context path. Check the name of your .war file and append it to the url but without .war ending. You should have put it in /var/lib/jetty9/webapps

**Comment by vijendraj** [comment]
done as same 
still error 
![image](https://user-images.githubusercontent.com/77285827/105712931-85119600-5f40-11eb-9063-a53dfcfd3b57.png)

**Comment by fototeddy** [comment]
i have placed my .war as 'docs.war' in '/usr/local/jetty/webapps'
also I have placed a docs.xml in the same directory with the following content

```<Configure class="org.eclipse.jetty.webapp.WebAppContext">                                                                                       
                                                                                                                                                 
  <Set name="contextPath">/</Set>                                                                                                                
                                                                                                                                                 
  <Set name="war"><SystemProperty name="jetty.data" default=""/>/usr/local/jetty/webapps/docs.war</Set>                                                                                                                                                                                           
                                                                                                                                                 
                                                                                                                                                 
  <Call class="java.lang.System" name="setProperty">                                                                                             
                                                                                                                                                     <Arg>docs.home</Arg>                                                                                                                         
                                                                                                                                                 
    <Arg>/data</Arg>                                                                                                                             
                                                                                                                                                 
  </Call>                                                                                                                                        
                                                                                                                                                 
</Configure> 
```

i have I running in a FreeNAS jail an also had to manipulate some lib because system an jetty version hast different lib versions but that was readable I the error log

**Comment by fototeddy** [comment]
> is there anything visible in /var/docs/logs or some timestamp where you can see last write access?
> Did you properly configure the systemd service to allow write permission to /var/docs?
> 
> What size does your war file have? Maybe it is corrupt and is not recognized by jetty. If you journalctl -u jetty9.service does not say anything about dms.war then i think there's an issue with the compiled archive.
> 
> To check you can try an older version. I am uploading compiled war archives from time to time: https://cloud.stadtfabrikanten.org/d/b7fe5e83324f4d51ba4c/?p=%2FSismics%20Docs%20Teedy%2FServer%20Web%20Archive&mode=list
> 
> my log contains the following lines when starting up:
> 
> ```
> 2021-01-25 15:39:32.971:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@8c3619e{Teedy,/dms,file:///tmp/jetty-0_0_0_0-8080-dms_war-_dms-any-4166594137135316891.dir/webapp/,AVAILABLE}{./webapps/dms.war}
> 2021-01-25 15:39:33.038:INFO:oejs.AbstractConnector:main: Started ServerConnector@2563102c{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
> 2021-01-25 15:39:33.039:INFO:oejs.Server:main: Started @7875ms
> ```

thanks for the link. its great to have newer versions than 1.8 :) keep compiling ;)

**Comment by vijendraj** [comment]
Hi I have check with .war which sent by you but still same 
![image](https://user-images.githubusercontent.com/77285827/106245083-e7fd7880-6231-11eb-9fa4-c5afa9ed3fd7.png)

**Comment by fototeddy** [comment]
Try to Place a docs.xml in addition

**Comment by vijendraj** [comment]
![image](https://user-images.githubusercontent.com/77285827/106249748-c358cf00-6238-11eb-89ba-52c55f46a4aa.png)

**Comment by fototeddy** [comment]
Xml and war needs to be both in the folder where jetty tries to load the webapps 
/opt/teedy seems Not to be the right place

**Comment by vijendraj** [comment]
Done installation too many times but can't find solution for this 
please help me to figure out this.

**Comment by vmario89** [comment]
docs.xml is only required if you change the default path of your data folder which is usually /var/docs. If you did not change just remove the xml file for beginning; the war file has to be put in /var/lib/jetty9/webapps

i used /opt/teedy to clone and compile teedy but not to run from.
maybe try to run on another machine ot check if something is wrong with your OS environment.

i have no clue about docker but you could try to use the docker variant of teedy

**Comment by vijendraj** [comment]
Do you have steps to install with tomcat9 ?

**Comment by vmario89** [comment]
yes/no. I tried this once and put some basic steps at https://fablabchemnitz.de/display/TEED/Teedy+1.9+Tomcat+9. But i cannot gurantee that it will work or if it is secure

**Comment by vijendraj** [comment]
> yes/no. I tried this once and put some basic steps at https://fablabchemnitz.de/display/TEED/Teedy+1.9+Tomcat+9. But i cannot gurantee that it will work or if it is secure

Link not opening
