### ISSUE TITLE
LDAP integration / usernames with dots

### ISSUE THREAD

**Issue by ChrisTG742** [sismics/docs#526]
We use usernames (uids) with the scheme <firstname>.<surname> in our LDAP directory.
Teedy seems to have problems with usernames that contain a dot.
Is there a solution for this problem? Renaming all users in the directory is not a solution ;-)
TIA!

**Comment by ChrisTG742** [comment]
github ate some of my text... The line should be:
"We use usernames (uids) with the scheme "firstname.surname" in our LDAP directory.

**Comment by jendib** [comment]
Did you try with Teedy 1.9 ?

**Comment by ChrisTG742** [comment]
Yes, the bug seems to happens with 1.9, too.

**Comment by timnis** [comment]
bug is also on v1.10

**Comment by jendib** [comment]
Reproducer and help needed.
