### ISSUE TITLE
Problem with docs-importer - no documents are imported

### ISSUE THREAD

**Issue by MikeDeltaHH** [sismics/docs#529]
Hello!

I have the docs-importer running as Docker - how can I read TEEDY_TAG there? When I go to http://ip:8080/api/tag/list only TAG [] is displayed - when i got to http://ip/api/tag/list only an error message is displayed (Error: Connection interrupted) the and since the import doesn't work, no files are imported, I suspect it's because I didn't pass this value as a variable.

**Comment by Cornelicorn** [comment]
You have to add the tag in the teedy instance first, then find the id at `http://<ip of teedy instance>(:<port of teedy instance>)/api/tag/list`. You can then pass this id as the env variable `TEEDY_TAG`. When you see `{"tags": []}` at `http://ip:8080/api/tag/list `, this means you have not created a tag yet.

**Comment by MikeDeltaHH** [comment]
@Cornelicorn 
Thanks for the reply... what tag do I need to add in the Teedy instance? Do I have to generate it myself or where do I get the tag? I can't find anything in the available variables...

**Comment by Cornelicorn** [comment]
`TEEDY_TAG` is not required. You can create any tag, specifying the UUID of that tag in `TEEDY_TAG` will add this tag to every document imported by the container.
The only variables needed are `TEEDY_URL`, `TEEDY_USERNAME` and `TEEDY_PASSWORD`. By default, no tag will be added to imported documents

**Comment by MikeDeltaHH** [comment]
Ok, thanks - then the problem is different.... i installed the teedy-import as docker and put some test pdf in the /import volume but nothing happens... here is the log:

eedy Importer 1.8, https://teedy.io
This program let you import files from your system to Teedy

Starting in quiet mode with the following configuration:
Base URL: http://192.168.2.120:8080
Username: Michael
Password: ***********
Tag: 
Add tags given #: false
Language: deu
Daemon mode: true
Copy folder: 
File filter: *

Polling the input folder for new files...

Is there an error in a configuration somewhere here?

**Comment by Cornelicorn** [comment]
That looks right, can you send the the docker run command (remove the password)?
And can you run `docker exec <name of docker container> cat /root/.config/preferences/com.sismics.docs.importer.pref` and post the result here (remove the password also in this output)?

**Comment by MikeDeltaHH** [comment]
Here is the output:

importer:
  daemon: true
  path: import
  tag: ''
  addtags: 'false'
  lang: deu
  baseUrl: 'http://192.168.2.120:8080'
  username: Michael
  password: MikeDelta
  copyFolder: ''
  fileFilter: '*'

**Comment by MikeDeltaHH** [comment]
@Cornelicorn 
Ok, very very strange...i don´t change anything but now it works! All my test files are imported! Thanks for your support and havr a nice weekend! :)

**Comment by Cornelicorn** [comment]
Ok, strange. My thought was that there was something wrong with the mount of /import

**Comment by Cornelicorn** [comment]
> password: xxx

Btw, you can see the history of edits on GitHub, so the password is still visible.

**Comment by MikeDeltaHH** [comment]
> 
> 
> > password: xxx
> 
> Btw, you can see the history of edits on GitHub, so the password is still visible.

Thank, will change it shortly!

**Comment by MikeDeltaHH** [comment]
Hello @Cornelicorn!

I have to reopen the case because I have the same problem again now....
I'm in the process of moving my docer containers to another host and have reinstalled docs-importer there and copied the configuration 1:1 from the old host:

Log docs-importer old host:

nvironment variables replaced
Teedy Importer 1.8, https://teedy.io
This program let you import files from your system to Teedy
Starting in quiet mode with the following configuration:
Base URL: http://192.168.2.126:8080
Username: admin
Password: ***********
Tag: 
Add tags given #: false
Language: enu
Daemon mode: true
Copy folder: 
File filter: *
Polling the input folder for new files...


Log docs-importer new host:

Username or password incorrect
Environment variables replaced
Teedy Importer 1.8, https://teedy.io
This program let you import files from your system to Teedy
Starting in quiet mode with the following configuration:
Base URL: http://192.168.2.126:8080
Username: admin
Password: ***********
Tag: 
Add tags given #: false
Language: enu
Daemon mode: true
Copy folder: 
File filter: *

In both docs-importer containers the same user is entered so I can't trace the entry with the wrong username or password and even if I store another user it doesn't work:

Environment variables replaced
Teedy Importer 1.8, https://teedy.io
This program let you import files from your system to Teedy
Starting in quiet mode with the following configuration:
Base URL: http://192.168.2.126:8080
Username: Michael
Password: ***********
Tag: 
Add tags given #: false
Language: enu
Daemon mode: true
Copy folder: 
File filter: *

The entry "Polling the input folder for new files..." is also missing here.

The import directory is located on a NAS and is connected via NFS:

showmount -e 192.168.2.100
Export list for 192.168.2.100:
/volume1/nfs-teedy-import 192.168.2.126,192.168.2.120

I have deleted and recreated containers on the new host x times now and can't find the error....

Can you help me?

Regards!
Mike

**Comment by MikeDeltaHH** [comment]
After changing TEEDY_URL from IP address to DNS name it works now...
