### ISSUE TITLE
How does encryption work?

### ISSUE THREAD

**Issue by tiuub** [sismics/docs#534]
Hello,

I have installed Teedy today and tested it out.
In the README I have noticed, that all documents are encrypted with AES. So I thought if I upload a document it will be encrypted and nobody else can read it. But after some testing, I have noticed, that I the documents, which I uploaded with my personal account, can also be read by the admin account.

So my basic question is: How does Teedy encrypt my documents? Is it based on a single user encryption, which encrypts the documents for each user individually or does it use a main key for all users? It would be awesome if you also can tell me, where the encryption keys are saved.

P.S. I'm hosting on myself.

Kind regards
tiuub

**Comment by jendib** [comment]
The encryption keys are generated for each user and are stored in the database.
