### ISSUE TITLE
Pdf : application/octet-stream vs application/pdf

### ISSUE THREAD

**Issue by nodecentral** [sismics/docs#536]
Hi

I tried to upload a pdf file, yet it didn’t render a thumbnail, so I continued on  to upload another pdf which did.
So I tried to upload the same pdf file again, and this time it worked, it gave me a thumbnail.

Upon investigation, it looks like the first pdf was uploaded as an ‘ application/octet-stream ’

Does anyone have an ideas why it would uploaded as that ? What even is an ‘ application/octet-stream ’?

FYI - Teedy is running under Docker, on a QNAP NAS with the uploads coming manually from the Apple iCloud via their an iPad and their Files app..

![533CF072-F57D-4EF3-A8D1-767F581246D1](https://user-images.githubusercontent.com/4349292/115070475-e49e9280-9eec-11eb-93e2-89fca085f4c6.jpeg)
![2CA93EF7-C4C5-4CF1-A1F3-01A7644BA56F](https://user-images.githubusercontent.com/4349292/115070635-1dd70280-9eed-11eb-96a0-1700e7da274c.jpeg)

**Comment by jendib** [comment]
Cannot reproduce.

**Comment by nodecentral** [comment]
Hi @jendib 

While I really appreciate you checking , if can’t be re-produced in your set up, does that warrant it to be marked as closed ? 

Do you have another way of categorising situations like these / perhaps as a ‘known issue’ - with currently no known root cause ?

**Comment by jendib** [comment]
Hello,
I'm not saying the issue doesn't exist, simply that if I cannot reproduce it, I cannot fix it.
If you can provide a reproduction case I will reopen this issue and check it out.
Thanks.

**Comment by nodecentral** [comment]
Thanks will do..

**Comment by archiloque** [comment]
I have hit the same issue, should I try the upload script on the demo instance to see if it happens?

**Comment by pepitoria** [comment]
this happens to me when it imports from mail inbox. it does not happen all the time, or most the time, but is not uncommon :(

If I click download it opens the pdf properly in another tab.
