### ISSUE TITLE
Unable to View Documents

### ISSUE THREAD

**Issue by nowjon** [sismics/docs#537]
Heyo, 

Appreciate any feedback, but I'm unable to view any documents in TeedyDocs. I get the below screen when I do so. 
There's also an error in the Chrome logs: "crbug/1173575, non-JS module files deprecated.
(anonymous) @ VM1715:5551"
Anyone have any ideas? 

Teedy-Docs is running in Docker and is currently on version 1.9 and I'm pulling from sismics/docs:latest

![image](https://user-images.githubusercontent.com/40905072/116461679-2bb24f00-a82e-11eb-9b62-8305b001650e.png)

**Comment by jendib** [comment]
It's working for me on Chrome at https://demo.teedy.io/ (running 1.9)
