### ISSUE TITLE
Cancelled processing due to server restart results in document thumbnails being missing

### ISSUE THREAD

**Issue by Inlustra** [sismics/docs#538]
Hi guys,

I've just moved to teedy from Mayan EDMS, to do this I did a bulk upload of all of my documents in Mayan. 
Unfortunately, while the processing queue wasn't empty, I did a container restart and unfortunately stopped the OCR processes etc.

Since then, I have actually run a reprocess on all of my documents using the API.
Code to do that, if anyone is interested:
https://gist.github.com/Inlustra/e7244142720c3590a82e909c34fa2594

But unfortunately, I'm left with the following:
![Screenshot 2021-05-19 113202](https://user-images.githubusercontent.com/2565465/118790249-de0d8d00-b895-11eb-99de-beffb8f34f39.png)

As you can see, the document thumbnails are missing, but the file thumbnails have been generated.
How can I reprocess the document?

Thanks!

**Comment by Inlustra** [comment]
I can also confirm that this is not a cache issue, this is happening on multiple devices

**Comment by jendib** [comment]
Any error in log when you reprocess? It should recreate the thumbnails as well as OCR those files.

**Comment by Inlustra** [comment]
None!
```


<!--StartFragment-->
1/5/27 12:45 PM | FileUtil | Processing ended for file: 9d974b0d-8a17-4de4-bfea-9f22c9d47d51
-- | -- | --
21/5/27 12:45 PM | FileProcessingAsyncListener | File content extracted in 3,737ms: 9d974b0d-8a17-4de4-bfea-9f22c9d47d51
21/5/27 12:45 PM | PdfFormatHandler | OCR page 1/1 of PDF file containing only images
21/5/27 12:45 PM | FileProcessingAsyncListener | Start extracting content from: File{id=9d974b0d-8a17-4de4-bfea-9f22c9d47d51, name=seolis contract.pdf}
21/5/27 12:45 PM | ClasspathScanner | Found 7 classes for FormatHandler
21/5/27 12:45 PM | FileProcessingAsyncListener | File updated event: FileUpdatedAsyncEvent{fileId=9d974b0d-8a17-4de4-bfea-9f22c9d47d51, language=eng}
21/5/27 12:45 PM | FileUtil | Processing started for file: 9d974b0d-8a17-4de4-bfea-9f22c9d47d51

<!--EndFragment-->

```

The file thumbnail gets created just fine, it's the document thumbnail that doesn't

**Comment by jendib** [comment]
Ok I see. It seems that the reboot also interrupted `DocumentUpdatedAsyncListener` events. You can update your documents using the API to do this (just like you did the reprocessing) using this endpoint <https://demo.teedy.io/apidoc/#api-Document-PostDocument>

**Comment by Inlustra** [comment]
Great that worked thanks, should anyone be interested in the script to trigger the reprocessing of documents and files all in one:
https://gist.github.com/Inlustra/e7244142720c3590a82e909c34fa2594
