### ISSUE TITLE
Backup and Restore Utility + Evernote Import

### ISSUE THREAD

**Issue by MattHodge** [sismics/docs#545]
Hi There,

I saw there was a few requests around backup solutions (https://github.com/sismics/docs/issues/361, https://github.com/sismics/docs/issues/331, https://github.com/sismics/docs/issues/249, https://github.com/sismics/docs/issues/225). 

I wanted a solution where:

- It would be easy to find the documents I was looking for in the backup (named correctly / stored as proper files and not a database backup)
- It would be easy to import into another Teedy installation
- The data was structured so it could be loaded to or from another document management system (I wanted to migrate from Evernote to Teedy)

Below is an example file structure from a backup.

```
├── documents
│   ├── 2191bcb6-1f43-46ef-80cd-45e029a5caa8
│   │   ├── document.json
│   │   └── files
│   │       ├── 43\ -\ Originele\ factuur\ -\ 32143470674071.pdf
│   │       └── invoice_paid.jpeg
│   ├── 28fe8b75-1066-4731-9ec3-3d777a223b8d
│   │   ├── document.json
│   │   └── files
│   │       └── Please_DocuSign_MH_-_Addendum_-_Start_Date_C.pdf
└── tags
    ├── 0c1fb3bd-5032-46cb-b5ae-33bc6393cc3b
    │   └── tag.json
    └── f8e2d855-ce76-42c2-b927-dba90ef4a7b0
        └── tag.json
```

I created a Go client library for Teedy, then a CLI which used it to do the backup, restore and import from Evernote `.enex` files. 

You can run a backup like so:

```bash
# Provide username and password via environment variables
export TEEDY_USERNAME=user
export TEEDY_PASSWORD=password

teedy-cli backup --url http://source.teedy.local --destinationpath ./backup
```

More usage instructions, the CLI and the Go client library are over at https://github.com/MattHodge/go-teedy. It's currently just limited to documents, their files and tags.

Hopefully this helps some people!

**Comment by jendib** [comment]
Thanks for this tool, I'm sure it will be useful
