### ISSUE TITLE
How to setup .env ?

### ISSUE THREAD

**Issue by naufalahnaf17** [sismics/docs#546]
im not java developer but its make me frustate , how i can setup env for using postgresql ? too many folder here i know but can someone explain to me how to do it ?

**Comment by mwxxt** [comment]
+

**Comment by dumi5952** [comment]
I have the same issue here... Please Guide us to set up the DB locally

**Comment by jendib** [comment]
It's all explained here <https://github.com/sismics/docs#using-the-internal-database> with Docker Compose examples.
