### ISSUE TITLE
Default initial login

### ISSUE THREAD

**Issue by MKE1138** [sismics/docs#553]
Taken from the readme, the default admin password is "admin". But what is the username? "admin" as well?

I try that (admin | admin) and it fails.

I try (admin_mail | admin) and it fails.

I try (admin | modified pw in docker file) and it fails.

Really frustrating and confusing.

**Comment by jendib** [comment]
It should all be explained here <https://github.com/sismics/docs#install-with-docker>
If you still have an issue please provide additional details
