### ISSUE TITLE
BUG(?): Searching tags is not prefix-free

### ISSUE THREAD

**Issue by noseshimself** [sismics/docs#561]
If there are tags that have the text of another tag as as a prefix in their name as tag specific search is returning both.

Example: If there are documents assigned the tag "test" and there are documents assigned the tag "testcase" searching for

tag:test

in the document search field will return documents tagged "test" or tagged "testcase". This is definitely not a good idea.

**Comment by francois-ferrandis** [comment]
I agree that this behaviour is indeed unexpected. I would expect a tag to be an atomic entity, so a partial match feels weird.

**Comment by jendib** [comment]
I'm not sure it's a good idea to change this, it has been like this forever and users might get confused if the next version changes the behavior.
