### ISSUE TITLE
Slow search when looking for exact titles => adding a new query parameter?

### ISSUE THREAD

**Issue by archiloque** [sismics/docs#563]
We're evaluating teedy and want to use it's API to store and share files documents between applications.

It's working pretty well, except that the search seem a bit slow for our use case which is to find a document by it's title and tag.

To avoid sharing teedy's documents uids' between applications, we want to use functional identifiers to identidy them in teedy, for example a contract id.

We're on a VM with a SSD and the search takes more than one second. It would be OK for the kind of full text search provided by the GUI, but not for a much more specialized exact search.

When doing a search with some document content, the code is using Lucene indexes and try to find a match on all possible fields, and it makes sense for it to takes some time.

But in our case the title is stored in PostgreSQL, so we don't need Lucene at all.

There are already a long list of parameters in `com.sismics.docs.rest.resource.DocumentResource#parseSearchQuery`, what do you think of adding a parameter that would match the exact title and be used as a SQL query instead of Lucene (for example `exactTitle`)?

In this case the search HTTP query is less than 0.05 seconds.

As our use case doesn't seem so specific, it could probably be useful for other users.

We can create a PR for it with the code if you think it's a good idea, or maybe you'll have a better suggestion.

Thanks!

**Comment by jendib** [comment]
The way you want to do it seems OK. Please name the parameter just "title".
