### ISSUE TITLE
Add parameter to return the files when searching for a document ?

### ISSUE THREAD

**Issue by archiloque** [sismics/docs#569]
Hello,

for our use case we look for documents with their title, then look for a specific file within each of them.

It means 2 APIs call for each file we want to have access to.

What would you think of adding a parameter to the `/api/document/list` that add the list of files to the query result ? We could do the same in `/api/document/:id` for coherency even if it's not a need for us.

If you think it's a good idea I can write a PR for it as I did for https://github.com/sismics/docs/issues/563

Thanks

**Comment by archiloque** [comment]
@jendib I think the PR is ready, could you have a look at it ? I have finally enough time to upstream the few changes we did on our side

**Comment by jendib** [comment]
@archiloque It's merged and built. Would you have time to do the final test on the `sismics/docs:latest` Docker image?

**Comment by archiloque** [comment]
@jendib yes, I'll do it this week

**Comment by archiloque** [comment]
@jendib just tested the image and it works as expected, thanks ! I'll work on sending you the next PR this week.
