### ISSUE TITLE
How to remove all documents in specific tag

### ISSUE THREAD

**Issue by lbrossault** [sismics/docs#588]
Hello,

How could you remove all document belongs to specific tag in quick steps ?

REgards,

**Comment by lbrossault** [comment]
Any idea ?

I can see some information to perform this action are defined in t_documents, t_tag ... PSQL tables, but I'm not PSQL expert I'm searching solution to remove all documents with file(s) attached to them for a specific tag name.

Help me ! :)

**Comment by vmario89** [comment]
have a look at https://stadtfabrikanten.org/display/TEED/Create+new+documents+which+act+as+collectors for some doc selects with tags; you can rewrite the query to use drop

**Comment by lbrossault** [comment]
Thanks for your reply.

I'm not a SQL expert and here I need to pipe SELECT commands to:
- for specific tag name, I need to extract tag_id:
  - for select documents (today, around 500 docs) binded to this tag_id AND remove attached file(s) for document to remove
  
Any idea to concate these commands ?
