### ISSUE TITLE
Where is the database path in Windows? 

### ISSUE THREAD

**Issue by shrideh** [sismics/docs#589]
Windows 10
Tomcat 8.5
docs-web-1.9
jdk-11.0.13
Where is the database path?
I deleted a folder
C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\docs-web-1.9
To re-install it again, but the database is still there, where is its location to delete it?

**Comment by kernrot** [comment]
have a look at
`%AppData%\Sismics\Docs` or
`C:\Users\[user]\AppData\Roaming\Sismics\Docs`
