### ISSUE TITLE
Set default document permissions 

### ISSUE THREAD

**Issue by Zoraws** [sismics/docs#593]
Hey,

how do I set default permissions for documents?
Currently all uploaded files and created documents are only visible to the author and I can't find the setting to change it.
I want all my users to be able to access all already and in the future uploaded files per default.

Or is there at least a best practice or code snippet available in order to set all document permissions via the API?

Using the docker image `sismics/docs:v1.9` on Linux.

Thank you in advance!

**Comment by jendib** [comment]
You can add permissions directly on documents or through tags.
