### ISSUE TITLE
login with 2fa fails

### ISSUE THREAD

**Issue by MadZeh** [sismics/docs#603]
SInce Update on 1.10, I can't login into Teedy anymore. When asked for the 2FA-code, it takes a few seconds and than the message "Login failed. Wrong username or password" apears. The Teedy-Installation has no access to a mailserver, so a password reset isn't possible. Is there any other way to disable it? I'm running Teedy in a container.

**Comment by jendib** [comment]
could you provide the request and response headers and content of the POST /login? (F12 in your browser, XHR tab)

**Comment by MadZeh** [comment]
Common:

> Anfrage-URL: https://docs.gue*******.net/api/user/login
> Anfragemethode: POST
> Statuscode: 500 
> Remote-Adresse: 31.17.#.#:443
> Richtlinien für Verweis-URL: strict-origin-when-cross-origin

Request Header:

> :authority: docs.gue*******.net
> :method: POST
> :path: /api/user/login
> :scheme: https
> accept: application/json, text/plain, */*
> accept-encoding: gzip, deflate, br
> accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
> content-length: 61
> content-type: application/x-www-form-urlencoded;charset=UTF-8
> cookie: auth_token=bb9bf60b-41cc-4e7b-a314-f647f7013e0a
> dnt: 1
> origin: https://docs.gue*******.net
> referer: https://docs.gue*******.net/
> sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"
> sec-ch-ua-mobile: ?0
> sec-ch-ua-platform: "Windows"
> sec-fetch-dest: empty
> sec-fetch-mode: cors
> sec-fetch-site: same-origin
> user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

Response Header:

> cache-control: must-revalidate,no-cache,no-store
> content-length: 1395
> content-type: application/json
> date: Thu, 13 Jan 2022 15:04:00 GMT
> server: nginx

Answer:

> {
> "cause6":"org.h2.message.DbException: Row &quot;157&quot; not found in primary index &quot;PUBLIC.T_AUTHENTICATION_TOKEN_DATA&quot; [90143-199]",
> "cause5":"org.h2.jdbc.JdbcSQLTimeoutException: Timeout trying to lock table {0}; SQL statement:\ndelete from T_AUTHENTICATION_TOKEN AS ato  where ato.AUT_IDUSER_C = ? and ato.AUT_LONGLASTED_B = ? and ato.AUT_LASTCONNECTIONDATE_D &lt; ?  [50200-199]",
> "cause7":"org.h2.jdbc.JdbcSQLTransientException: Row &quot;157&quot; not found in primary index &quot;PUBLIC.T_AUTHENTICATION_TOKEN_DATA&quot; [90143-199]",
> "cause2":"javax.servlet.ServletException: javax.persistence.QueryTimeoutException: could not execute statement",
> "cause1":"javax.servlet.ServletException: javax.servlet.ServletException: javax.persistence.QueryTimeoutException: could not execute statement",
> "servlet":"JerseyServlet",
> "cause4":"org.hibernate.QueryTimeoutException: could not execute statement",
> "cause3":"javax.persistence.QueryTimeoutException: could not execute statement",
> "cause0":"javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.ServletException: javax.persistence.QueryTimeoutException: could not execute statement",
> "message":"javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.ServletException: javax.persistence.QueryTimeoutException: could not execute statement",
> "url":"/api/user/login",
> "status":"500"
> }

**Comment by jendib** [comment]
It seems to be the same problem as https://github.com/sismics/docs/issues/547

Maybe you didn't shutdown the app properly or something like this, but H2 seems to be very sensible to that.

Your best bet is to migrate your database to PostgreSQL as instructed in the last comment of #547.
