### ISSUE TITLE
Docker images always build as 'latest'

### ISSUE THREAD

**Issue by dschaper** [sismics/docs#607]
I'm opening this issue to track a feature I'll work on.

Currently the docker images all build as the `latest` tag. We can adjust the build process to tag the docker image with the same tag used in GitHub's Release.

Are there any other tags that should be built? We can build images for each commit to master (or other branches) or do a nightly image.

**Comment by jendib** [comment]
I think the master branch going to sismics/docs:latest (already done) and the tags going to sismics/docs:<tag> would be perfect.

For version v1.10 I pushed manually to DockerHub, so it would save me some time.

The cherry on top would be to automatically create the Github release and upload the war and importer artifacts 👍

**Comment by dschaper** [comment]
Okay, I'll work on the tagging. 

I didn't think about uploading the war but that should be doable. I was going to look at the importer as well...

**Comment by jendib** [comment]
@dschaper It doesn't seem to work for the master branch. It comes from the docker/metadata action.

The value `type=ref,event=push` was invalid so I removed it, and the doc says "latest" is done by default.

https://github.com/sismics/docs/runs/4896567833 but no tag is generated

**Comment by dschaper** [comment]
It didn't have a tag since the only `tag` attribute specified was one that would happen when you tagged a commit. Since there wasn't a new tag created, there was nothing for the metadata to tag. 

I'll have to think a bit on how to get it to always tag `latest` with every push to `master` no matter what.

**Comment by dschaper** [comment]
Latest PR should work.

Next I'll work on uploading the artifact war file to the GitHub Release.
