### ISSUE TITLE
User detail won't open if using LDAP with userPrincipalName

### ISSUE THREAD

**Issue by timnis** [sismics/docs#614]
When using LDAP with AD and search filter is set to `(&(objectClass=user)(userPrincipalName=USERNAME))` (so the username is same as email).

User can login but admin cannot open/delete user because user details won't open (circular keeps rolling)

![image](https://user-images.githubusercontent.com/31338854/151860469-6161aa49-53d9-4c41-a20b-695f22c525b0.png)

**Comment by jendib** [comment]
Please attach your server logs.

**Comment by timnis** [comment]
if you mean `docker logs` there is nothing
`2022-02-03 13:34:12.731:INFO:oejs.Server:main: Started @3854ms`

**Comment by jendib** [comment]
@timnis If it's not loading you must have an error either in the server logs or in the "Network" tab of your browser console. If you can attach this.

**Comment by timnis** [comment]
In console there is 
![image](https://user-images.githubusercontent.com/31338854/152349709-04c2dfe4-9fb6-4685-9fe9-8f2aca94943a.png)

**Comment by timnis** [comment]
I'm runnning teedy on docker behind traefik proxy it that matters

**Comment by jendib** [comment]
It should be related to the dot in the username. Duplicate of #526
