### ISSUE TITLE
Cant send Emails

### ISSUE THREAD

**Issue by niklask52t** [sismics/docs#615]
Ive setup it via docker and my Config for smtp is:
 # SMTP Settings
      DOCS_SMTP_HOSTNAME: "smtp.ionos.de"
      DOCS_SMTP_PORT: 465
      DOCS_SMTP_USERNAME: "mail@example.net"
      DOCS_SMTP_PASSWORD: "myPassword"
But i get everytime an error (see attachment) and the data is correct and working on other apps.
![152342326-54e9a406-a499-400e-adf6-d765c8cc830a](https://user-images.githubusercontent.com/50155520/152342421-2d218ec4-a2cd-4c5a-baab-e7909b5fccff.png)

**Comment by jendib** [comment]
Please attach your server logs as well.

**Comment by dannykorpan** [comment]
Same problem here with another server. It has something to do with DNS resolution in the docker container.
