### ISSUE TITLE
Pdf Thumbnail generation & Fulltext search, not working on Demo

### ISSUE THREAD

**Issue by JPVenson** [sismics/docs#624]
[popular-physicsprize2020.pdf](https://github.com/sismics/docs/files/8104448/popular-physicsprize2020.pdf)
Using the attached PDF, i wanted to evaluate teedy via https://demo.teedy.io/. When uploaded the pdf, only the placeholder image was shown:

![image](https://user-images.githubusercontent.com/6794763/154854282-0ae9d9dc-3726-4a8e-9ff6-029ccdb2e52e.png)

Even after refreshing the site (with clear cache). Also even after reprocessing the file, searching for `full:Black` did not find the file.

**Comment by jendib** [comment]
@JPVenson do you have anything in logs?

**Comment by JPVenson** [comment]
@jendib Browser log? As I said, that was done via your demo site https://demo.teedy.io/ so no access to server logs

**Comment by JPVenson** [comment]
<html>
<body>


22/2/20 5:50 PM | FileUtil | Processing ended for file: a94c9f45-6f53-4901-b18a-5cf83599c99c
-- | -- | --
22/2/20 5:50 PM | FileProcessingAsyncListener | File content extracted in 0ms: a94c9f45-6f53-4901-b18a-5cf83599c99c
22/2/20 5:50 PM | FileProcessingAsyncListener | Error extracting content from: File{id=a94c9f45-6f53-4901-b18a-5cf83599c99c, name=popular-physicsprize2020.pdf}
22/2/20 5:50 PM | FileProcessingAsyncListener | Start extracting content from: File{id=a94c9f45-6f53-4901-b18a-5cf83599c99c, name=popular-physicsprize2020.pdf}
22/2/20 5:50 PM | FileProcessingAsyncListener | Unable to generate thumbnails for: File{id=a94c9f45-6f53-4901-b18a-5cf83599c99c, name=popular-physicsprize2020.pdf}
22/2/20 5:50 PM | FileProcessingAsyncListener | File updated event: FileUpdatedAsyncEvent{fileId=a94c9f45-6f53-4901-b18a-5cf83599c99c, language=eng}
22/2/20 5:50 PM | FileUtil | Processing started for file: a94c9f45-6f53-4901-b18a-5cf83599c99c
22/2/20 5:49 PM | FileUtil | Processing ended for file: a94c9f45-6f53-4901-b18a-5cf83599c99c
22/2/20 5:49 PM | FileProcessingAsyncListener | File content extracted in 1ms: a94c9f45-6f53-4901-b18a-5cf83599c99c
22/2/20 5:49 PM | FileProcessingAsyncListener | Error extracting content from: File{id=a94c9f45-6f53-4901-b18a-5cf83599c99c, name=popular-physicsprize2020.pdf}
22/2/20 5:49 PM | FileProcessingAsyncListener | Start extracting content from: File{id=a94c9f45-6f53-4901-b18a-5cf83599c99c, name=popular-physicsprize2020.pdf}
22/2/20 5:49 PM | FileProcessingAsyncListener | Unable to generate thumbnails for: File{id=a94c9f45-6f53-4901-b18a-5cf83599c99c, name=popular-physicsprize2020.pdf}
22/2/20 5:49 PM | DocumentUpdatedAsyncListener | Document updated event: DocumentUpdatedAsyncEvent{documentId=956ce36c-d6e6-4360-b484-e8233ab80445}
22/2/20 5:49 PM | FileProcessingAsyncListener | File updated event: FileUpdatedAsyncEvent{fileId=a94c9f45-6f53-4901-b18a-5cf83599c99c, language=eng}
22/2/20 5:49 PM | FileUtil | Processing started for file: a94c9f45-6f53-4901-b18a-5cf83599c99c
22/2/20 5:49 PM | DocumentCreatedAsyncListener | Document created event: DocumentCreatedAsyncEvent{documentId=956ce36c-d6e6-4360-b484-e8233ab80445}
22/2/20 5:49 PM | FileUtil | Processing ended for file: a94c9f45-6f53-4901-b18a-5cf83599c99c
22/2/20 5:49 PM | FileProcessingAsyncListener | File content extracted in 1ms: a94c9f45-6f53-4901-b18a-5cf83599c99c
22/2/20 5:49 PM | FileProcessingAsyncListener | Error extracting content from: File{id=a94c9f45-6f53-4901-b18a-5cf83599c99c, name=popular-physicsprize2020.pdf}
22/2/20 5:49 PM | FileProcessingAsyncListener | Start extracting content from: File{id=a94c9f45-6f53-4901-b18a-5cf83599c99c, name=popular-physicsprize2020.pdf}
22/2/20 5:49 PM | FileProcessingAsyncListener | Unable to generate thumbnails for: File{id=a94c9f45-6f53-4901-b18a-5cf83599c99c, name=popular-physicsprize2020.pdf}
22/2/20 5:49 PM | FileProcessingAsyncListener | File created event: FileCreatedAsyncEvent{fileId=a94c9f45-6f53-4901-b18a-5cf83599c99c, language=null}
22/2/20 5:49 PM | FileUtil | Processing started for file: a94c9f45-6f53-4901-b18a-5cf83599c99c


</body>
</html>

**Comment by jendib** [comment]
Thanks I'll check it out. There might be something specific to this PDF.

**Comment by jendib** [comment]
It was apparently only related to the demo server. I redeployed it and it works:
![image](https://user-images.githubusercontent.com/2623413/154855590-2cd1593c-7e41-4c9b-8f45-cf4b44593431.png)
