### ISSUE TITLE
Enhancement request: Inherit permissions on tags

### ISSUE THREAD

**Issue by Craneson** [sismics/docs#626]
I would appreciate an option for tags, to switch between explicit permissions and inheriting the parent-permissions.

An idea would be to take the windows-approach for file-permissions: by default each sub-tag inherits the permissions from the parent. When disabling inheritance, the user is given the choice to convert inherited permissions to explicit permissions.

**Comment by jendib** [comment]
Duplicate of #196
You can add your enabled/disabled toggle as comment over there.
