### ISSUE TITLE
Unable to login with admin after last update

### ISSUE THREAD

**Issue by dpajanssen** [sismics/docs#630]
Somehow i cannot login with the admin account anymore (incorrect username/password).
One regular user still works... is their an instruction on how to reset the admin password?

**Comment by jendib** [comment]
Is it related to https://github.com/sismics/docs/issues/547 ?

**Comment by dpajanssen** [comment]
Looks indeed the same issue.. but somehow i can't connect to the DB file also using DBeaver, some error: wrong username/password :(

**Comment by dpajanssen** [comment]
ahh username sa blanc password..worked.. will try the migration tomorrow

**Comment by dpajanssen** [comment]
Migration steps worked! Got all up and running again and the data is all back, thanks!
