### ISSUE TITLE
SSL Certificates

### ISSUE THREAD

**Issue by wolicape** [sismics/docs#633]
Hi, 

I'm looking for any documentation about how SSL Certificates are handled. We are looking for importing our own cert signed by Gandi, but for the moment we haven't figured out how to tell our Teedy server to use this certificate. If you have any documentation or information about it, i'm interested.

Thanks for your replies 😄

**Comment by jendib** [comment]
If you are referring to certs for https, I suggest you to use a reverse proxy to handle that.

**Comment by cocoonkid** [comment]
yes. Certificates are handled by your webserver/domain registrar.  Nothing to do with the application.
