### ISSUE TITLE
Behavior when searching for documents with an invalid date

### ISSUE THREAD

**Issue by archiloque** [sismics/docs#635]
After working on https://github.com/sismics/docs/pull/634 I noticed that the search behavior when searching for a date with an invalid formatted parameter is unexpected: currently it returns no result, but I wonder if returning an error like a `ClientException` would makes more sense since the data is invalid.

It shouldn't break the GUI since we can only enter valid dates with it.

What do you think of it ? I can write a PR for it if you agree.

**Comment by jendib** [comment]
We can enter invalid dates with the UI as well, if you type the search query manually.

**Comment by archiloque** [comment]
Didn't know that (we rarely use the GUI), thanks
