### ISSUE TITLE
Need help in accessing Teedy API

### ISSUE THREAD

**Issue by harishK16** [sismics/docs#636]
I am trying to access my self hosted Teedy through a java client from another server in order to perform some operations. I am able to login, get list, search through httpClient in Java however I am unable to get/download files through Java client. I am getting 404 in Java service., But in postman it works fine and returns the file.

Kindly help. Thanks in Advance.

Note : Cookie is sent appropriately, URL is correct. The same works fine in Postman.

Sample Code : 

HttpGet getFile = new HttpGet("http://localhost:8101/docs-web/api/file/a3c97ca8-435a-4839-8644-21d765ecb761/data"); 
post1.addHeader("Cookie", sessionID);
HttpClient httpClient1 = HttpClients.createDefault();
CloseableHttpResponse response2 = (CloseableHttpResponse) httpClient1.execute(getFile);
response2.close();

Response Error :
HTTP/1.1 500 Server Error [Cache-Control: must-revalidate,no-cache,no-store, Content-Type: text/html;charset=iso-8859-1, Connection: close, Server: Jetty(9.4.17.v20190418)]

**Comment by harishK16** [comment]
Hi jendib. Thanks for your response. I was able to debug the code and found that the user principal object was retrieved while I was hitting the application through Postman. But the same is not defined when I am trying to access the same API through http client. This happens only for few endpoints like api/file/zip which is little more secured.

Can you help me, so that I can get my issue resolved. I am not getting why the user principal is binding when

**Comment by jendib** [comment]
Do you have any logs to share?

**Comment by harishK16** [comment]
No there is no error in logs actually. The api is not returning expected response, as it is not having the user principal.

**Comment by harishK16** [comment]
The response to the API /api/file/zip with id and share as two params, Line no 690 - FileResource.java in resources package will return the response as a zip file if the user is authenticated and has an user principal attached to the request.

I have an active auth-token as a valid authentication, however the user principal is not attached to the request. That’s where I’m stuck up. But the same request when triggered from postman works as expected. Not sure why it is not working with httpclient in java.

**Comment by jendib** [comment]
Do you have any kind of complete reproducer then?

**Comment by harishK16** [comment]
I have resolved the issue for now by removing the permission checking logic in the getDocument method of DocumentDao class., However this is a way bringing the security of the API a way below down. I couldn't spot what is the difference as the API call works well in Postman and not in httpclient even appending the same auth-token in both the methods.
