### ISSUE TITLE
Teedy is always using internal Database and not Postgresql

### ISSUE THREAD

**Issue by akilani** [sismics/docs#640]
hi team;

i have repackaged teedy docker container and trying to have aws eks deployment, utilizing EFS for data store, and RDS for postgresql 

however i am facing currently an issue, teedy is always using internal database and not integrating with the RDS database despite all evn variables are set correctly with the correct creditntials

what would be a possible fix for this, and or right place to look into, as refering to this github, teedy is smart enought to know if postgresql is configured using the env variables and it will use psql instead of internal

artifacts used can be found on https://github.com/akilani/ab3/tree/main/infra/dms-large

**Comment by jendib** [comment]
The docker-compose.yml given as example works, so I'm not sure what's wrong with your deployment. Do you have any interesting log on the deployed pod ?

**Comment by akilani** [comment]
[Uploading ab3.log…]()

the env variables within the container is also pointing correctly , i tested even by doing manual psql command , and it is reachable.

**Comment by akilani** [comment]
[ab3.log.zip](https://github.com/sismics/docs/files/8749707/ab3.log.zip)
here is the log ,

**Comment by jendib** [comment]
I tested the following docker-compose.yml and it works as expected.
[docker-compose.zip](https://github.com/sismics/docs/files/8749849/docker-compose.zip)

However I just noticed that you are using a unknown image `akilani/docs:1.0`. Please use the official docker image and try again.

**Comment by akilani** [comment]
hi

true , yes i have recompiled the official teedy package by merely
rebranding the first screen landscape logo , but apparently , seems my
recompilation and repackaging had some issues.
i reverted to the use of the official image and it worked ,
these are the commands i used to recompile the source code.

mvn -Pprod -DskipTests=true install



 cp docs-web/target/docs-web-1.10.war
../build/docs/docs-web/target/docs-web-1.10.war



docker-compose down



docker build --rm -t mine/docs .



docker-compose up -d
