### ISSUE TITLE
User can not log in and can not be deleted

### ISSUE THREAD

**Issue by fulo821** [sismics/docs#652]
Hi,
I have a user who can not log in anymore.
The account can not be deleted by the admin
user.

I get the following messages in the log. Think
that there is a problem with the database.

01.10.22 22:27 | RequestContextFilter | An exception occured, rolling back current transaction
-- | -- | --
01.10.22 22:27 | SqlExceptionHelper | Timeout trying to lock table {0}; SQL statement: delete from T_AUTHENTICATION_TOKEN where AUT_IDUSER_C=? [50200-199]
01.10.22 22:27 | SqlExceptionHelper | SQL Error: 50200, SQLState: HYT00

01 Oct 2022 22:27:55,186 WARN org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions(SqlExceptionHelper.java:137) SQL Error: 50200
, SQLState: HYT00                                                                                                                         
01 Oct 2022 22:27:55,187 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions(SqlExceptionHelper.java:142) Timeout trying 
to lock table {0}; SQL statement:                                                                                                         
delete from T_AUTHENTICATION_TOKEN where AUT_IDUSER_C=? [50200-199]                                                                       
01 Oct 2022 22:27:55,198 ERROR com.sismics.util.filter.RequestContextFilter.doFilter(RequestContextFilter.java:95) An exception occured, r
olling back current transaction                                                                                                           
javax.servlet.ServletException: javax.persistence.QueryTimeoutException: could not execute statement  

Any idea to fix this problem?

**Comment by jendib** [comment]
It's a long time issue related to the database. You should migrate to PostgreSQL for production usage.
