### ISSUE TITLE
Password reset does not disable 2FA

### ISSUE THREAD

**Issue by serelsnauw** [sismics/docs#661]
Hi,

The password reset function does not disable 2FA for the user requesting a password reset.
If the user lost it's 2FA-code, and request a password reset, the user is still not able to login (in our case the admin user :-( )

Is there perhaps any other way to disable 2FA from the CLI on the docker container or database?
Any help would be much appreciated. :-)

Grtz Serel.

**Comment by vmario89** [comment]
Hi. Should be possible by modifying the following database table

at first have a look at your users:
```
SELECT
    use_id_c,
    use_idrole_c,
    use_username_c,
    use_totpkey_c
FROM t_user WHERE use_totpkey_c IS NOT NULL AND use_deletedate_d IS NULL;
```

then set to NULL to remove the 2FA for your user (i did not test the statement, because i have no test db at my hand right now)
`UPDATE t_user SET use_totpkey_c=NULL WHERE use_id_c = 'admin';`
