### ISSUE TITLE
LDAP_ADMIN_PASSWORD is not encrypted

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#667]
Hey,
i recognized that LDAP_ADMIN_PASSWORD is not encrypted in database. This value is highly sensible and should be stored as some hash value.

**Comment by jendib** [comment]
How do you think it could be done? The password needs to be sent to the LDAP server to connect.

**Comment by vmario89** [comment]
hm didn't you use some mechanism to encrypt/decrypt the default admin password in the database, too?

**Comment by jendib** [comment]
Users' password are stored hashed yes, but the authentication is done locally. LDAP protocol requires to send the plain text password (unless I'm mistaken)
