### ISSUE TITLE
Move from javax to jakarta dependencies

### ISSUE THREAD

**Issue by jendib** [sismics/docs#668]
- Jetty 11
- Jersey 3.0.9
- Servlet API 5.0

**Comment by jendib** [comment]
@vmario89 Do you think you could test the latest version? You opened the related ticket associated to Jetty 11.

**Comment by tgkenney** [comment]
I'm not him obviously, but I run the latest version of the docker image, and my container went down around the time you pushed the commit for this.  It's failing with this error: `Cannot find a start.ini file or a start.d directory in your JETTY_BASE directory: /opt/jetty`

Container is setup pretty much exactly as the docker-compose.yml in the repo

If you want any more details for debugging I'm more than happy to help

**Comment by jendib** [comment]
I still have this issue:
```
12 Apr 2023 17:42:53,636 WARN jakarta.persistence.spi.PersistenceProviderResolverHolder$DefaultPersistenceProviderResolver.log(PersistenceProviderResolverHolder.java:170) jakarta.persistence.spi::No valid providers found.
12 Apr 2023 17:42:53,638 ERROR com.sismics.util.jpa.EMF.<clinit>(EMF.java:58) Error creating EMF
jakarta.persistence.PersistenceException: No Persistence provider for EntityManager named transactions-optional
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:86)
        at com.sismics.util.jpa.EMF.<clinit>(EMF.java:55)
```
The persistence provider named "transactions-optional" is declared in persistence.xml but it seems to not be used. It's probably related to javax -> jakarta.

**Comment by jendib** [comment]
Fixed, it was a dependency issue.

**Comment by vmario89** [comment]
hi, i am going to check this out next days. i got some Raspberry Pi 4 as a test machine at the time. It's bare enough to route through all the steps to setup java + jetty + psql + teedy

**Comment by vmario89** [comment]
Hi, i opened some tickets at
* https://github.com/sismics/docs/issues/675
* https://github.com/sismics/docs/issues/676
* https://github.com/sismics/docs/issues/677

**Comment by vmario89** [comment]
and some info about the basic setup on a fresh system: https://github.com/sismics/docs/issues/679
