### ISSUE TITLE
faulty database / file recovery

### ISSUE THREAD

**Issue by fototeddy** [sismics/docs#671]
I have a somehow faulty database and there for cannot enter the web interface.
Also my backups do not help. Actually I don't know what the problem is except that there ist a timeout accessing the database on login.

nevermind. I have the stored files in the storage folder but don't know what file format they are. is there any way to recover the files from "storage" without getting the database running?

**Comment by jendib** [comment]
I will need log extracts if you want any assistance.

**Comment by fototeddy** [comment]
these are the Logs form starting and trying to login with my credentials

> 25 Mar 2023 16:17:21,445 INFO com.sismics.util.jpa.EMF.getEntityManagerProperties(EMF.java:82) Configuring EntityManager from environment parameters 
> 25 Mar 2023 16:17:26,439 INFO com.sismics.util.jpa.DbOpenHelper.open(DbOpenHelper.java:57) Opening database and executing incremental updates 
> 25 Mar 2023 16:17:26,455 INFO com.sismics.util.jpa.DbOpenHelper.open(DbOpenHelper.java:106) Found database version 27, new version is 27, executing database incremental update scripts 
> 25 Mar 2023 16:17:26,456 INFO com.sismics.util.jpa.DbOpenHelper.open(DbOpenHelper.java:108) Database upgrade complete 
> 25 Mar 2023 16:17:26,459 INFO com.sismics.util.jpa.EMF.getEntityManagerProperties(EMF.java:82) Configuring EntityManager from environment parameters 
> 25 Mar 2023 16:17:33,754 INFO com.sismics.util.ClasspathScanner.findClasses(ClasspathScanner.java:48) Found 1 classes for IndexingHandler 
> 25 Mar 2023 16:17:33,922 INFO com.sismics.docs.core.util.indexing.LuceneIndexingHandler.initLucene(LuceneIndexingHandler.java:118) Using file Lucene storage: /data/lucene 
> 25 Mar 2023 16:17:34,399 INFO com.sismics.docs.core.util.indexing.LuceneIndexingHandler.initLucene(LuceneIndexingHandler.java:130) Checking index health and version 
> 25 Mar 2023 16:17:35,567 INFO com.sismics.docs.core.service.FileService.startUp(FileService.java:39) File service starting up 
> 25 Mar 2023 16:17:35,585 INFO com.sismics.docs.core.service.InboxService.startUp(InboxService.java:55) Inbox service starting up 
> 25 Mar 2023 16:17:35,611 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:82) Synchronizing IMAP inbox... 
> 25 Mar 2023 16:17:38,380 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:92) 0 messages found 
> 25 Mar 2023 16:18:38,658 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:82) Synchronizing IMAP inbox... 
> 25 Mar 2023 16:18:40,072 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:92) 0 messages found 
> 25 Mar 2023 16:19:40,347 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:82) Synchronizing IMAP inbox... 
> 25 Mar 2023 16:19:41,746 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:92) 0 messages found 
> 25 Mar 2023 16:20:07,932 INFO com.sismics.util.ClasspathScanner.findClasses(ClasspathScanner.java:48) Found 2 classes for AuthenticationHandler 
> 25 Mar 2023 16:20:18,453 WARN org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions(SqlExceptionHelper.java:137) SQL Error: 50200, SQLState: HYT00 
> 25 Mar 2023 16:20:18,454 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions(SqlExceptionHelper.java:142) Timeout trying to lock table {0}; SQL statement:
> delete from T_AUTHENTICATION_TOKEN AS ato  where ato.AUT_IDUSER_C = ? and ato.AUT_LONGLASTED_B = ? and ato.AUT_LASTCONNECTIONDATE_D < ?  [50200-199] 
> 25 Mar 2023 16:20:18,483 ERROR com.sismics.util.filter.RequestContextFilter.doFilter(RequestContextFilter.java:95) An exception occured, rolling back current transaction 
> javax.servlet.ServletException: javax.persistence.QueryTimeoutException: could not execute statement
> 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
> 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
> 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
> 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
> 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
> 	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
> 	at com.sismics.util.filter.SecurityFilter.doFilter(SecurityFilter.java:134)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
> 	at com.sismics.util.filter.SecurityFilter.doFilter(SecurityFilter.java:134)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
> 	at com.sismics.util.filter.RequestContextFilter.doFilter(RequestContextFilter.java:89)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
> 	at com.sismics.util.filter.CorsFilter.doFilter(CorsFilter.java:39)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
> 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:501)
> 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
> 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
> 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
> 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: javax.persistence.QueryTimeoutException: could not execute statement
> 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:113)
> 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
> 	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1681)
> 	at com.sismics.docs.core.dao.AuthenticationTokenDao.deleteOldSessionToken(AuthenticationTokenDao.java:78)
> 	at com.sismics.docs.rest.resource.UserResource.login(UserResource.java:374)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
> 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
> 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
> 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
> 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
> 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
> 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
> 	... 49 more
> Caused by: org.hibernate.QueryTimeoutException: could not execute statement
> 	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:66)
> 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
> 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
> 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
> 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
> 	at org.hibernate.engine.query.spi.NativeSQLQueryPlan.performExecuteUpdate(NativeSQLQueryPlan.java:107)
> 	at org.hibernate.internal.SessionImpl.executeNativeUpdate(SessionImpl.java:1509)
> 	at org.hibernate.query.internal.NativeQueryImpl.doExecuteUpdate(NativeQueryImpl.java:298)
> 	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1672)
> 	... 73 more
> Caused by: org.h2.jdbc.JdbcSQLTimeoutException: Timeout trying to lock table {0}; SQL statement:
> delete from T_AUTHENTICATION_TOKEN AS ato  where ato.AUT_IDUSER_C = ? and ato.AUT_LONGLASTED_B = ? and ato.AUT_LASTCONNECTIONDATE_D < ?  [50200-199]
> 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
> 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
> 	at org.h2.message.DbException.get(DbException.java:194)
> 	at org.h2.command.Command.filterConcurrentUpdate(Command.java:333)
> 	at org.h2.command.Command.executeUpdate(Command.java:274)
> 	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
> 	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
> 	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1502)
> 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
> 	... 77 more
> Caused by: org.h2.message.DbException: Row "115" not found in primary index "PUBLIC.T_AUTHENTICATION_TOKEN_DATA" [90143-199]
> 	at org.h2.message.DbException.get(DbException.java:205)
> 	at org.h2.mvstore.db.MVPrimaryIndex.getRow(MVPrimaryIndex.java:274)
> 	at org.h2.mvstore.db.MVTable.getRow(MVTable.java:338)
> 	at org.h2.mvstore.db.MVSecondaryIndex$MVStoreCursor.get(MVSecondaryIndex.java:455)
> 	at org.h2.index.IndexCursor.get(IndexCursor.java:274)
> 	at org.h2.table.TableFilter.getValue(TableFilter.java:1092)
> 	at org.h2.expression.ExpressionColumn.getValue(ExpressionColumn.java:215)
> 	at org.h2.expression.condition.Comparison.getValue(Comparison.java:271)
> 	at org.h2.expression.condition.ConditionAndOr.getValue(ConditionAndOr.java:89)
> 	at org.h2.expression.Expression.getBooleanValue(Expression.java:259)
> 	at org.h2.command.dml.Delete.update(Delete.java:91)
> 	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
> 	at org.h2.command.Command.executeUpdate(Command.java:267)
> 	... 81 more
> Caused by: org.h2.jdbc.JdbcSQLTransientException: Row "115" not found in primary index "PUBLIC.T_AUTHENTICATION_TOKEN_DATA" [90143-199]
> 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:621)
> 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
> 	... 94 more
> 25 Mar 2023 16:20:42,022 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:82) Synchronizing IMAP inbox... 
> 25 Mar 2023 16:20:43,461 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:92) 0 messages found

**Comment by jendib** [comment]
It's probably the same issue as https://github.com/sismics/docs/issues/547

**Comment by fototeddy** [comment]
that worked, thanks a lot.

is there a good way to export all files for a second backup?

**Comment by jendib** [comment]
While it's working you can use the API to extract all documents (but you need to create a script for that), otherwise simply backing up the database and the encrypted files is enough (the private key is in the database).
