### ISSUE TITLE
JS transition bug at really first login for Teedy 1.12dev

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#676]
Hi,
the following error occures when logging in the admin:admin user first time. As you can see the ui is malformed and buttons are missing. Refreshing the page leads to a working interface. But its irritating for fresh users.
![image](https://user-images.githubusercontent.com/5631071/232345656-7f4903de-e8c0-4c7d-8043-b7bbeffd077b.png)

**Comment by jendib** [comment]
I cannot reproduce this issue on Firefox on Chrome. I'm getting the error message but the UI is good. Are you doing anything special?

**Comment by jendib** [comment]
@vmario89
