### ISSUE TITLE
Applying setting changes leads to XML error (Teedy 1.12dev)

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#677]
Hi,
a fresh instance of 1.12dev shows the following console error when changing/saving new values in the UI. The values are stored and work, but the error is given:
![image](https://user-images.githubusercontent.com/5631071/232345718-2f3ead37-a0db-4eb0-a8f9-d37326b77abe.png)

basically it says sth. like "XML processing error: No root element found" - sorry for the german version

**Comment by jendib** [comment]
It seems to be a Firefox only issue. I don't think it's worth it to fix it considering it's not causing any problem.

**Comment by vmario89** [comment]
Might be true. I did not test it twice because i just recognized it when setting up the test instance. If this occures again, i will repost it maybe into this issue. Or it might fix itself with a newer release of firefox. Who knows :)
