### ISSUE TITLE
Since jetty11 locale is always ENGLISH

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#685]
Hi,
i have an issue compiling the recent github master. I recognized that is always english and it does not matter which client device (android, fedora linux) or browser (firefox, chromium) i use.

i played with
*  /docs-core/src/main/java/com/sismics/util/LocaleUtil.java to override it returning german
* setting Environment="LANG=de_DE.UTF-8" in systemd unit
* changing the angular locale in the docs-web app.js file

nothing changed it from german to english.

do you have an idea what it could be?

**Comment by vmario89** [comment]
using `localectl` to change LANG from en_US.UTF-8 to de_DE.UTF-8 does not change anything too

**Comment by vmario89** [comment]
![grafik](https://user-images.githubusercontent.com/5631071/236652833-fa698ce5-9db2-4327-ac9e-dbcf27ba5f46.png)
okay found the configuriration for lang at the bottom. indeed it seems that only german does not work. maybe me or sb else destroyed a locale file last commits .. :-(

**Comment by vmario89** [comment]
and there it is https://github.com/sismics/docs/pull/686 ...

**Comment by jendib** [comment]
Thanks, merged.
