### ISSUE TITLE
Possible to search the list of tags? 

### ISSUE THREAD

**Issue by WGandy** [sismics/docs#690]
When I first started playing with the Teedy interface i was surprised that I couldn't just search for items with a specific tag using the search box. But then I realized that I could switch the interface to show tags in a similar way to folders and find a tag that way. But, if I have lots of tags, then I still think I might like a way to search for a tag. 

A) 
Ideally, especially for the novice user, simply searching for a word in the search box would show results for items tagged with that word. Is this something that exists and I can't find? 

B) 
Is it possible to search the list of tags or is the only way to find all the docs with a given tag by scrolling through them alphabetically?

**Comment by vmario89** [comment]
for A) https://stadtfabrikanten.org/display/TEED/Teedy+1.12+Searching+and+Tags might help

B) you can search over all tags by using the integrated API -> https://demo.teedy.io/apidoc/#api-Tag-GetTagList
our you can use postgresql, like https://stadtfabrikanten.org/display/TEED/Auto-delete+guest+tags
