### ISSUE TITLE
Duplication bug in quick file upload

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#700]
Hey,
just a funny bug i figured out after years, when accidently picking an element and doing some drag and drop. "data" is created. Seems it just multiplies the file:
https://github.com/sismics/docs/assets/5631071/20103694-ece6-4a02-b986-d1979a34c0a2

**Comment by jendib** [comment]
You are actually drag & dropping the thumbnail of the first document as a new file. I don't think anything can be done about it, it's the default browser behavior.
