### ISSUE TITLE
Password is always wrong when deploying via docker-compose

### ISSUE THREAD

**Issue by JulianGro** [sismics/docs#729]
When trying to log into teedy, it always complains that the username or password is invalid.
As username, I have tried both `admin` and the email address supplied in the docker-compose.yml.
For a password, I have tried setting a password by supplying a bcrypted string with `$` escaped using an additional `$` for every occurrence, and I have tried just keeping the default. Both fail. Supplying a cleartext password also fails.

Since other issues suggested database corruption, I tried stopping both containers, deleting all Docker data using
```
docker system prune --all --force --volumes
```
and recreating via docker-compose. Again, “Username or password invalid”

**Comment by JulianGro** [comment]
Apparently the database is saved outside of Docker, which is good, but I didn't realize that this was the case.
Deleting it and retrying worked.

Maybe there should be a comment in the README.md noting that the DOCS_ADMIN_PASSWORD_INIT cannot be changed by just recreating the containers?
Or what I feel is more fool-proof, would be to not even put DOCS_ADMIN_PASSWORD_INIT in the default docker-compose and just assume a default if it is missing. People can then just change their password after logging in (or not if they just use the thing locally).

**Comment by Mohamed-sobhi95** [comment]
> Apparently the database is saved outside of Docker, which is good, but I didn't realize that this was the case. Deleting it and retrying worked.
> 
> Maybe there should be a comment in the README.md noting that the DOCS_ADMIN_PASSWORD_INIT cannot be changed by just recreating the containers? Or what I feel is more fool-proof, would be to not even put DOCS_ADMIN_PASSWORD_INIT in the default docker-compose and just assume a default if it is missing. People can then just change their password after logging in (or not if they just use the thing locally).

how to delete it ?
