### ISSUE TITLE
Fresh docker installataion - Username or password invalid

### ISSUE THREAD

**Issue by thehijacker** [sismics/docs#746]
Hello. Copy paste from the docker compose sample. Only change was the domain and email. But I can not login no matter what. Default password superSecure is not working with email or admin as user. I tried changing it with my own (with double $). But it is the same.

Using latest image tag.

Any ideas?

**Comment by BoringKraken** [comment]
having the exact same issue, tried changing username, password, and base url no luck.

is there something im missing?

**Comment by mv-stns** [comment]
Credentials in a fresh install are mentioned in the compose file as "superSecure". The username is "admin". It should definitely be mentioned in the documentation.

**Comment by Mohamed-sobhi95** [comment]
i have same problem
